// Code generated by MockGen. DO NOT EDIT.
// Source: activities.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
	metadata "github.com/feral-file/ff-indexer-v2/internal/metadata"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// CheckTokenExistsActivity mocks base method.
func (m *MockExecutor) CheckTokenExistsActivity(ctx context.Context, tokenCID domain.TokenCID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTokenExistsActivity", ctx, tokenCID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTokenExistsActivity indicates an expected call of CheckTokenExistsActivity.
func (mr *MockExecutorMockRecorder) CheckTokenExistsActivity(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTokenExistsActivity", reflect.TypeOf((*MockExecutor)(nil).CheckTokenExistsActivity), ctx, tokenCID)
}

// CreateMetadataUpdateActivity mocks base method.
func (m *MockExecutor) CreateMetadataUpdateActivity(ctx context.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetadataUpdateActivity", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMetadataUpdateActivity indicates an expected call of CreateMetadataUpdateActivity.
func (mr *MockExecutorMockRecorder) CreateMetadataUpdateActivity(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetadataUpdateActivity", reflect.TypeOf((*MockExecutor)(nil).CreateMetadataUpdateActivity), ctx, event)
}

// CreateTokenMintActivity mocks base method.
func (m *MockExecutor) CreateTokenMintActivity(ctx context.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTokenMintActivity", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTokenMintActivity indicates an expected call of CreateTokenMintActivity.
func (mr *MockExecutorMockRecorder) CreateTokenMintActivity(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTokenMintActivity", reflect.TypeOf((*MockExecutor)(nil).CreateTokenMintActivity), ctx, event)
}

// FetchTokenMetadataActivity mocks base method.
func (m *MockExecutor) FetchTokenMetadataActivity(ctx context.Context, tokenCID domain.TokenCID) (*metadata.NormalizedMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTokenMetadataActivity", ctx, tokenCID)
	ret0, _ := ret[0].(*metadata.NormalizedMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTokenMetadataActivity indicates an expected call of FetchTokenMetadataActivity.
func (mr *MockExecutorMockRecorder) FetchTokenMetadataActivity(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTokenMetadataActivity", reflect.TypeOf((*MockExecutor)(nil).FetchTokenMetadataActivity), ctx, tokenCID)
}

// IndexTokenWithFullProvenancesActivity mocks base method.
func (m *MockExecutor) IndexTokenWithFullProvenancesActivity(ctx context.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenWithFullProvenancesActivity", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenWithFullProvenancesActivity indicates an expected call of IndexTokenWithFullProvenancesActivity.
func (mr *MockExecutorMockRecorder) IndexTokenWithFullProvenancesActivity(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenWithFullProvenancesActivity", reflect.TypeOf((*MockExecutor)(nil).IndexTokenWithFullProvenancesActivity), ctx, event)
}

// IndexTokenWithMinimalProvenancesActivity mocks base method.
func (m *MockExecutor) IndexTokenWithMinimalProvenancesActivity(ctx context.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenWithMinimalProvenancesActivity", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenWithMinimalProvenancesActivity indicates an expected call of IndexTokenWithMinimalProvenancesActivity.
func (mr *MockExecutorMockRecorder) IndexTokenWithMinimalProvenancesActivity(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenWithMinimalProvenancesActivity", reflect.TypeOf((*MockExecutor)(nil).IndexTokenWithMinimalProvenancesActivity), ctx, event)
}

// UpdateTokenBurnActivity mocks base method.
func (m *MockExecutor) UpdateTokenBurnActivity(ctx context.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenBurnActivity", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenBurnActivity indicates an expected call of UpdateTokenBurnActivity.
func (mr *MockExecutorMockRecorder) UpdateTokenBurnActivity(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenBurnActivity", reflect.TypeOf((*MockExecutor)(nil).UpdateTokenBurnActivity), ctx, event)
}

// UpdateTokenTransferActivity mocks base method.
func (m *MockExecutor) UpdateTokenTransferActivity(ctx context.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenTransferActivity", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenTransferActivity indicates an expected call of UpdateTokenTransferActivity.
func (mr *MockExecutorMockRecorder) UpdateTokenTransferActivity(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenTransferActivity", reflect.TypeOf((*MockExecutor)(nil).UpdateTokenTransferActivity), ctx, event)
}

// UpsertTokenMetadataActivity mocks base method.
func (m *MockExecutor) UpsertTokenMetadataActivity(ctx context.Context, tokenCID domain.TokenCID, metadata *metadata.NormalizedMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTokenMetadataActivity", ctx, tokenCID, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTokenMetadataActivity indicates an expected call of UpsertTokenMetadataActivity.
func (mr *MockExecutorMockRecorder) UpsertTokenMetadataActivity(ctx, tokenCID, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTokenMetadataActivity", reflect.TypeOf((*MockExecutor)(nil).UpsertTokenMetadataActivity), ctx, tokenCID, metadata)
}
