// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=../../mocks/api_handler.go -package=mocks -mock_names=Handler=MockAPIHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIHandler is a mock of Handler interface.
type MockAPIHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAPIHandlerMockRecorder
	isgomock struct{}
}

// MockAPIHandlerMockRecorder is the mock recorder for MockAPIHandler.
type MockAPIHandlerMockRecorder struct {
	mock *MockAPIHandler
}

// NewMockAPIHandler creates a new mock instance.
func NewMockAPIHandler(ctrl *gomock.Controller) *MockAPIHandler {
	mock := &MockAPIHandler{ctrl: ctrl}
	mock.recorder = &MockAPIHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIHandler) EXPECT() *MockAPIHandlerMockRecorder {
	return m.recorder
}

// CreateWebhookClient mocks base method.
func (m *MockAPIHandler) CreateWebhookClient(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateWebhookClient", c)
}

// CreateWebhookClient indicates an expected call of CreateWebhookClient.
func (mr *MockAPIHandlerMockRecorder) CreateWebhookClient(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhookClient", reflect.TypeOf((*MockAPIHandler)(nil).CreateWebhookClient), c)
}

// GetAddressIndexingJob mocks base method.
func (m *MockAPIHandler) GetAddressIndexingJob(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAddressIndexingJob", c)
}

// GetAddressIndexingJob indicates an expected call of GetAddressIndexingJob.
func (mr *MockAPIHandlerMockRecorder) GetAddressIndexingJob(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressIndexingJob", reflect.TypeOf((*MockAPIHandler)(nil).GetAddressIndexingJob), c)
}

// GetJobStatus mocks base method.
func (m *MockAPIHandler) GetJobStatus(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetJobStatus", c)
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockAPIHandlerMockRecorder) GetJobStatus(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockAPIHandler)(nil).GetJobStatus), c)
}

// GetToken mocks base method.
func (m *MockAPIHandler) GetToken(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetToken", c)
}

// GetToken indicates an expected call of GetToken.
func (mr *MockAPIHandlerMockRecorder) GetToken(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockAPIHandler)(nil).GetToken), c)
}

// HealthCheck mocks base method.
func (m *MockAPIHandler) HealthCheck(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HealthCheck", c)
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockAPIHandlerMockRecorder) HealthCheck(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockAPIHandler)(nil).HealthCheck), c)
}

// ListTokens mocks base method.
func (m *MockAPIHandler) ListTokens(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListTokens", c)
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockAPIHandlerMockRecorder) ListTokens(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockAPIHandler)(nil).ListTokens), c)
}

// SyncCollection mocks base method.
func (m *MockAPIHandler) SyncCollection(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SyncCollection", c)
}

// SyncCollection indicates an expected call of SyncCollection.
func (mr *MockAPIHandlerMockRecorder) SyncCollection(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncCollection", reflect.TypeOf((*MockAPIHandler)(nil).SyncCollection), c)
}

// TriggerAddressIndexing mocks base method.
func (m *MockAPIHandler) TriggerAddressIndexing(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerAddressIndexing", c)
}

// TriggerAddressIndexing indicates an expected call of TriggerAddressIndexing.
func (mr *MockAPIHandlerMockRecorder) TriggerAddressIndexing(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerAddressIndexing", reflect.TypeOf((*MockAPIHandler)(nil).TriggerAddressIndexing), c)
}

// TriggerMetadataIndexing mocks base method.
func (m *MockAPIHandler) TriggerMetadataIndexing(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerMetadataIndexing", c)
}

// TriggerMetadataIndexing indicates an expected call of TriggerMetadataIndexing.
func (mr *MockAPIHandlerMockRecorder) TriggerMetadataIndexing(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerMetadataIndexing", reflect.TypeOf((*MockAPIHandler)(nil).TriggerMetadataIndexing), c)
}

// TriggerTokenIndexing mocks base method.
func (m *MockAPIHandler) TriggerTokenIndexing(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerTokenIndexing", c)
}

// TriggerTokenIndexing indicates an expected call of TriggerTokenIndexing.
func (mr *MockAPIHandlerMockRecorder) TriggerTokenIndexing(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerTokenIndexing", reflect.TypeOf((*MockAPIHandler)(nil).TriggerTokenIndexing), c)
}
