// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockArtBlocksClient is a mock of Client interface.
type MockArtBlocksClient struct {
	ctrl     *gomock.Controller
	recorder *MockArtBlocksClientMockRecorder
}

// MockArtBlocksClientMockRecorder is the mock recorder for MockArtBlocksClient.
type MockArtBlocksClientMockRecorder struct {
	mock *MockArtBlocksClient
}

// NewMockArtBlocksClient creates a new mock instance.
func NewMockArtBlocksClient(ctrl *gomock.Controller) *MockArtBlocksClient {
	mock := &MockArtBlocksClient{ctrl: ctrl}
	mock.recorder = &MockArtBlocksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtBlocksClient) EXPECT() *MockArtBlocksClientMockRecorder {
	return m.recorder
}
