// Code generated by MockGen. DO NOT EDIT.
// Source: blacklist.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
	registry "github.com/feral-file/ff-indexer-v2/internal/registry"
)

// MockBlacklistRegistry is a mock of BlacklistRegistry interface.
type MockBlacklistRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistRegistryMockRecorder
}

// MockBlacklistRegistryMockRecorder is the mock recorder for MockBlacklistRegistry.
type MockBlacklistRegistryMockRecorder struct {
	mock *MockBlacklistRegistry
}

// NewMockBlacklistRegistry creates a new mock instance.
func NewMockBlacklistRegistry(ctrl *gomock.Controller) *MockBlacklistRegistry {
	mock := &MockBlacklistRegistry{ctrl: ctrl}
	mock.recorder = &MockBlacklistRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklistRegistry) EXPECT() *MockBlacklistRegistryMockRecorder {
	return m.recorder
}

// IsBlacklisted mocks base method.
func (m *MockBlacklistRegistry) IsBlacklisted(chainID domain.Chain, contractAddress string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlacklisted", chainID, contractAddress)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBlacklisted indicates an expected call of IsBlacklisted.
func (mr *MockBlacklistRegistryMockRecorder) IsBlacklisted(chainID, contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlacklisted", reflect.TypeOf((*MockBlacklistRegistry)(nil).IsBlacklisted), chainID, contractAddress)
}

// IsTokenCIDBlacklisted mocks base method.
func (m *MockBlacklistRegistry) IsTokenCIDBlacklisted(tokenCID domain.TokenCID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenCIDBlacklisted", tokenCID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTokenCIDBlacklisted indicates an expected call of IsTokenCIDBlacklisted.
func (mr *MockBlacklistRegistryMockRecorder) IsTokenCIDBlacklisted(tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenCIDBlacklisted", reflect.TypeOf((*MockBlacklistRegistry)(nil).IsTokenCIDBlacklisted), tokenCID)
}

// MockBlacklistRegistryLoader is a mock of BlacklistRegistryLoader interface.
type MockBlacklistRegistryLoader struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistRegistryLoaderMockRecorder
}

// MockBlacklistRegistryLoaderMockRecorder is the mock recorder for MockBlacklistRegistryLoader.
type MockBlacklistRegistryLoaderMockRecorder struct {
	mock *MockBlacklistRegistryLoader
}

// NewMockBlacklistRegistryLoader creates a new mock instance.
func NewMockBlacklistRegistryLoader(ctrl *gomock.Controller) *MockBlacklistRegistryLoader {
	mock := &MockBlacklistRegistryLoader{ctrl: ctrl}
	mock.recorder = &MockBlacklistRegistryLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklistRegistryLoader) EXPECT() *MockBlacklistRegistryLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockBlacklistRegistryLoader) Load(filePath string) (registry.BlacklistRegistry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", filePath)
	ret0, _ := ret[0].(registry.BlacklistRegistry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockBlacklistRegistryLoaderMockRecorder) Load(filePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockBlacklistRegistryLoader)(nil).Load), filePath)
}
