// Code generated by MockGen. DO NOT EDIT.
// Source: head.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBlockHeadProvider is a mock of BlockHeadProvider interface.
type MockBlockHeadProvider struct {
	ctrl     *gomock.Controller
	recorder *MockBlockHeadProviderMockRecorder
}

// MockBlockHeadProviderMockRecorder is the mock recorder for MockBlockHeadProvider.
type MockBlockHeadProviderMockRecorder struct {
	mock *MockBlockHeadProvider
}

// NewMockBlockHeadProvider creates a new mock instance.
func NewMockBlockHeadProvider(ctrl *gomock.Controller) *MockBlockHeadProvider {
	mock := &MockBlockHeadProvider{ctrl: ctrl}
	mock.recorder = &MockBlockHeadProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockHeadProvider) EXPECT() *MockBlockHeadProviderMockRecorder {
	return m.recorder
}

// GetLatestBlock mocks base method.
func (m *MockBlockHeadProvider) GetLatestBlock(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlock", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlock indicates an expected call of GetLatestBlock.
func (mr *MockBlockHeadProviderMockRecorder) GetLatestBlock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlock", reflect.TypeOf((*MockBlockHeadProvider)(nil).GetLatestBlock), ctx)
}

// MockBlockFetcher is a mock of BlockFetcher interface.
type MockBlockFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockBlockFetcherMockRecorder
}

// MockBlockFetcherMockRecorder is the mock recorder for MockBlockFetcher.
type MockBlockFetcherMockRecorder struct {
	mock *MockBlockFetcher
}

// NewMockBlockFetcher creates a new mock instance.
func NewMockBlockFetcher(ctrl *gomock.Controller) *MockBlockFetcher {
	mock := &MockBlockFetcher{ctrl: ctrl}
	mock.recorder = &MockBlockFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockFetcher) EXPECT() *MockBlockFetcherMockRecorder {
	return m.recorder
}

// FetchLatestBlock mocks base method.
func (m *MockBlockFetcher) FetchLatestBlock(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLatestBlock", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLatestBlock indicates an expected call of FetchLatestBlock.
func (mr *MockBlockFetcherMockRecorder) FetchLatestBlock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLatestBlock", reflect.TypeOf((*MockBlockFetcher)(nil).FetchLatestBlock), ctx)
}
