// Code generated by MockGen. DO NOT EDIT.
// Source: source.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	blockchain "github.com/feral-file/ff-indexer-v2/internal/blockchain"
	gomock "github.com/golang/mock/gomock"
)

// MockBlockchainEventSource is a mock of EventSource interface.
type MockBlockchainEventSource struct {
	ctrl     *gomock.Controller
	recorder *MockBlockchainEventSourceMockRecorder
}

// MockBlockchainEventSourceMockRecorder is the mock recorder for MockBlockchainEventSource.
type MockBlockchainEventSourceMockRecorder struct {
	mock *MockBlockchainEventSource
}

// NewMockBlockchainEventSource creates a new mock instance.
func NewMockBlockchainEventSource(ctrl *gomock.Controller) *MockBlockchainEventSource {
	mock := &MockBlockchainEventSource{ctrl: ctrl}
	mock.recorder = &MockBlockchainEventSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockchainEventSource) EXPECT() *MockBlockchainEventSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBlockchainEventSource) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockBlockchainEventSourceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBlockchainEventSource)(nil).Close))
}

// GetLatestBlock mocks base method.
func (m *MockBlockchainEventSource) GetLatestBlock(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlock", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlock indicates an expected call of GetLatestBlock.
func (mr *MockBlockchainEventSourceMockRecorder) GetLatestBlock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlock", reflect.TypeOf((*MockBlockchainEventSource)(nil).GetLatestBlock), ctx)
}

// SubscribeEvents mocks base method.
func (m *MockBlockchainEventSource) SubscribeEvents(ctx context.Context, fromBlock uint64, handler blockchain.EventHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeEvents", ctx, fromBlock, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeEvents indicates an expected call of SubscribeEvents.
func (mr *MockBlockchainEventSourceMockRecorder) SubscribeEvents(ctx, fromBlock, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEvents", reflect.TypeOf((*MockBlockchainEventSource)(nil).SubscribeEvents), ctx, fromBlock, handler)
}
