// Code generated by MockGen. DO NOT EDIT.
// Source: browser_rasterizer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBrowserRasterizer is a mock of BrowserRasterizer interface.
type MockBrowserRasterizer struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserRasterizerMockRecorder
}

// MockBrowserRasterizerMockRecorder is the mock recorder for MockBrowserRasterizer.
type MockBrowserRasterizerMockRecorder struct {
	mock *MockBrowserRasterizer
}

// NewMockBrowserRasterizer creates a new mock instance.
func NewMockBrowserRasterizer(ctrl *gomock.Controller) *MockBrowserRasterizer {
	mock := &MockBrowserRasterizer{ctrl: ctrl}
	mock.recorder = &MockBrowserRasterizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowserRasterizer) EXPECT() *MockBrowserRasterizerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBrowserRasterizer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrowserRasterizerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrowserRasterizer)(nil).Close))
}

// RasterizeSVG mocks base method.
func (m *MockBrowserRasterizer) RasterizeSVG(ctx context.Context, svgData []byte, width int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RasterizeSVG", ctx, svgData, width)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RasterizeSVG indicates an expected call of RasterizeSVG.
func (mr *MockBrowserRasterizerMockRecorder) RasterizeSVG(ctx, svgData, width interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RasterizeSVG", reflect.TypeOf((*MockBrowserRasterizer)(nil).RasterizeSVG), ctx, svgData, width)
}
