// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapter/chromedp.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapter/chromedp.go -destination=internal/mocks/chromedp.go -package=mocks -mock_names=ChromedpClient=MockChromedpClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	fetch "github.com/chromedp/cdproto/fetch"
	network "github.com/chromedp/cdproto/network"
	chromedp "github.com/chromedp/chromedp"
	gomock "go.uber.org/mock/gomock"
)

// MockChromedpClient is a mock of ChromedpClient interface.
type MockChromedpClient struct {
	ctrl     *gomock.Controller
	recorder *MockChromedpClientMockRecorder
	isgomock struct{}
}

// MockChromedpClientMockRecorder is the mock recorder for MockChromedpClient.
type MockChromedpClientMockRecorder struct {
	mock *MockChromedpClient
}

// NewMockChromedpClient creates a new mock instance.
func NewMockChromedpClient(ctrl *gomock.Controller) *MockChromedpClient {
	mock := &MockChromedpClient{ctrl: ctrl}
	mock.recorder = &MockChromedpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChromedpClient) EXPECT() *MockChromedpClientMockRecorder {
	return m.recorder
}

// AddScriptToEvaluateOnNewDocument mocks base method.
func (m *MockChromedpClient) AddScriptToEvaluateOnNewDocument(source string) chromedp.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddScriptToEvaluateOnNewDocument", source)
	ret0, _ := ret[0].(chromedp.Action)
	return ret0
}

// AddScriptToEvaluateOnNewDocument indicates an expected call of AddScriptToEvaluateOnNewDocument.
func (mr *MockChromedpClientMockRecorder) AddScriptToEvaluateOnNewDocument(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddScriptToEvaluateOnNewDocument", reflect.TypeOf((*MockChromedpClient)(nil).AddScriptToEvaluateOnNewDocument), source)
}

// CaptureScreenshot mocks base method.
func (m *MockChromedpClient) CaptureScreenshot(result *[]byte) chromedp.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CaptureScreenshot", result)
	ret0, _ := ret[0].(chromedp.Action)
	return ret0
}

// CaptureScreenshot indicates an expected call of CaptureScreenshot.
func (mr *MockChromedpClientMockRecorder) CaptureScreenshot(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureScreenshot", reflect.TypeOf((*MockChromedpClient)(nil).CaptureScreenshot), result)
}

// ContinueRequest mocks base method.
func (m *MockChromedpClient) ContinueRequest(ctx context.Context, id fetch.RequestID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContinueRequest", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContinueRequest indicates an expected call of ContinueRequest.
func (mr *MockChromedpClientMockRecorder) ContinueRequest(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContinueRequest", reflect.TypeOf((*MockChromedpClient)(nil).ContinueRequest), ctx, id)
}

// EmulateViewport mocks base method.
func (m *MockChromedpClient) EmulateViewport(width, height int64) chromedp.EmulateAction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmulateViewport", width, height)
	ret0, _ := ret[0].(chromedp.EmulateAction)
	return ret0
}

// EmulateViewport indicates an expected call of EmulateViewport.
func (mr *MockChromedpClientMockRecorder) EmulateViewport(width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmulateViewport", reflect.TypeOf((*MockChromedpClient)(nil).EmulateViewport), width, height)
}

// Evaluate mocks base method.
func (m *MockChromedpClient) Evaluate(expr string, result any, options ...chromedp.EvaluateOption) chromedp.EvaluateAction {
	m.ctrl.T.Helper()
	varargs := []any{expr, result}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Evaluate", varargs...)
	ret0, _ := ret[0].(chromedp.EvaluateAction)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockChromedpClientMockRecorder) Evaluate(expr, result any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{expr, result}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockChromedpClient)(nil).Evaluate), varargs...)
}

// FailRequest mocks base method.
func (m *MockChromedpClient) FailRequest(ctx context.Context, id fetch.RequestID, reason network.ErrorReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailRequest", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailRequest indicates an expected call of FailRequest.
func (mr *MockChromedpClientMockRecorder) FailRequest(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailRequest", reflect.TypeOf((*MockChromedpClient)(nil).FailRequest), ctx, id, reason)
}

// FetchEnable mocks base method.
func (m *MockChromedpClient) FetchEnable() chromedp.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchEnable")
	ret0, _ := ret[0].(chromedp.Action)
	return ret0
}

// FetchEnable indicates an expected call of FetchEnable.
func (mr *MockChromedpClientMockRecorder) FetchEnable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchEnable", reflect.TypeOf((*MockChromedpClient)(nil).FetchEnable))
}

// FullScreenshot mocks base method.
func (m *MockChromedpClient) FullScreenshot(result *[]byte, quality int) chromedp.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullScreenshot", result, quality)
	ret0, _ := ret[0].(chromedp.Action)
	return ret0
}

// FullScreenshot indicates an expected call of FullScreenshot.
func (mr *MockChromedpClientMockRecorder) FullScreenshot(result, quality any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullScreenshot", reflect.TypeOf((*MockChromedpClient)(nil).FullScreenshot), result, quality)
}

// ListenTarget mocks base method.
func (m *MockChromedpClient) ListenTarget(ctx context.Context, fn func(any)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenTarget", ctx, fn)
}

// ListenTarget indicates an expected call of ListenTarget.
func (mr *MockChromedpClientMockRecorder) ListenTarget(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenTarget", reflect.TypeOf((*MockChromedpClient)(nil).ListenTarget), ctx, fn)
}

// Navigate mocks base method.
func (m *MockChromedpClient) Navigate(url string) chromedp.NavigateAction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Navigate", url)
	ret0, _ := ret[0].(chromedp.NavigateAction)
	return ret0
}

// Navigate indicates an expected call of Navigate.
func (mr *MockChromedpClientMockRecorder) Navigate(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Navigate", reflect.TypeOf((*MockChromedpClient)(nil).Navigate), url)
}

// NewContext mocks base method.
func (m *MockChromedpClient) NewContext(ctx context.Context) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewContext", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// NewContext indicates an expected call of NewContext.
func (mr *MockChromedpClientMockRecorder) NewContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewContext", reflect.TypeOf((*MockChromedpClient)(nil).NewContext), ctx)
}

// NewExecAllocator mocks base method.
func (m *MockChromedpClient) NewExecAllocator(ctx context.Context, opts []chromedp.ExecAllocatorOption) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewExecAllocator", ctx, opts)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// NewExecAllocator indicates an expected call of NewExecAllocator.
func (mr *MockChromedpClientMockRecorder) NewExecAllocator(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewExecAllocator", reflect.TypeOf((*MockChromedpClient)(nil).NewExecAllocator), ctx, opts)
}

// Run mocks base method.
func (m *MockChromedpClient) Run(ctx context.Context, actions ...chromedp.Action) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range actions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockChromedpClientMockRecorder) Run(ctx any, actions ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, actions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockChromedpClient)(nil).Run), varargs...)
}

// Sleep mocks base method.
func (m *MockChromedpClient) Sleep(duration time.Duration) chromedp.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sleep", duration)
	ret0, _ := ret[0].(chromedp.Action)
	return ret0
}

// Sleep indicates an expected call of Sleep.
func (mr *MockChromedpClientMockRecorder) Sleep(duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sleep", reflect.TypeOf((*MockChromedpClient)(nil).Sleep), duration)
}

// WaitReady mocks base method.
func (m *MockChromedpClient) WaitReady(sel string, waitReadyOpts ...chromedp.QueryOption) chromedp.QueryAction {
	m.ctrl.T.Helper()
	varargs := []any{sel}
	for _, a := range waitReadyOpts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WaitReady", varargs...)
	ret0, _ := ret[0].(chromedp.QueryAction)
	return ret0
}

// WaitReady indicates an expected call of WaitReady.
func (mr *MockChromedpClientMockRecorder) WaitReady(sel any, waitReadyOpts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{sel}, waitReadyOpts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitReady", reflect.TypeOf((*MockChromedpClient)(nil).WaitReady), varargs...)
}
