// Code generated by MockGen. DO NOT EDIT.
// Source: cloudflare.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cloudflare "github.com/cloudflare/cloudflare-go"
	gomock "github.com/golang/mock/gomock"
)

// MockCloudflareClient is a mock of CloudflareClient interface.
type MockCloudflareClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudflareClientMockRecorder
}

// MockCloudflareClientMockRecorder is the mock recorder for MockCloudflareClient.
type MockCloudflareClientMockRecorder struct {
	mock *MockCloudflareClient
}

// NewMockCloudflareClient creates a new mock instance.
func NewMockCloudflareClient(ctrl *gomock.Controller) *MockCloudflareClient {
	mock := &MockCloudflareClient{ctrl: ctrl}
	mock.recorder = &MockCloudflareClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudflareClient) EXPECT() *MockCloudflareClientMockRecorder {
	return m.recorder
}

// GetImage mocks base method.
func (m *MockCloudflareClient) GetImage(ctx context.Context, rc *cloudflare.ResourceContainer, id string) (cloudflare.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, rc, id)
	ret0, _ := ret[0].(cloudflare.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockCloudflareClientMockRecorder) GetImage(ctx, rc, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockCloudflareClient)(nil).GetImage), ctx, rc, id)
}

// GetVideo mocks base method.
func (m *MockCloudflareClient) GetVideo(ctx context.Context, params cloudflare.StreamParameters) (cloudflare.StreamVideo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideo", ctx, params)
	ret0, _ := ret[0].(cloudflare.StreamVideo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideo indicates an expected call of GetVideo.
func (mr *MockCloudflareClientMockRecorder) GetVideo(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideo", reflect.TypeOf((*MockCloudflareClient)(nil).GetVideo), ctx, params)
}

// UploadImage mocks base method.
func (m *MockCloudflareClient) UploadImage(ctx context.Context, rc *cloudflare.ResourceContainer, params cloudflare.UploadImageParams) (cloudflare.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, rc, params)
	ret0, _ := ret[0].(cloudflare.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockCloudflareClientMockRecorder) UploadImage(ctx, rc, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockCloudflareClient)(nil).UploadImage), ctx, rc, params)
}

// UploadVideoFromURL mocks base method.
func (m *MockCloudflareClient) UploadVideoFromURL(ctx context.Context, params cloudflare.StreamUploadFromURLParameters) (cloudflare.StreamVideo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadVideoFromURL", ctx, params)
	ret0, _ := ret[0].(cloudflare.StreamVideo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadVideoFromURL indicates an expected call of UploadVideoFromURL.
func (mr *MockCloudflareClientMockRecorder) UploadVideoFromURL(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadVideoFromURL", reflect.TypeOf((*MockCloudflareClient)(nil).UploadVideoFromURL), ctx, params)
}
