// Code generated by MockGen. DO NOT EDIT.
// Source: internal/uri/content_validator.go
//
// Generated by this command:
//
//	mockgen -source=internal/uri/content_validator.go -destination=internal/mocks/content_validator.go -package=mocks -mock_names=ContentValidator=MockContentValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	uri "github.com/feral-file/ff-indexer-v2/internal/uri"
)

// MockContentValidator is a mock of ContentValidator interface.
type MockContentValidator struct {
	ctrl     *gomock.Controller
	recorder *MockContentValidatorMockRecorder
	isgomock struct{}
}

// MockContentValidatorMockRecorder is the mock recorder for MockContentValidator.
type MockContentValidatorMockRecorder struct {
	mock *MockContentValidator
}

// NewMockContentValidator creates a new mock instance.
func NewMockContentValidator(ctrl *gomock.Controller) *MockContentValidator {
	mock := &MockContentValidator{ctrl: ctrl}
	mock.recorder = &MockContentValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentValidator) EXPECT() *MockContentValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockContentValidator) Validate(declaredContentType string, body []byte, totalLength int64) uri.ContentVerdict {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", declaredContentType, body, totalLength)
	ret0, _ := ret[0].(uri.ContentVerdict)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockContentValidatorMockRecorder) Validate(declaredContentType, body, totalLength any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockContentValidator)(nil).Validate), declaredContentType, body, totalLength)
}
