// Code generated by MockGen. DO NOT EDIT.
// Source: data_uri_checker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	uri "github.com/feral-file/ff-indexer-v2/internal/uri"
)

// MockDataURIChecker is a mock of DataURIChecker interface.
type MockDataURIChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDataURICheckerMockRecorder
}

// MockDataURICheckerMockRecorder is the mock recorder for MockDataURIChecker.
type MockDataURICheckerMockRecorder struct {
	mock *MockDataURIChecker
}

// NewMockDataURIChecker creates a new mock instance.
func NewMockDataURIChecker(ctrl *gomock.Controller) *MockDataURIChecker {
	mock := &MockDataURIChecker{ctrl: ctrl}
	mock.recorder = &MockDataURICheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataURIChecker) EXPECT() *MockDataURICheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockDataURIChecker) Check(dataURI string) uri.DataURICheckResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", dataURI)
	ret0, _ := ret[0].(uri.DataURICheckResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockDataURICheckerMockRecorder) Check(dataURI interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockDataURIChecker)(nil).Check), dataURI)
}
