// Code generated by MockGen. DO NOT EDIT.
// Source: encoding.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBase64 is a mock of Base64 interface.
type MockBase64 struct {
	ctrl     *gomock.Controller
	recorder *MockBase64MockRecorder
}

// MockBase64MockRecorder is the mock recorder for MockBase64.
type MockBase64MockRecorder struct {
	mock *MockBase64
}

// NewMockBase64 creates a new mock instance.
func NewMockBase64(ctrl *gomock.Controller) *MockBase64 {
	mock := &MockBase64{ctrl: ctrl}
	mock.recorder = &MockBase64MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBase64) EXPECT() *MockBase64MockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockBase64) Decode(data string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockBase64MockRecorder) Decode(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockBase64)(nil).Decode), data)
}

// Encode mocks base method.
func (m *MockBase64) Encode(data []byte) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", data)
	ret0, _ := ret[0].(string)
	return ret0
}

// Encode indicates an expected call of Encode.
func (mr *MockBase64MockRecorder) Encode(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockBase64)(nil).Encode), data)
}
