// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "github.com/golang/mock/gomock"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
)

// MockEthereumProviderClient is a mock of EthereumClient interface.
type MockEthereumProviderClient struct {
	ctrl     *gomock.Controller
	recorder *MockEthereumProviderClientMockRecorder
}

// MockEthereumProviderClientMockRecorder is the mock recorder for MockEthereumProviderClient.
type MockEthereumProviderClientMockRecorder struct {
	mock *MockEthereumProviderClient
}

// NewMockEthereumProviderClient creates a new mock instance.
func NewMockEthereumProviderClient(ctrl *gomock.Controller) *MockEthereumProviderClient {
	mock := &MockEthereumProviderClient{ctrl: ctrl}
	mock.recorder = &MockEthereumProviderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthereumProviderClient) EXPECT() *MockEthereumProviderClientMockRecorder {
	return m.recorder
}

// BlockByNumber mocks base method.
func (m *MockEthereumProviderClient) BlockByNumber(ctx context.Context, number *big.Int) (*types.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockByNumber", ctx, number)
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockByNumber indicates an expected call of BlockByNumber.
func (mr *MockEthereumProviderClientMockRecorder) BlockByNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockByNumber", reflect.TypeOf((*MockEthereumProviderClient)(nil).BlockByNumber), ctx, number)
}

// Close mocks base method.
func (m *MockEthereumProviderClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockEthereumProviderClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEthereumProviderClient)(nil).Close))
}

// ERC1155BalanceOf mocks base method.
func (m *MockEthereumProviderClient) ERC1155BalanceOf(ctx context.Context, contractAddress, ownerAddress, tokenNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ERC1155BalanceOf", ctx, contractAddress, ownerAddress, tokenNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ERC1155BalanceOf indicates an expected call of ERC1155BalanceOf.
func (mr *MockEthereumProviderClientMockRecorder) ERC1155BalanceOf(ctx, contractAddress, ownerAddress, tokenNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ERC1155BalanceOf", reflect.TypeOf((*MockEthereumProviderClient)(nil).ERC1155BalanceOf), ctx, contractAddress, ownerAddress, tokenNumber)
}

// ERC1155Balances mocks base method.
func (m *MockEthereumProviderClient) ERC1155Balances(ctx context.Context, contractAddress, tokenNumber string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ERC1155Balances", ctx, contractAddress, tokenNumber)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ERC1155Balances indicates an expected call of ERC1155Balances.
func (mr *MockEthereumProviderClientMockRecorder) ERC1155Balances(ctx, contractAddress, tokenNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ERC1155Balances", reflect.TypeOf((*MockEthereumProviderClient)(nil).ERC1155Balances), ctx, contractAddress, tokenNumber)
}

// ERC1155URI mocks base method.
func (m *MockEthereumProviderClient) ERC1155URI(ctx context.Context, contractAddress, tokenNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ERC1155URI", ctx, contractAddress, tokenNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ERC1155URI indicates an expected call of ERC1155URI.
func (mr *MockEthereumProviderClientMockRecorder) ERC1155URI(ctx, contractAddress, tokenNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ERC1155URI", reflect.TypeOf((*MockEthereumProviderClient)(nil).ERC1155URI), ctx, contractAddress, tokenNumber)
}

// ERC721OwnerOf mocks base method.
func (m *MockEthereumProviderClient) ERC721OwnerOf(ctx context.Context, contractAddress, tokenNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ERC721OwnerOf", ctx, contractAddress, tokenNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ERC721OwnerOf indicates an expected call of ERC721OwnerOf.
func (mr *MockEthereumProviderClientMockRecorder) ERC721OwnerOf(ctx, contractAddress, tokenNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ERC721OwnerOf", reflect.TypeOf((*MockEthereumProviderClient)(nil).ERC721OwnerOf), ctx, contractAddress, tokenNumber)
}

// ERC721TokenURI mocks base method.
func (m *MockEthereumProviderClient) ERC721TokenURI(ctx context.Context, contractAddress, tokenNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ERC721TokenURI", ctx, contractAddress, tokenNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ERC721TokenURI indicates an expected call of ERC721TokenURI.
func (mr *MockEthereumProviderClientMockRecorder) ERC721TokenURI(ctx, contractAddress, tokenNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ERC721TokenURI", reflect.TypeOf((*MockEthereumProviderClient)(nil).ERC721TokenURI), ctx, contractAddress, tokenNumber)
}

// GetContractDeployer mocks base method.
func (m *MockEthereumProviderClient) GetContractDeployer(ctx context.Context, contractAddress string, minBlock uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractDeployer", ctx, contractAddress, minBlock)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractDeployer indicates an expected call of GetContractDeployer.
func (mr *MockEthereumProviderClientMockRecorder) GetContractDeployer(ctx, contractAddress, minBlock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractDeployer", reflect.TypeOf((*MockEthereumProviderClient)(nil).GetContractDeployer), ctx, contractAddress, minBlock)
}

// GetLatestBlock mocks base method.
func (m *MockEthereumProviderClient) GetLatestBlock(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlock", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlock indicates an expected call of GetLatestBlock.
func (mr *MockEthereumProviderClientMockRecorder) GetLatestBlock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlock", reflect.TypeOf((*MockEthereumProviderClient)(nil).GetLatestBlock), ctx)
}

// GetTokenCIDsByOwnerAndBlockRange mocks base method.
func (m *MockEthereumProviderClient) GetTokenCIDsByOwnerAndBlockRange(ctx context.Context, ownerAddress string, fromBlock, toBlock uint64) ([]domain.TokenWithBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenCIDsByOwnerAndBlockRange", ctx, ownerAddress, fromBlock, toBlock)
	ret0, _ := ret[0].([]domain.TokenWithBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenCIDsByOwnerAndBlockRange indicates an expected call of GetTokenCIDsByOwnerAndBlockRange.
func (mr *MockEthereumProviderClientMockRecorder) GetTokenCIDsByOwnerAndBlockRange(ctx, ownerAddress, fromBlock, toBlock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenCIDsByOwnerAndBlockRange", reflect.TypeOf((*MockEthereumProviderClient)(nil).GetTokenCIDsByOwnerAndBlockRange), ctx, ownerAddress, fromBlock, toBlock)
}

// GetTokenEvents mocks base method.
func (m *MockEthereumProviderClient) GetTokenEvents(ctx context.Context, contractAddress, tokenNumber string, standard domain.ChainStandard) ([]domain.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenEvents", ctx, contractAddress, tokenNumber, standard)
	ret0, _ := ret[0].([]domain.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenEvents indicates an expected call of GetTokenEvents.
func (mr *MockEthereumProviderClientMockRecorder) GetTokenEvents(ctx, contractAddress, tokenNumber, standard interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenEvents", reflect.TypeOf((*MockEthereumProviderClient)(nil).GetTokenEvents), ctx, contractAddress, tokenNumber, standard)
}

// ParseEventLog mocks base method.
func (m *MockEthereumProviderClient) ParseEventLog(ctx context.Context, vLog types.Log) (*domain.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseEventLog", ctx, vLog)
	ret0, _ := ret[0].(*domain.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseEventLog indicates an expected call of ParseEventLog.
func (mr *MockEthereumProviderClientMockRecorder) ParseEventLog(ctx, vLog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseEventLog", reflect.TypeOf((*MockEthereumProviderClient)(nil).ParseEventLog), ctx, vLog)
}

// SubscribeFilterLogs mocks base method.
func (m *MockEthereumProviderClient) SubscribeFilterLogs(ctx context.Context, query ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeFilterLogs", ctx, query, ch)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeFilterLogs indicates an expected call of SubscribeFilterLogs.
func (mr *MockEthereumProviderClientMockRecorder) SubscribeFilterLogs(ctx, query, ch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeFilterLogs", reflect.TypeOf((*MockEthereumProviderClient)(nil).SubscribeFilterLogs), ctx, query, ch)
}

// TokenExists mocks base method.
func (m *MockEthereumProviderClient) TokenExists(ctx context.Context, contractAddress, tokenNumber string, standard domain.ChainStandard) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenExists", ctx, contractAddress, tokenNumber, standard)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenExists indicates an expected call of TokenExists.
func (mr *MockEthereumProviderClientMockRecorder) TokenExists(ctx, contractAddress, tokenNumber, standard interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenExists", reflect.TypeOf((*MockEthereumProviderClient)(nil).TokenExists), ctx, contractAddress, tokenNumber, standard)
}
