// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../../mocks/ethereum_provider_client.go -package=mocks -mock_names=EthereumClient=MockEthereumProviderClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
	adapters "github.com/feral-file/ff-indexer-v2/internal/providers/ethereum/adapters"
	registry "github.com/feral-file/ff-indexer-v2/internal/providers/ethereum/registry"
	registry0 "github.com/feral-file/ff-indexer-v2/internal/registry"
)

// MockEthereumProviderClient is a mock of EthereumClient interface.
type MockEthereumProviderClient struct {
	ctrl     *gomock.Controller
	recorder *MockEthereumProviderClientMockRecorder
	isgomock struct{}
}

// MockEthereumProviderClientMockRecorder is the mock recorder for MockEthereumProviderClient.
type MockEthereumProviderClientMockRecorder struct {
	mock *MockEthereumProviderClient
}

// NewMockEthereumProviderClient creates a new mock instance.
func NewMockEthereumProviderClient(ctrl *gomock.Controller) *MockEthereumProviderClient {
	mock := &MockEthereumProviderClient{ctrl: ctrl}
	mock.recorder = &MockEthereumProviderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthereumProviderClient) EXPECT() *MockEthereumProviderClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEthereumProviderClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockEthereumProviderClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEthereumProviderClient)(nil).Close))
}

// ContractAdapterRegistry mocks base method.
func (m *MockEthereumProviderClient) ContractAdapterRegistry() *registry.AdapterRegistry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContractAdapterRegistry")
	ret0, _ := ret[0].(*registry.AdapterRegistry)
	return ret0
}

// ContractAdapterRegistry indicates an expected call of ContractAdapterRegistry.
func (mr *MockEthereumProviderClientMockRecorder) ContractAdapterRegistry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContractAdapterRegistry", reflect.TypeOf((*MockEthereumProviderClient)(nil).ContractAdapterRegistry))
}

// GetContractDeployer mocks base method.
func (m *MockEthereumProviderClient) GetContractDeployer(ctx context.Context, contractAddress string, minBlock uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractDeployer", ctx, contractAddress, minBlock)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractDeployer indicates an expected call of GetContractDeployer.
func (mr *MockEthereumProviderClientMockRecorder) GetContractDeployer(ctx, contractAddress, minBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractDeployer", reflect.TypeOf((*MockEthereumProviderClient)(nil).GetContractDeployer), ctx, contractAddress, minBlock)
}

// GetLatestBlock mocks base method.
func (m *MockEthereumProviderClient) GetLatestBlock(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlock", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlock indicates an expected call of GetLatestBlock.
func (mr *MockEthereumProviderClientMockRecorder) GetLatestBlock(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlock", reflect.TypeOf((*MockEthereumProviderClient)(nil).GetLatestBlock), ctx)
}

// GetTokenCIDsByOwnerAndBlockRange mocks base method.
func (m *MockEthereumProviderClient) GetTokenCIDsByOwnerAndBlockRange(ctx context.Context, ownerAddress string, requestedFromBlock, requestedToBlock uint64, limit int, order domain.BlockScanOrder, blacklist registry0.BlacklistRegistry) (domain.TokenWithBlockRangeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenCIDsByOwnerAndBlockRange", ctx, ownerAddress, requestedFromBlock, requestedToBlock, limit, order, blacklist)
	ret0, _ := ret[0].(domain.TokenWithBlockRangeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenCIDsByOwnerAndBlockRange indicates an expected call of GetTokenCIDsByOwnerAndBlockRange.
func (mr *MockEthereumProviderClientMockRecorder) GetTokenCIDsByOwnerAndBlockRange(ctx, ownerAddress, requestedFromBlock, requestedToBlock, limit, order, blacklist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenCIDsByOwnerAndBlockRange", reflect.TypeOf((*MockEthereumProviderClient)(nil).GetTokenCIDsByOwnerAndBlockRange), ctx, ownerAddress, requestedFromBlock, requestedToBlock, limit, order, blacklist)
}

// GetTokenEvents mocks base method.
func (m *MockEthereumProviderClient) GetTokenEvents(ctx context.Context, contractAddress, tokenNumber string, standard domain.ChainStandard) ([]domain.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenEvents", ctx, contractAddress, tokenNumber, standard)
	ret0, _ := ret[0].([]domain.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenEvents indicates an expected call of GetTokenEvents.
func (mr *MockEthereumProviderClientMockRecorder) GetTokenEvents(ctx, contractAddress, tokenNumber, standard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenEvents", reflect.TypeOf((*MockEthereumProviderClient)(nil).GetTokenEvents), ctx, contractAddress, tokenNumber, standard)
}

// IsVendorOnlyMetadata mocks base method.
func (m *MockEthereumProviderClient) IsVendorOnlyMetadata(contractAddress string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVendorOnlyMetadata", contractAddress)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsVendorOnlyMetadata indicates an expected call of IsVendorOnlyMetadata.
func (mr *MockEthereumProviderClientMockRecorder) IsVendorOnlyMetadata(contractAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVendorOnlyMetadata", reflect.TypeOf((*MockEthereumProviderClient)(nil).IsVendorOnlyMetadata), contractAddress)
}

// OwnerBalanceAndEvents mocks base method.
func (m *MockEthereumProviderClient) OwnerBalanceAndEvents(ctx context.Context, contractAddress, tokenNumber, ownerAddress string, standard domain.ChainStandard) (string, []domain.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnerBalanceAndEvents", ctx, contractAddress, tokenNumber, ownerAddress, standard)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]domain.BlockchainEvent)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OwnerBalanceAndEvents indicates an expected call of OwnerBalanceAndEvents.
func (mr *MockEthereumProviderClientMockRecorder) OwnerBalanceAndEvents(ctx, contractAddress, tokenNumber, ownerAddress, standard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnerBalanceAndEvents", reflect.TypeOf((*MockEthereumProviderClient)(nil).OwnerBalanceAndEvents), ctx, contractAddress, tokenNumber, ownerAddress, standard)
}

// OwnershipModel mocks base method.
func (m *MockEthereumProviderClient) OwnershipModel(contractAddress string, standard domain.ChainStandard) (adapters.OwnershipModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnershipModel", contractAddress, standard)
	ret0, _ := ret[0].(adapters.OwnershipModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OwnershipModel indicates an expected call of OwnershipModel.
func (mr *MockEthereumProviderClientMockRecorder) OwnershipModel(contractAddress, standard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnershipModel", reflect.TypeOf((*MockEthereumProviderClient)(nil).OwnershipModel), contractAddress, standard)
}

// ParseEventLog mocks base method.
func (m *MockEthereumProviderClient) ParseEventLog(ctx context.Context, vLog types.Log) (*domain.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseEventLog", ctx, vLog)
	ret0, _ := ret[0].(*domain.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseEventLog indicates an expected call of ParseEventLog.
func (mr *MockEthereumProviderClientMockRecorder) ParseEventLog(ctx, vLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseEventLog", reflect.TypeOf((*MockEthereumProviderClient)(nil).ParseEventLog), ctx, vLog)
}

// SubscribeFilterLogs mocks base method.
func (m *MockEthereumProviderClient) SubscribeFilterLogs(ctx context.Context, query ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeFilterLogs", ctx, query, ch)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeFilterLogs indicates an expected call of SubscribeFilterLogs.
func (mr *MockEthereumProviderClientMockRecorder) SubscribeFilterLogs(ctx, query, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeFilterLogs", reflect.TypeOf((*MockEthereumProviderClient)(nil).SubscribeFilterLogs), ctx, query, ch)
}

// SupportsProvenance mocks base method.
func (m *MockEthereumProviderClient) SupportsProvenance(contractAddress string, standard domain.ChainStandard) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsProvenance", contractAddress, standard)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsProvenance indicates an expected call of SupportsProvenance.
func (mr *MockEthereumProviderClientMockRecorder) SupportsProvenance(contractAddress, standard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsProvenance", reflect.TypeOf((*MockEthereumProviderClient)(nil).SupportsProvenance), contractAddress, standard)
}

// TokenBalances mocks base method.
func (m *MockEthereumProviderClient) TokenBalances(ctx context.Context, contractAddress, tokenNumber string, standard domain.ChainStandard) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenBalances", ctx, contractAddress, tokenNumber, standard)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenBalances indicates an expected call of TokenBalances.
func (mr *MockEthereumProviderClientMockRecorder) TokenBalances(ctx, contractAddress, tokenNumber, standard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenBalances", reflect.TypeOf((*MockEthereumProviderClient)(nil).TokenBalances), ctx, contractAddress, tokenNumber, standard)
}

// TokenExists mocks base method.
func (m *MockEthereumProviderClient) TokenExists(ctx context.Context, contractAddress, tokenNumber string, standard domain.ChainStandard) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenExists", ctx, contractAddress, tokenNumber, standard)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenExists indicates an expected call of TokenExists.
func (mr *MockEthereumProviderClientMockRecorder) TokenExists(ctx, contractAddress, tokenNumber, standard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenExists", reflect.TypeOf((*MockEthereumProviderClient)(nil).TokenExists), ctx, contractAddress, tokenNumber, standard)
}

// TokenOwner mocks base method.
func (m *MockEthereumProviderClient) TokenOwner(ctx context.Context, contractAddress, tokenNumber string, standard domain.ChainStandard) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenOwner", ctx, contractAddress, tokenNumber, standard)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenOwner indicates an expected call of TokenOwner.
func (mr *MockEthereumProviderClientMockRecorder) TokenOwner(ctx, contractAddress, tokenNumber, standard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenOwner", reflect.TypeOf((*MockEthereumProviderClient)(nil).TokenOwner), ctx, contractAddress, tokenNumber, standard)
}

// TokenURI mocks base method.
func (m *MockEthereumProviderClient) TokenURI(ctx context.Context, contractAddress, tokenNumber string, standard domain.ChainStandard) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenURI", ctx, contractAddress, tokenNumber, standard)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenURI indicates an expected call of TokenURI.
func (mr *MockEthereumProviderClientMockRecorder) TokenURI(ctx, contractAddress, tokenNumber, standard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenURI", reflect.TypeOf((*MockEthereumProviderClient)(nil).TokenURI), ctx, contractAddress, tokenNumber, standard)
}
