// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../../../mocks/feralfile_client.go -package=mocks -mock_names=Client=MockFeralFileClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	feralfile "github.com/feral-file/ff-indexer-v2/internal/providers/vendors/feralfile"
	gomock "go.uber.org/mock/gomock"
)

// MockFeralFileClient is a mock of Client interface.
type MockFeralFileClient struct {
	ctrl     *gomock.Controller
	recorder *MockFeralFileClientMockRecorder
	isgomock struct{}
}

// MockFeralFileClientMockRecorder is the mock recorder for MockFeralFileClient.
type MockFeralFileClientMockRecorder struct {
	mock *MockFeralFileClient
}

// NewMockFeralFileClient creates a new mock instance.
func NewMockFeralFileClient(ctrl *gomock.Controller) *MockFeralFileClient {
	mock := &MockFeralFileClient{ctrl: ctrl}
	mock.recorder = &MockFeralFileClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeralFileClient) EXPECT() *MockFeralFileClientMockRecorder {
	return m.recorder
}

// GetArtwork mocks base method.
func (m *MockFeralFileClient) GetArtwork(ctx context.Context, tokenID string) (*feralfile.Artwork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtwork", ctx, tokenID)
	ret0, _ := ret[0].(*feralfile.Artwork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtwork indicates an expected call of GetArtwork.
func (mr *MockFeralFileClientMockRecorder) GetArtwork(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtwork", reflect.TypeOf((*MockFeralFileClient)(nil).GetArtwork), ctx, tokenID)
}

// GetSeriesArtworks mocks base method.
func (m *MockFeralFileClient) GetSeriesArtworks(ctx context.Context, seriesID string, mintFrom, mintTo int64) ([]feralfile.ArtworkRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeriesArtworks", ctx, seriesID, mintFrom, mintTo)
	ret0, _ := ret[0].([]feralfile.ArtworkRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeriesArtworks indicates an expected call of GetSeriesArtworks.
func (mr *MockFeralFileClientMockRecorder) GetSeriesArtworks(ctx, seriesID, mintFrom, mintTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeriesArtworks", reflect.TypeOf((*MockFeralFileClient)(nil).GetSeriesArtworks), ctx, seriesID, mintFrom, mintTo)
}
