// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../../../mocks/fxhash_client.go -package=mocks -mock_names=Client=MockFxhashClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	fxhash "github.com/feral-file/ff-indexer-v2/internal/providers/vendors/fxhash"
	gomock "go.uber.org/mock/gomock"
)

// MockFxhashClient is a mock of Client interface.
type MockFxhashClient struct {
	ctrl     *gomock.Controller
	recorder *MockFxhashClientMockRecorder
	isgomock struct{}
}

// MockFxhashClientMockRecorder is the mock recorder for MockFxhashClient.
type MockFxhashClientMockRecorder struct {
	mock *MockFxhashClient
}

// NewMockFxhashClient creates a new mock instance.
func NewMockFxhashClient(ctrl *gomock.Controller) *MockFxhashClient {
	mock := &MockFxhashClient{ctrl: ctrl}
	mock.recorder = &MockFxhashClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFxhashClient) EXPECT() *MockFxhashClientMockRecorder {
	return m.recorder
}

// GetGentk mocks base method.
func (m *MockFxhashClient) GetGentk(ctx context.Context, contractAddress, tokenID string) (*fxhash.Gentk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGentk", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].(*fxhash.Gentk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGentk indicates an expected call of GetGentk.
func (mr *MockFxhashClientMockRecorder) GetGentk(ctx, contractAddress, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGentk", reflect.TypeOf((*MockFxhashClient)(nil).GetGentk), ctx, contractAddress, tokenID)
}

// GetGentksByIteration mocks base method.
func (m *MockFxhashClient) GetGentksByIteration(ctx context.Context, generativeTokenID string, iterationFrom, iterationTo int64) ([]fxhash.GentkRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGentksByIteration", ctx, generativeTokenID, iterationFrom, iterationTo)
	ret0, _ := ret[0].([]fxhash.GentkRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGentksByIteration indicates an expected call of GetGentksByIteration.
func (mr *MockFxhashClientMockRecorder) GetGentksByIteration(ctx, generativeTokenID, iterationFrom, iterationTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGentksByIteration", reflect.TypeOf((*MockFxhashClient)(nil).GetGentksByIteration), ctx, generativeTokenID, iterationFrom, iterationTo)
}
