// Code generated by MockGen. DO NOT EDIT.
// Source: http.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// GetAndUnmarshal mocks base method.
func (m *MockHTTPClient) GetAndUnmarshal(ctx context.Context, url string, result interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndUnmarshal", ctx, url, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAndUnmarshal indicates an expected call of GetAndUnmarshal.
func (mr *MockHTTPClientMockRecorder) GetAndUnmarshal(ctx, url, result interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndUnmarshal", reflect.TypeOf((*MockHTTPClient)(nil).GetAndUnmarshal), ctx, url, result)
}

// GetBytes mocks base method.
func (m *MockHTTPClient) GetBytes(ctx context.Context, url string, headers map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBytes", ctx, url, headers)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBytes indicates an expected call of GetBytes.
func (mr *MockHTTPClientMockRecorder) GetBytes(ctx, url, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBytes", reflect.TypeOf((*MockHTTPClient)(nil).GetBytes), ctx, url, headers)
}

// GetPartialBytes mocks base method.
func (m *MockHTTPClient) GetPartialBytes(ctx context.Context, url string, maxBytes int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPartialBytes", ctx, url, maxBytes)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPartialBytes indicates an expected call of GetPartialBytes.
func (mr *MockHTTPClientMockRecorder) GetPartialBytes(ctx, url, maxBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPartialBytes", reflect.TypeOf((*MockHTTPClient)(nil).GetPartialBytes), ctx, url, maxBytes)
}

// GetPartialBytesNoRetry mocks base method.
func (m *MockHTTPClient) GetPartialBytesNoRetry(ctx context.Context, url string, maxBytes int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPartialBytesNoRetry", ctx, url, maxBytes)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPartialBytesNoRetry indicates an expected call of GetPartialBytesNoRetry.
func (mr *MockHTTPClientMockRecorder) GetPartialBytesNoRetry(ctx, url, maxBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPartialBytesNoRetry", reflect.TypeOf((*MockHTTPClient)(nil).GetPartialBytesNoRetry), ctx, url, maxBytes)
}

// GetResponse mocks base method.
func (m *MockHTTPClient) GetResponse(ctx context.Context, url string, headers map[string]string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponse", ctx, url, headers)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponse indicates an expected call of GetResponse.
func (mr *MockHTTPClientMockRecorder) GetResponse(ctx, url, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponse", reflect.TypeOf((*MockHTTPClient)(nil).GetResponse), ctx, url, headers)
}

// GetResponseNoRetry mocks base method.
func (m *MockHTTPClient) GetResponseNoRetry(ctx context.Context, url string, headers map[string]string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponseNoRetry", ctx, url, headers)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponseNoRetry indicates an expected call of GetResponseNoRetry.
func (mr *MockHTTPClientMockRecorder) GetResponseNoRetry(ctx, url, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseNoRetry", reflect.TypeOf((*MockHTTPClient)(nil).GetResponseNoRetry), ctx, url, headers)
}

// Head mocks base method.
func (m *MockHTTPClient) Head(ctx context.Context, url string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head", ctx, url)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head.
func (mr *MockHTTPClientMockRecorder) Head(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockHTTPClient)(nil).Head), ctx, url)
}

// HeadNoRetry mocks base method.
func (m *MockHTTPClient) HeadNoRetry(ctx context.Context, url string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadNoRetry", ctx, url)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadNoRetry indicates an expected call of HeadNoRetry.
func (mr *MockHTTPClientMockRecorder) HeadNoRetry(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadNoRetry", reflect.TypeOf((*MockHTTPClient)(nil).HeadNoRetry), ctx, url)
}

// PostBytes mocks base method.
func (m *MockHTTPClient) PostBytes(ctx context.Context, url string, headers map[string]string, body io.Reader) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostBytes", ctx, url, headers, body)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostBytes indicates an expected call of PostBytes.
func (mr *MockHTTPClientMockRecorder) PostBytes(ctx, url, headers, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostBytes", reflect.TypeOf((*MockHTTPClient)(nil).PostBytes), ctx, url, headers, body)
}

// PostNoRetry mocks base method.
func (m *MockHTTPClient) PostNoRetry(ctx context.Context, url string, headers map[string]string, body io.Reader) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostNoRetry", ctx, url, headers, body)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostNoRetry indicates an expected call of PostNoRetry.
func (mr *MockHTTPClientMockRecorder) PostNoRetry(ctx, url, headers, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostNoRetry", reflect.TypeOf((*MockHTTPClient)(nil).PostNoRetry), ctx, url, headers, body)
}
