// Code generated by MockGen. DO NOT EDIT.
// Source: image.go

// Package mocks is a generated GoMock package.
package mocks

import (
	image "image"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockImageEncoder is a mock of ImageEncoder interface.
type MockImageEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockImageEncoderMockRecorder
}

// MockImageEncoderMockRecorder is the mock recorder for MockImageEncoder.
type MockImageEncoderMockRecorder struct {
	mock *MockImageEncoder
}

// NewMockImageEncoder creates a new mock instance.
func NewMockImageEncoder(ctrl *gomock.Controller) *MockImageEncoder {
	mock := &MockImageEncoder{ctrl: ctrl}
	mock.recorder = &MockImageEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageEncoder) EXPECT() *MockImageEncoderMockRecorder {
	return m.recorder
}

// EncodeJPEG mocks base method.
func (m *MockImageEncoder) EncodeJPEG(w io.Writer, img image.Image, quality int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeJPEG", w, img, quality)
	ret0, _ := ret[0].(error)
	return ret0
}

// EncodeJPEG indicates an expected call of EncodeJPEG.
func (mr *MockImageEncoderMockRecorder) EncodeJPEG(w, img, quality interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeJPEG", reflect.TypeOf((*MockImageEncoder)(nil).EncodeJPEG), w, img, quality)
}

// EncodePNG mocks base method.
func (m *MockImageEncoder) EncodePNG(w io.Writer, img image.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodePNG", w, img)
	ret0, _ := ret[0].(error)
	return ret0
}

// EncodePNG indicates an expected call of EncodePNG.
func (mr *MockImageEncoderMockRecorder) EncodePNG(w, img interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodePNG", reflect.TypeOf((*MockImageEncoder)(nil).EncodePNG), w, img)
}
