// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=../mocks/ingestion_runner.go -package=mocks -mock_names=Runner=MockIngestionRunner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIngestionRunner is a mock of Runner interface.
type MockIngestionRunner struct {
	ctrl     *gomock.Controller
	recorder *MockIngestionRunnerMockRecorder
	isgomock struct{}
}

// MockIngestionRunnerMockRecorder is the mock recorder for MockIngestionRunner.
type MockIngestionRunnerMockRecorder struct {
	mock *MockIngestionRunner
}

// NewMockIngestionRunner creates a new mock instance.
func NewMockIngestionRunner(ctrl *gomock.Controller) *MockIngestionRunner {
	mock := &MockIngestionRunner{ctrl: ctrl}
	mock.recorder = &MockIngestionRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestionRunner) EXPECT() *MockIngestionRunnerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIngestionRunner) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIngestionRunnerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIngestionRunner)(nil).Close))
}

// Run mocks base method.
func (m *MockIngestionRunner) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockIngestionRunnerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIngestionRunner)(nil).Run), ctx)
}
