// Code generated by MockGen. DO NOT EDIT.
// Source: message.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
)

// MockJetStreamMessage is a mock of Message interface.
type MockJetStreamMessage struct {
	ctrl     *gomock.Controller
	recorder *MockJetStreamMessageMockRecorder
}

// MockJetStreamMessageMockRecorder is the mock recorder for MockJetStreamMessage.
type MockJetStreamMessageMockRecorder struct {
	mock *MockJetStreamMessage
}

// NewMockJetStreamMessage creates a new mock instance.
func NewMockJetStreamMessage(ctrl *gomock.Controller) *MockJetStreamMessage {
	mock := &MockJetStreamMessage{ctrl: ctrl}
	mock.recorder = &MockJetStreamMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJetStreamMessage) EXPECT() *MockJetStreamMessageMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockJetStreamMessage) Ack() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockJetStreamMessageMockRecorder) Ack() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockJetStreamMessage)(nil).Ack))
}

// Data mocks base method.
func (m *MockJetStreamMessage) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockJetStreamMessageMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockJetStreamMessage)(nil).Data))
}

// Metadata mocks base method.
func (m *MockJetStreamMessage) Metadata() (*jetstream.MsgMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(*jetstream.MsgMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockJetStreamMessageMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockJetStreamMessage)(nil).Metadata))
}

// Nak mocks base method.
func (m *MockJetStreamMessage) Nak() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nak")
	ret0, _ := ret[0].(error)
	return ret0
}

// Nak indicates an expected call of Nak.
func (mr *MockJetStreamMessageMockRecorder) Nak() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nak", reflect.TypeOf((*MockJetStreamMessage)(nil).Nak))
}

// Term mocks base method.
func (m *MockJetStreamMessage) Term() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Term")
	ret0, _ := ret[0].(error)
	return ret0
}

// Term indicates an expected call of Term.
func (mr *MockJetStreamMessageMockRecorder) Term() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Term", reflect.TypeOf((*MockJetStreamMessage)(nil).Term))
}
