// Code generated by MockGen. DO NOT EDIT.
// Source: jsc.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJCS is a mock of JCS interface.
type MockJCS struct {
	ctrl     *gomock.Controller
	recorder *MockJCSMockRecorder
}

// MockJCSMockRecorder is the mock recorder for MockJCS.
type MockJCSMockRecorder struct {
	mock *MockJCS
}

// NewMockJCS creates a new mock instance.
func NewMockJCS(ctrl *gomock.Controller) *MockJCS {
	mock := &MockJCS{ctrl: ctrl}
	mock.recorder = &MockJCSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJCS) EXPECT() *MockJCSMockRecorder {
	return m.recorder
}

// Transform mocks base method.
func (m *MockJCS) Transform(data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transform", data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transform indicates an expected call of Transform.
func (mr *MockJCSMockRecorder) Transform(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transform", reflect.TypeOf((*MockJCS)(nil).Transform), data)
}
