// Code generated by MockGen. DO NOT EDIT.
// Source: media_workflow.go
//
// Generated by this command:
//
//	mockgen -source=media_workflow.go -destination=../mocks/media_workflows.go -package=mocks -mock_names=MediaWorkflows=MockMediaWorkflows
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMediaWorkflows is a mock of MediaWorkflows interface.
type MockMediaWorkflows struct {
	ctrl     *gomock.Controller
	recorder *MockMediaWorkflowsMockRecorder
	isgomock struct{}
}

// MockMediaWorkflowsMockRecorder is the mock recorder for MockMediaWorkflows.
type MockMediaWorkflowsMockRecorder struct {
	mock *MockMediaWorkflows
}

// NewMockMediaWorkflows creates a new mock instance.
func NewMockMediaWorkflows(ctrl *gomock.Controller) *MockMediaWorkflows {
	mock := &MockMediaWorkflows{ctrl: ctrl}
	mock.recorder = &MockMediaWorkflowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaWorkflows) EXPECT() *MockMediaWorkflowsMockRecorder {
	return m.recorder
}

// IndexMediaWorkflow mocks base method.
func (m *MockMediaWorkflows) IndexMediaWorkflow(ctx context.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMediaWorkflow", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMediaWorkflow indicates an expected call of IndexMediaWorkflow.
func (mr *MockMediaWorkflowsMockRecorder) IndexMediaWorkflow(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMediaWorkflow", reflect.TypeOf((*MockMediaWorkflows)(nil).IndexMediaWorkflow), ctx, url)
}

// IndexMultipleMediaWorkflow mocks base method.
func (m *MockMediaWorkflows) IndexMultipleMediaWorkflow(ctx context.Context, urls []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMultipleMediaWorkflow", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMultipleMediaWorkflow indicates an expected call of IndexMultipleMediaWorkflow.
func (mr *MockMediaWorkflowsMockRecorder) IndexMultipleMediaWorkflow(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMultipleMediaWorkflow", reflect.TypeOf((*MockMediaWorkflows)(nil).IndexMultipleMediaWorkflow), ctx, urls)
}
