// Code generated by MockGen. DO NOT EDIT.
// Source: media_executor.go
//
// Generated by this command:
//
//	mockgen -source=media_executor.go -destination=../mocks/media_executor.go -package=mocks -mock_names=MediaExecutor=MockMediaExecutor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMediaExecutor is a mock of MediaExecutor interface.
type MockMediaExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockMediaExecutorMockRecorder
	isgomock struct{}
}

// MockMediaExecutorMockRecorder is the mock recorder for MockMediaExecutor.
type MockMediaExecutorMockRecorder struct {
	mock *MockMediaExecutor
}

// NewMockMediaExecutor creates a new mock instance.
func NewMockMediaExecutor(ctrl *gomock.Controller) *MockMediaExecutor {
	mock := &MockMediaExecutor{ctrl: ctrl}
	mock.recorder = &MockMediaExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaExecutor) EXPECT() *MockMediaExecutorMockRecorder {
	return m.recorder
}

// IndexMediaFile mocks base method.
func (m *MockMediaExecutor) IndexMediaFile(ctx context.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMediaFile", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMediaFile indicates an expected call of IndexMediaFile.
func (mr *MockMediaExecutorMockRecorder) IndexMediaFile(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMediaFile", reflect.TypeOf((*MockMediaExecutor)(nil).IndexMediaFile), ctx, url)
}
