// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMediaProcessor is a mock of Processor interface.
type MockMediaProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockMediaProcessorMockRecorder
}

// MockMediaProcessorMockRecorder is the mock recorder for MockMediaProcessor.
type MockMediaProcessorMockRecorder struct {
	mock *MockMediaProcessor
}

// NewMockMediaProcessor creates a new mock instance.
func NewMockMediaProcessor(ctrl *gomock.Controller) *MockMediaProcessor {
	mock := &MockMediaProcessor{ctrl: ctrl}
	mock.recorder = &MockMediaProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaProcessor) EXPECT() *MockMediaProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockMediaProcessor) Process(ctx context.Context, sourceURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, sourceURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockMediaProcessorMockRecorder) Process(ctx, sourceURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockMediaProcessor)(nil).Process), ctx, sourceURL)
}

// Provider mocks base method.
func (m *MockMediaProcessor) Provider() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provider")
	ret0, _ := ret[0].(string)
	return ret0
}

// Provider indicates an expected call of Provider.
func (mr *MockMediaProcessorMockRecorder) Provider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provider", reflect.TypeOf((*MockMediaProcessor)(nil).Provider))
}
