// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	mediaprovider "github.com/feral-file/ff-indexer-v2/internal/media/provider"
)

// MockMediaProvider is a mock of Provider interface.
type MockMediaProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMediaProviderMockRecorder
}

// MockMediaProviderMockRecorder is the mock recorder for MockMediaProvider.
type MockMediaProviderMockRecorder struct {
	mock *MockMediaProvider
}

// NewMockMediaProvider creates a new mock instance.
func NewMockMediaProvider(ctrl *gomock.Controller) *MockMediaProvider {
	mock := &MockMediaProvider{ctrl: ctrl}
	mock.recorder = &MockMediaProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaProvider) EXPECT() *MockMediaProviderMockRecorder {
	return m.recorder
}

// UploadImageFromURL mocks base method.
func (m *MockMediaProvider) UploadImageFromURL(ctx context.Context, sourceURL string, metadata map[string]interface{}) (*mediaprovider.UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImageFromURL", ctx, sourceURL, metadata)
	ret0, _ := ret[0].(*mediaprovider.UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImageFromURL indicates an expected call of UploadImageFromURL.
func (mr *MockMediaProviderMockRecorder) UploadImageFromURL(ctx, sourceURL, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImageFromURL", reflect.TypeOf((*MockMediaProvider)(nil).UploadImageFromURL), ctx, sourceURL, metadata)
}

// UploadImageFromReader mocks base method.
func (m *MockMediaProvider) UploadImageFromReader(ctx context.Context, reader io.Reader, filename, contentType string, metadata map[string]interface{}) (*mediaprovider.UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImageFromReader", ctx, reader, filename, contentType, metadata)
	ret0, _ := ret[0].(*mediaprovider.UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImageFromReader indicates an expected call of UploadImageFromReader.
func (mr *MockMediaProviderMockRecorder) UploadImageFromReader(ctx, reader, filename, contentType, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImageFromReader", reflect.TypeOf((*MockMediaProvider)(nil).UploadImageFromReader), ctx, reader, filename, contentType, metadata)
}

// UploadVideo mocks base method.
func (m *MockMediaProvider) UploadVideo(ctx context.Context, sourceURL string, metadata map[string]interface{}) (*mediaprovider.UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadVideo", ctx, sourceURL, metadata)
	ret0, _ := ret[0].(*mediaprovider.UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadVideo indicates an expected call of UploadVideo.
func (mr *MockMediaProviderMockRecorder) UploadVideo(ctx, sourceURL, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadVideo", reflect.TypeOf((*MockMediaProvider)(nil).UploadVideo), ctx, sourceURL, metadata)
}

// Name mocks base method.
func (m *MockMediaProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMediaProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMediaProvider)(nil).Name))
}
