// Code generated by MockGen. DO NOT EDIT.
// Source: resolver.go
//
// Generated by this command:
//
//	mockgen -source=resolver.go -destination=../mocks/metadata_resolver.go -package=mocks -mock_names=Resolver=MockMetadataResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
	metadata "github.com/feral-file/ff-indexer-v2/internal/metadata"
)

// MockMetadataResolver is a mock of Resolver interface.
type MockMetadataResolver struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataResolverMockRecorder
	isgomock struct{}
}

// MockMetadataResolverMockRecorder is the mock recorder for MockMetadataResolver.
type MockMetadataResolverMockRecorder struct {
	mock *MockMetadataResolver
}

// NewMockMetadataResolver creates a new mock instance.
func NewMockMetadataResolver(ctrl *gomock.Controller) *MockMetadataResolver {
	mock := &MockMetadataResolver{ctrl: ctrl}
	mock.recorder = &MockMetadataResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataResolver) EXPECT() *MockMetadataResolverMockRecorder {
	return m.recorder
}

// LoadDeployerCacheFromDB mocks base method.
func (m *MockMetadataResolver) LoadDeployerCacheFromDB(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDeployerCacheFromDB", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadDeployerCacheFromDB indicates an expected call of LoadDeployerCacheFromDB.
func (mr *MockMetadataResolverMockRecorder) LoadDeployerCacheFromDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDeployerCacheFromDB", reflect.TypeOf((*MockMetadataResolver)(nil).LoadDeployerCacheFromDB), ctx)
}

// RawHash mocks base method.
func (m *MockMetadataResolver) RawHash(arg0 *metadata.NormalizedMetadata) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawHash", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RawHash indicates an expected call of RawHash.
func (mr *MockMetadataResolverMockRecorder) RawHash(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawHash", reflect.TypeOf((*MockMetadataResolver)(nil).RawHash), arg0)
}

// Resolve mocks base method.
func (m *MockMetadataResolver) Resolve(ctx context.Context, tokenCID domain.TokenCID) (*metadata.NormalizedMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, tokenCID)
	ret0, _ := ret[0].(*metadata.NormalizedMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockMetadataResolverMockRecorder) Resolve(ctx, tokenCID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockMetadataResolver)(nil).Resolve), ctx, tokenCID)
}
