// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockAPIHandler is a mock of Handler interface.
type MockAPIHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAPIHandlerMockRecorder
}

// MockAPIHandlerMockRecorder is the mock recorder for MockAPIHandler.
type MockAPIHandlerMockRecorder struct {
	mock *MockAPIHandler
}

// NewMockAPIHandler creates a new mock instance.
func NewMockAPIHandler(ctrl *gomock.Controller) *MockAPIHandler {
	mock := &MockAPIHandler{ctrl: ctrl}
	mock.recorder = &MockAPIHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIHandler) EXPECT() *MockAPIHandlerMockRecorder {
	return m.recorder
}

// GetChanges mocks base method.
func (m *MockAPIHandler) GetChanges(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetChanges", c)
}

// GetChanges indicates an expected call of GetChanges.
func (mr *MockAPIHandlerMockRecorder) GetChanges(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChanges", reflect.TypeOf((*MockAPIHandler)(nil).GetChanges), c)
}

// GetToken mocks base method.
func (m *MockAPIHandler) GetToken(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetToken", c)
}

// GetToken indicates an expected call of GetToken.
func (mr *MockAPIHandlerMockRecorder) GetToken(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockAPIHandler)(nil).GetToken), c)
}

// GetWorkflowStatus mocks base method.
func (m *MockAPIHandler) GetWorkflowStatus(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetWorkflowStatus", c)
}

// GetWorkflowStatus indicates an expected call of GetWorkflowStatus.
func (mr *MockAPIHandlerMockRecorder) GetWorkflowStatus(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowStatus", reflect.TypeOf((*MockAPIHandler)(nil).GetWorkflowStatus), c)
}

// HealthCheck mocks base method.
func (m *MockAPIHandler) HealthCheck(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HealthCheck", c)
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockAPIHandlerMockRecorder) HealthCheck(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockAPIHandler)(nil).HealthCheck), c)
}

// ListTokens mocks base method.
func (m *MockAPIHandler) ListTokens(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListTokens", c)
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockAPIHandlerMockRecorder) ListTokens(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockAPIHandler)(nil).ListTokens), c)
}

// TriggerTokenIndexing mocks base method.
func (m *MockAPIHandler) TriggerTokenIndexing(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerTokenIndexing", c)
}

// TriggerTokenIndexing indicates an expected call of TriggerTokenIndexing.
func (mr *MockAPIHandlerMockRecorder) TriggerTokenIndexing(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerTokenIndexing", reflect.TypeOf((*MockAPIHandler)(nil).TriggerTokenIndexing), c)
}
