// Code generated by MockGen. DO NOT EDIT.
// Source: nats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	adapter "github.com/feral-file/ff-indexer-v2/internal/adapter"
	gomock "github.com/golang/mock/gomock"
	nats "github.com/nats-io/nats.go"
	jetstream "github.com/nats-io/nats.go/jetstream"
)

// MockNatsConn is a mock of NatsConn interface.
type MockNatsConn struct {
	ctrl     *gomock.Controller
	recorder *MockNatsConnMockRecorder
}

// MockNatsConnMockRecorder is the mock recorder for MockNatsConn.
type MockNatsConnMockRecorder struct {
	mock *MockNatsConn
}

// NewMockNatsConn creates a new mock instance.
func NewMockNatsConn(ctrl *gomock.Controller) *MockNatsConn {
	mock := &MockNatsConn{ctrl: ctrl}
	mock.recorder = &MockNatsConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsConn) EXPECT() *MockNatsConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockNatsConn) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockNatsConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNatsConn)(nil).Close))
}

// ConnectedUrl mocks base method.
func (m *MockNatsConn) ConnectedUrl() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectedUrl")
	ret0, _ := ret[0].(string)
	return ret0
}

// ConnectedUrl indicates an expected call of ConnectedUrl.
func (mr *MockNatsConnMockRecorder) ConnectedUrl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectedUrl", reflect.TypeOf((*MockNatsConn)(nil).ConnectedUrl))
}

// LastError mocks base method.
func (m *MockNatsConn) LastError() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastError")
	ret0, _ := ret[0].(error)
	return ret0
}

// LastError indicates an expected call of LastError.
func (mr *MockNatsConnMockRecorder) LastError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastError", reflect.TypeOf((*MockNatsConn)(nil).LastError))
}

// MockJetStream is a mock of JetStream interface.
type MockJetStream struct {
	ctrl     *gomock.Controller
	recorder *MockJetStreamMockRecorder
}

// MockJetStreamMockRecorder is the mock recorder for MockJetStream.
type MockJetStreamMockRecorder struct {
	mock *MockJetStream
}

// NewMockJetStream creates a new mock instance.
func NewMockJetStream(ctrl *gomock.Controller) *MockJetStream {
	mock := &MockJetStream{ctrl: ctrl}
	mock.recorder = &MockJetStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJetStream) EXPECT() *MockJetStreamMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockJetStream) Publish(ctx context.Context, subject string, data []byte, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, subject, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(*jetstream.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockJetStreamMockRecorder) Publish(ctx, subject, data interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, subject, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockJetStream)(nil).Publish), varargs...)
}

// MockNatsJetStream is a mock of NatsJetStream interface.
type MockNatsJetStream struct {
	ctrl     *gomock.Controller
	recorder *MockNatsJetStreamMockRecorder
}

// MockNatsJetStreamMockRecorder is the mock recorder for MockNatsJetStream.
type MockNatsJetStreamMockRecorder struct {
	mock *MockNatsJetStream
}

// NewMockNatsJetStream creates a new mock instance.
func NewMockNatsJetStream(ctrl *gomock.Controller) *MockNatsJetStream {
	mock := &MockNatsJetStream{ctrl: ctrl}
	mock.recorder = &MockNatsJetStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsJetStream) EXPECT() *MockNatsJetStreamMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockNatsJetStream) Connect(url string, options ...nats.Option) (adapter.NatsConn, adapter.JetStream, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{url}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Connect", varargs...)
	ret0, _ := ret[0].(adapter.NatsConn)
	ret1, _ := ret[1].(adapter.JetStream)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Connect indicates an expected call of Connect.
func (mr *MockNatsJetStreamMockRecorder) Connect(url interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{url}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockNatsJetStream)(nil).Connect), varargs...)
}
