// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	objkt "github.com/feral-file/ff-indexer-v2/internal/providers/vendors/objkt"
	gomock "github.com/golang/mock/gomock"
)

// MockObjktClient is a mock of Client interface.
type MockObjktClient struct {
	ctrl     *gomock.Controller
	recorder *MockObjktClientMockRecorder
}

// MockObjktClientMockRecorder is the mock recorder for MockObjktClient.
type MockObjktClientMockRecorder struct {
	mock *MockObjktClient
}

// NewMockObjktClient creates a new mock instance.
func NewMockObjktClient(ctrl *gomock.Controller) *MockObjktClient {
	mock := &MockObjktClient{ctrl: ctrl}
	mock.recorder = &MockObjktClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjktClient) EXPECT() *MockObjktClientMockRecorder {
	return m.recorder
}

// GetToken mocks base method.
func (m *MockObjktClient) GetToken(ctx context.Context, contractAddress, tokenID string) (*objkt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].(*objkt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockObjktClientMockRecorder) GetToken(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockObjktClient)(nil).GetToken), ctx, contractAddress, tokenID)
}
