// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	opensea "github.com/feral-file/ff-indexer-v2/internal/providers/vendors/opensea"
)

// MockOpenSeaClient is a mock of Client interface.
type MockOpenSeaClient struct {
	ctrl     *gomock.Controller
	recorder *MockOpenSeaClientMockRecorder
}

// MockOpenSeaClientMockRecorder is the mock recorder for MockOpenSeaClient.
type MockOpenSeaClientMockRecorder struct {
	mock *MockOpenSeaClient
}

// NewMockOpenSeaClient creates a new mock instance.
func NewMockOpenSeaClient(ctrl *gomock.Controller) *MockOpenSeaClient {
	mock := &MockOpenSeaClient{ctrl: ctrl}
	mock.recorder = &MockOpenSeaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenSeaClient) EXPECT() *MockOpenSeaClientMockRecorder {
	return m.recorder
}

// GetNFT mocks base method.
func (m *MockOpenSeaClient) GetNFT(ctx context.Context, contractAddress, tokenID string) (*opensea.NFTMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNFT", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].(*opensea.NFTMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNFT indicates an expected call of GetNFT.
func (mr *MockOpenSeaClientMockRecorder) GetNFT(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNFT", reflect.TypeOf((*MockOpenSeaClient)(nil).GetNFT), ctx, contractAddress, tokenID)
}
