// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
	registry "github.com/feral-file/ff-indexer-v2/internal/registry"
)

// MockPublisherRegistry is a mock of PublisherRegistry interface.
type MockPublisherRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherRegistryMockRecorder
}

// MockPublisherRegistryMockRecorder is the mock recorder for MockPublisherRegistry.
type MockPublisherRegistryMockRecorder struct {
	mock *MockPublisherRegistry
}

// NewMockPublisherRegistry creates a new mock instance.
func NewMockPublisherRegistry(ctrl *gomock.Controller) *MockPublisherRegistry {
	mock := &MockPublisherRegistry{ctrl: ctrl}
	mock.recorder = &MockPublisherRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherRegistry) EXPECT() *MockPublisherRegistryMockRecorder {
	return m.recorder
}

// GetMinBlock mocks base method.
func (m *MockPublisherRegistry) GetMinBlock(chainID domain.Chain) (uint64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinBlock", chainID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMinBlock indicates an expected call of GetMinBlock.
func (mr *MockPublisherRegistryMockRecorder) GetMinBlock(chainID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinBlock", reflect.TypeOf((*MockPublisherRegistry)(nil).GetMinBlock), chainID)
}

// LookupPublisherByCollection mocks base method.
func (m *MockPublisherRegistry) LookupPublisherByCollection(chainID domain.Chain, contractAddress string) *registry.PublisherInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupPublisherByCollection", chainID, contractAddress)
	ret0, _ := ret[0].(*registry.PublisherInfo)
	return ret0
}

// LookupPublisherByCollection indicates an expected call of LookupPublisherByCollection.
func (mr *MockPublisherRegistryMockRecorder) LookupPublisherByCollection(chainID, contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupPublisherByCollection", reflect.TypeOf((*MockPublisherRegistry)(nil).LookupPublisherByCollection), chainID, contractAddress)
}

// LookupPublisherByDeployer mocks base method.
func (m *MockPublisherRegistry) LookupPublisherByDeployer(chainID domain.Chain, deployerAddress string) *registry.PublisherInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupPublisherByDeployer", chainID, deployerAddress)
	ret0, _ := ret[0].(*registry.PublisherInfo)
	return ret0
}

// LookupPublisherByDeployer indicates an expected call of LookupPublisherByDeployer.
func (mr *MockPublisherRegistryMockRecorder) LookupPublisherByDeployer(chainID, deployerAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupPublisherByDeployer", reflect.TypeOf((*MockPublisherRegistry)(nil).LookupPublisherByDeployer), chainID, deployerAddress)
}

// MockPublisherRegistryLoader is a mock of PublisherRegistryLoader interface.
type MockPublisherRegistryLoader struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherRegistryLoaderMockRecorder
}

// MockPublisherRegistryLoaderMockRecorder is the mock recorder for MockPublisherRegistryLoader.
type MockPublisherRegistryLoaderMockRecorder struct {
	mock *MockPublisherRegistryLoader
}

// NewMockPublisherRegistryLoader creates a new mock instance.
func NewMockPublisherRegistryLoader(ctrl *gomock.Controller) *MockPublisherRegistryLoader {
	mock := &MockPublisherRegistryLoader{ctrl: ctrl}
	mock.recorder = &MockPublisherRegistryLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherRegistryLoader) EXPECT() *MockPublisherRegistryLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockPublisherRegistryLoader) Load(filePath string) (registry.PublisherRegistry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", filePath)
	ret0, _ := ret[0].(registry.PublisherRegistry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockPublisherRegistryLoaderMockRecorder) Load(filePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockPublisherRegistryLoader)(nil).Load), filePath)
}
