// Code generated by MockGen. DO NOT EDIT.
// Source: limiter.go
//
// Generated by this command:
//
//	mockgen -source=limiter.go -destination=../mocks/ratelimit_limiter.go -package=mocks -mock_names=Limiter=MockLimiter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	ratelimit "github.com/feral-file/ff-indexer-v2/internal/ratelimit"
)

// MockLimiter is a mock of Limiter interface.
type MockLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockLimiterMockRecorder
	isgomock struct{}
}

// MockLimiterMockRecorder is the mock recorder for MockLimiter.
type MockLimiterMockRecorder struct {
	mock *MockLimiter
}

// NewMockLimiter creates a new mock instance.
func NewMockLimiter(ctrl *gomock.Controller) *MockLimiter {
	mock := &MockLimiter{ctrl: ctrl}
	mock.recorder = &MockLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimiter) EXPECT() *MockLimiterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockLimiter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLimiterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLimiter)(nil).Close))
}

// Do mocks base method.
func (m *MockLimiter) Do(ctx context.Context, providerName string, fn ratelimit.Func) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, providerName, fn)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockLimiterMockRecorder) Do(ctx, providerName, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockLimiter)(nil).Do), ctx, providerName, fn)
}
