// Code generated by MockGen. DO NOT EDIT.
// Source: rate_limiter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLocalRateLimiter is a mock of LocalRateLimiter interface.
type MockLocalRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockLocalRateLimiterMockRecorder
}

// MockLocalRateLimiterMockRecorder is the mock recorder for MockLocalRateLimiter.
type MockLocalRateLimiterMockRecorder struct {
	mock *MockLocalRateLimiter
}

// NewMockLocalRateLimiter creates a new mock instance.
func NewMockLocalRateLimiter(ctrl *gomock.Controller) *MockLocalRateLimiter {
	mock := &MockLocalRateLimiter{ctrl: ctrl}
	mock.recorder = &MockLocalRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalRateLimiter) EXPECT() *MockLocalRateLimiterMockRecorder {
	return m.recorder
}

// Wait mocks base method.
func (m *MockLocalRateLimiter) Wait(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockLocalRateLimiterMockRecorder) Wait(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockLocalRateLimiter)(nil).Wait), ctx)
}
