// Code generated by MockGen. DO NOT EDIT.
// Source: redis.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	redis_rate "github.com/go-redis/redis_rate/v10"
	gomock "github.com/golang/mock/gomock"
	redis "github.com/redis/go-redis/v9"

	adapter "github.com/feral-file/ff-indexer-v2/internal/adapter"
)

// MockRedisClient is a mock of RedisClient interface.
type MockRedisClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedisClientMockRecorder
}

// MockRedisClientMockRecorder is the mock recorder for MockRedisClient.
type MockRedisClientMockRecorder struct {
	mock *MockRedisClient
}

// NewMockRedisClient creates a new mock instance.
func NewMockRedisClient(ctrl *gomock.Controller) *MockRedisClient {
	mock := &MockRedisClient{ctrl: ctrl}
	mock.recorder = &MockRedisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisClient) EXPECT() *MockRedisClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedisClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedisClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisClient)(nil).Close))
}

// NewRateLimiter mocks base method.
func (m *MockRedisClient) NewRateLimiter() adapter.RedisRateLimiter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRateLimiter")
	ret0, _ := ret[0].(adapter.RedisRateLimiter)
	return ret0
}

// NewRateLimiter indicates an expected call of NewRateLimiter.
func (mr *MockRedisClientMockRecorder) NewRateLimiter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRateLimiter", reflect.TypeOf((*MockRedisClient)(nil).NewRateLimiter))
}

// Ping mocks base method.
func (m *MockRedisClient) Ping(ctx context.Context) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRedisClientMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRedisClient)(nil).Ping), ctx)
}

// MockRedisRateLimiter is a mock of RedisRateLimiter interface.
type MockRedisRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRateLimiterMockRecorder
}

// MockRedisRateLimiterMockRecorder is the mock recorder for MockRedisRateLimiter.
type MockRedisRateLimiterMockRecorder struct {
	mock *MockRedisRateLimiter
}

// NewMockRedisRateLimiter creates a new mock instance.
func NewMockRedisRateLimiter(ctrl *gomock.Controller) *MockRedisRateLimiter {
	mock := &MockRedisRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRedisRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRateLimiter) EXPECT() *MockRedisRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRedisRateLimiter) Allow(ctx context.Context, key string, limit redis_rate.Limit) (*redis_rate.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, key, limit)
	ret0, _ := ret[0].(*redis_rate.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockRedisRateLimiterMockRecorder) Allow(ctx, key, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRedisRateLimiter)(nil).Allow), ctx, key, limit)
}
