// Code generated by MockGen. DO NOT EDIT.
// Source: internal/workflows/render_probe_executor.go
//
// Generated by this command:
//
//	mockgen -source=internal/workflows/render_probe_executor.go -destination=internal/mocks/render_probe_executor.go -package=mocks -mock_names=RenderProbeExecutor=MockRenderProbeExecutor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRenderProbeExecutor is a mock of RenderProbeExecutor interface.
type MockRenderProbeExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockRenderProbeExecutorMockRecorder
	isgomock struct{}
}

// MockRenderProbeExecutorMockRecorder is the mock recorder for MockRenderProbeExecutor.
type MockRenderProbeExecutorMockRecorder struct {
	mock *MockRenderProbeExecutor
}

// NewMockRenderProbeExecutor creates a new mock instance.
func NewMockRenderProbeExecutor(ctrl *gomock.Controller) *MockRenderProbeExecutor {
	mock := &MockRenderProbeExecutor{ctrl: ctrl}
	mock.recorder = &MockRenderProbeExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRenderProbeExecutor) EXPECT() *MockRenderProbeExecutorMockRecorder {
	return m.recorder
}

// ExecuteRenderProbe mocks base method.
func (m *MockRenderProbeExecutor) ExecuteRenderProbe(ctx context.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteRenderProbe", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteRenderProbe indicates an expected call of ExecuteRenderProbe.
func (mr *MockRenderProbeExecutorMockRecorder) ExecuteRenderProbe(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteRenderProbe", reflect.TypeOf((*MockRenderProbeExecutor)(nil).ExecuteRenderProbe), ctx, url)
}
