// Code generated by MockGen. DO NOT EDIT.
// Source: resvg.go

// Package mocks is a generated GoMock package.
package mocks

import (
	image "image"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResvgClient is a mock of ResvgClient interface.
type MockResvgClient struct {
	ctrl     *gomock.Controller
	recorder *MockResvgClientMockRecorder
}

// MockResvgClientMockRecorder is the mock recorder for MockResvgClient.
type MockResvgClientMockRecorder struct {
	mock *MockResvgClient
}

// NewMockResvgClient creates a new mock instance.
func NewMockResvgClient(ctrl *gomock.Controller) *MockResvgClient {
	mock := &MockResvgClient{ctrl: ctrl}
	mock.recorder = &MockResvgClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResvgClient) EXPECT() *MockResvgClientMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockResvgClient) Render(data []byte, width int) (image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", data, width)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockResvgClientMockRecorder) Render(data, width interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockResvgClient)(nil).Render), data, width)
}
