// Code generated by MockGen. DO NOT EDIT.
// Source: signalr.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	adapter "github.com/feral-file/ff-indexer-v2/internal/adapter"
	gomock "github.com/golang/mock/gomock"
)

// MockSignalRClient is a mock of SignalRClient interface.
type MockSignalRClient struct {
	ctrl     *gomock.Controller
	recorder *MockSignalRClientMockRecorder
}

// MockSignalRClientMockRecorder is the mock recorder for MockSignalRClient.
type MockSignalRClientMockRecorder struct {
	mock *MockSignalRClient
}

// NewMockSignalRClient creates a new mock instance.
func NewMockSignalRClient(ctrl *gomock.Controller) *MockSignalRClient {
	mock := &MockSignalRClient{ctrl: ctrl}
	mock.recorder = &MockSignalRClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignalRClient) EXPECT() *MockSignalRClientMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSignalRClient) Send(target string, args ...interface{}) <-chan error {
	m.ctrl.T.Helper()
	varargs := []interface{}{target}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSignalRClientMockRecorder) Send(target interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{target}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSignalRClient)(nil).Send), varargs...)
}

// Start mocks base method.
func (m *MockSignalRClient) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockSignalRClientMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSignalRClient)(nil).Start))
}

// Stop mocks base method.
func (m *MockSignalRClient) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockSignalRClientMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSignalRClient)(nil).Stop))
}

// MockSignalR is a mock of SignalR interface.
type MockSignalR struct {
	ctrl     *gomock.Controller
	recorder *MockSignalRMockRecorder
}

// MockSignalRMockRecorder is the mock recorder for MockSignalR.
type MockSignalRMockRecorder struct {
	mock *MockSignalR
}

// NewMockSignalR creates a new mock instance.
func NewMockSignalR(ctrl *gomock.Controller) *MockSignalR {
	mock := &MockSignalR{ctrl: ctrl}
	mock.recorder = &MockSignalRMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignalR) EXPECT() *MockSignalRMockRecorder {
	return m.recorder
}

// NewClient mocks base method.
func (m *MockSignalR) NewClient(ctx context.Context, address string, receiver interface{}) (adapter.SignalRClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", ctx, address, receiver)
	ret0, _ := ret[0].(adapter.SignalRClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient.
func (mr *MockSignalRMockRecorder) NewClient(ctx, address, receiver interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockSignalR)(nil).NewClient), ctx, address, receiver)
}
