// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
	store "github.com/feral-file/ff-indexer-v2/internal/store"
	schema "github.com/feral-file/ff-indexer-v2/internal/store/schema"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateMediaAsset mocks base method.
func (m *MockStore) CreateMediaAsset(ctx context.Context, input store.CreateMediaAssetInput) (*schema.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMediaAsset", ctx, input)
	ret0, _ := ret[0].(*schema.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMediaAsset indicates an expected call of CreateMediaAsset.
func (mr *MockStoreMockRecorder) CreateMediaAsset(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMediaAsset", reflect.TypeOf((*MockStore)(nil).CreateMediaAsset), ctx, input)
}

// CreateMetadataUpdate mocks base method.
func (m *MockStore) CreateMetadataUpdate(ctx context.Context, input store.CreateMetadataUpdateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetadataUpdate", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMetadataUpdate indicates an expected call of CreateMetadataUpdate.
func (mr *MockStoreMockRecorder) CreateMetadataUpdate(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetadataUpdate", reflect.TypeOf((*MockStore)(nil).CreateMetadataUpdate), ctx, input)
}

// CreateTokenMint mocks base method.
func (m *MockStore) CreateTokenMint(ctx context.Context, input store.CreateTokenMintInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTokenMint", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTokenMint indicates an expected call of CreateTokenMint.
func (mr *MockStoreMockRecorder) CreateTokenMint(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTokenMint", reflect.TypeOf((*MockStore)(nil).CreateTokenMint), ctx, input)
}

// CreateTokenWithProvenances mocks base method.
func (m *MockStore) CreateTokenWithProvenances(ctx context.Context, input store.CreateTokenWithProvenancesInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTokenWithProvenances", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTokenWithProvenances indicates an expected call of CreateTokenWithProvenances.
func (mr *MockStoreMockRecorder) CreateTokenWithProvenances(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTokenWithProvenances", reflect.TypeOf((*MockStore)(nil).CreateTokenWithProvenances), ctx, input)
}

// EnsureWatchedAddressExists mocks base method.
func (m *MockStore) EnsureWatchedAddressExists(ctx context.Context, address string, chain domain.Chain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureWatchedAddressExists", ctx, address, chain)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureWatchedAddressExists indicates an expected call of EnsureWatchedAddressExists.
func (mr *MockStoreMockRecorder) EnsureWatchedAddressExists(ctx, address, chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureWatchedAddressExists", reflect.TypeOf((*MockStore)(nil).EnsureWatchedAddressExists), ctx, address, chain)
}

// GetAllKeyValuesByPrefix mocks base method.
func (m *MockStore) GetAllKeyValuesByPrefix(ctx context.Context, prefix string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllKeyValuesByPrefix", ctx, prefix)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllKeyValuesByPrefix indicates an expected call of GetAllKeyValuesByPrefix.
func (mr *MockStoreMockRecorder) GetAllKeyValuesByPrefix(ctx, prefix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllKeyValuesByPrefix", reflect.TypeOf((*MockStore)(nil).GetAllKeyValuesByPrefix), ctx, prefix)
}

// GetBalanceByID mocks base method.
func (m *MockStore) GetBalanceByID(ctx context.Context, id uint64) (*schema.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByID", ctx, id)
	ret0, _ := ret[0].(*schema.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByID indicates an expected call of GetBalanceByID.
func (mr *MockStoreMockRecorder) GetBalanceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByID", reflect.TypeOf((*MockStore)(nil).GetBalanceByID), ctx, id)
}

// GetBlockCursor mocks base method.
func (m *MockStore) GetBlockCursor(ctx context.Context, chain string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockCursor", ctx, chain)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockCursor indicates an expected call of GetBlockCursor.
func (mr *MockStoreMockRecorder) GetBlockCursor(ctx, chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockCursor", reflect.TypeOf((*MockStore)(nil).GetBlockCursor), ctx, chain)
}

// GetChanges mocks base method.
func (m *MockStore) GetChanges(ctx context.Context, filter store.ChangesQueryFilter) ([]*schema.ChangesJournal, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChanges", ctx, filter)
	ret0, _ := ret[0].([]*schema.ChangesJournal)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetChanges indicates an expected call of GetChanges.
func (mr *MockStoreMockRecorder) GetChanges(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChanges", reflect.TypeOf((*MockStore)(nil).GetChanges), ctx, filter)
}

// GetEnrichmentSourceByTokenCID mocks base method.
func (m *MockStore) GetEnrichmentSourceByTokenCID(ctx context.Context, tokenCID string) (*schema.EnrichmentSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrichmentSourceByTokenCID", ctx, tokenCID)
	ret0, _ := ret[0].(*schema.EnrichmentSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrichmentSourceByTokenCID indicates an expected call of GetEnrichmentSourceByTokenCID.
func (mr *MockStoreMockRecorder) GetEnrichmentSourceByTokenCID(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrichmentSourceByTokenCID", reflect.TypeOf((*MockStore)(nil).GetEnrichmentSourceByTokenCID), ctx, tokenCID)
}

// GetEnrichmentSourceByTokenID mocks base method.
func (m *MockStore) GetEnrichmentSourceByTokenID(ctx context.Context, tokenID uint64) (*schema.EnrichmentSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrichmentSourceByTokenID", ctx, tokenID)
	ret0, _ := ret[0].(*schema.EnrichmentSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrichmentSourceByTokenID indicates an expected call of GetEnrichmentSourceByTokenID.
func (mr *MockStoreMockRecorder) GetEnrichmentSourceByTokenID(ctx, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrichmentSourceByTokenID", reflect.TypeOf((*MockStore)(nil).GetEnrichmentSourceByTokenID), ctx, tokenID)
}

// GetIndexingBlockRangeForAddress mocks base method.
func (m *MockStore) GetIndexingBlockRangeForAddress(ctx context.Context, address string, chainID domain.Chain) (uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexingBlockRangeForAddress", ctx, address, chainID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIndexingBlockRangeForAddress indicates an expected call of GetIndexingBlockRangeForAddress.
func (mr *MockStoreMockRecorder) GetIndexingBlockRangeForAddress(ctx, address, chainID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexingBlockRangeForAddress", reflect.TypeOf((*MockStore)(nil).GetIndexingBlockRangeForAddress), ctx, address, chainID)
}

// GetKeyValue mocks base method.
func (m *MockStore) GetKeyValue(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyValue", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyValue indicates an expected call of GetKeyValue.
func (mr *MockStoreMockRecorder) GetKeyValue(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyValue", reflect.TypeOf((*MockStore)(nil).GetKeyValue), ctx, key)
}

// GetMediaAssetByID mocks base method.
func (m *MockStore) GetMediaAssetByID(ctx context.Context, id int64) (*schema.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaAssetByID", ctx, id)
	ret0, _ := ret[0].(*schema.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaAssetByID indicates an expected call of GetMediaAssetByID.
func (mr *MockStoreMockRecorder) GetMediaAssetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaAssetByID", reflect.TypeOf((*MockStore)(nil).GetMediaAssetByID), ctx, id)
}

// GetMediaAssetBySourceURL mocks base method.
func (m *MockStore) GetMediaAssetBySourceURL(ctx context.Context, sourceURL string, provider schema.StorageProvider) (*schema.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaAssetBySourceURL", ctx, sourceURL, provider)
	ret0, _ := ret[0].(*schema.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaAssetBySourceURL indicates an expected call of GetMediaAssetBySourceURL.
func (mr *MockStoreMockRecorder) GetMediaAssetBySourceURL(ctx, sourceURL, provider interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaAssetBySourceURL", reflect.TypeOf((*MockStore)(nil).GetMediaAssetBySourceURL), ctx, sourceURL, provider)
}

// GetMediaAssetsBySourceURLs mocks base method.
func (m *MockStore) GetMediaAssetsBySourceURLs(ctx context.Context, sourceURLs []string) ([]schema.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaAssetsBySourceURLs", ctx, sourceURLs)
	ret0, _ := ret[0].([]schema.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaAssetsBySourceURLs indicates an expected call of GetMediaAssetsBySourceURLs.
func (mr *MockStoreMockRecorder) GetMediaAssetsBySourceURLs(ctx, sourceURLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaAssetsBySourceURLs", reflect.TypeOf((*MockStore)(nil).GetMediaAssetsBySourceURLs), ctx, sourceURLs)
}

// GetProvenanceEventByID mocks base method.
func (m *MockStore) GetProvenanceEventByID(ctx context.Context, id uint64) (*schema.ProvenanceEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvenanceEventByID", ctx, id)
	ret0, _ := ret[0].(*schema.ProvenanceEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvenanceEventByID indicates an expected call of GetProvenanceEventByID.
func (mr *MockStoreMockRecorder) GetProvenanceEventByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvenanceEventByID", reflect.TypeOf((*MockStore)(nil).GetProvenanceEventByID), ctx, id)
}

// GetTokenByTokenCID mocks base method.
func (m *MockStore) GetTokenByTokenCID(ctx context.Context, tokenCID string) (*schema.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByTokenCID", ctx, tokenCID)
	ret0, _ := ret[0].(*schema.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByTokenCID indicates an expected call of GetTokenByTokenCID.
func (mr *MockStoreMockRecorder) GetTokenByTokenCID(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByTokenCID", reflect.TypeOf((*MockStore)(nil).GetTokenByTokenCID), ctx, tokenCID)
}

// GetTokenCIDsByOwner mocks base method.
func (m *MockStore) GetTokenCIDsByOwner(ctx context.Context, ownerAddress string) ([]domain.TokenCID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenCIDsByOwner", ctx, ownerAddress)
	ret0, _ := ret[0].([]domain.TokenCID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenCIDsByOwner indicates an expected call of GetTokenCIDsByOwner.
func (mr *MockStoreMockRecorder) GetTokenCIDsByOwner(ctx, ownerAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenCIDsByOwner", reflect.TypeOf((*MockStore)(nil).GetTokenCIDsByOwner), ctx, ownerAddress)
}

// GetTokenMetadataByTokenCID mocks base method.
func (m *MockStore) GetTokenMetadataByTokenCID(ctx context.Context, tokenCID string) (*schema.TokenMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMetadataByTokenCID", ctx, tokenCID)
	ret0, _ := ret[0].(*schema.TokenMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMetadataByTokenCID indicates an expected call of GetTokenMetadataByTokenCID.
func (mr *MockStoreMockRecorder) GetTokenMetadataByTokenCID(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMetadataByTokenCID", reflect.TypeOf((*MockStore)(nil).GetTokenMetadataByTokenCID), ctx, tokenCID)
}

// GetTokenMetadataByTokenID mocks base method.
func (m *MockStore) GetTokenMetadataByTokenID(ctx context.Context, tokenID uint64) (*schema.TokenMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMetadataByTokenID", ctx, tokenID)
	ret0, _ := ret[0].(*schema.TokenMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMetadataByTokenID indicates an expected call of GetTokenMetadataByTokenID.
func (mr *MockStoreMockRecorder) GetTokenMetadataByTokenID(ctx, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMetadataByTokenID", reflect.TypeOf((*MockStore)(nil).GetTokenMetadataByTokenID), ctx, tokenID)
}

// GetTokenOwners mocks base method.
func (m *MockStore) GetTokenOwners(ctx context.Context, tokenID uint64, limit int, offset uint64) ([]schema.Balance, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenOwners", ctx, tokenID, limit, offset)
	ret0, _ := ret[0].([]schema.Balance)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTokenOwners indicates an expected call of GetTokenOwners.
func (mr *MockStoreMockRecorder) GetTokenOwners(ctx, tokenID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenOwners", reflect.TypeOf((*MockStore)(nil).GetTokenOwners), ctx, tokenID, limit, offset)
}

// GetTokenProvenanceEvents mocks base method.
func (m *MockStore) GetTokenProvenanceEvents(ctx context.Context, tokenID uint64, limit int, offset uint64, orderDesc bool) ([]schema.ProvenanceEvent, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenProvenanceEvents", ctx, tokenID, limit, offset, orderDesc)
	ret0, _ := ret[0].([]schema.ProvenanceEvent)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTokenProvenanceEvents indicates an expected call of GetTokenProvenanceEvents.
func (mr *MockStoreMockRecorder) GetTokenProvenanceEvents(ctx, tokenID, limit, offset, orderDesc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenProvenanceEvents", reflect.TypeOf((*MockStore)(nil).GetTokenProvenanceEvents), ctx, tokenID, limit, offset, orderDesc)
}

// GetTokenWithMetadataByTokenCID mocks base method.
func (m *MockStore) GetTokenWithMetadataByTokenCID(ctx context.Context, tokenCID string) (*store.TokensWithMetadataResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenWithMetadataByTokenCID", ctx, tokenCID)
	ret0, _ := ret[0].(*store.TokensWithMetadataResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenWithMetadataByTokenCID indicates an expected call of GetTokenWithMetadataByTokenCID.
func (mr *MockStoreMockRecorder) GetTokenWithMetadataByTokenCID(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenWithMetadataByTokenCID", reflect.TypeOf((*MockStore)(nil).GetTokenWithMetadataByTokenCID), ctx, tokenCID)
}

// GetTokensByFilter mocks base method.
func (m *MockStore) GetTokensByFilter(ctx context.Context, filter store.TokenQueryFilter) ([]*store.TokensWithMetadataResult, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokensByFilter", ctx, filter)
	ret0, _ := ret[0].([]*store.TokensWithMetadataResult)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTokensByFilter indicates an expected call of GetTokensByFilter.
func (mr *MockStoreMockRecorder) GetTokensByFilter(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokensByFilter", reflect.TypeOf((*MockStore)(nil).GetTokensByFilter), ctx, filter)
}

// IsAnyAddressWatched mocks base method.
func (m *MockStore) IsAnyAddressWatched(ctx context.Context, chain domain.Chain, addresses []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAnyAddressWatched", ctx, chain, addresses)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAnyAddressWatched indicates an expected call of IsAnyAddressWatched.
func (mr *MockStoreMockRecorder) IsAnyAddressWatched(ctx, chain, addresses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAnyAddressWatched", reflect.TypeOf((*MockStore)(nil).IsAnyAddressWatched), ctx, chain, addresses)
}

// SetBlockCursor mocks base method.
func (m *MockStore) SetBlockCursor(ctx context.Context, chain string, blockNumber uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlockCursor", ctx, chain, blockNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlockCursor indicates an expected call of SetBlockCursor.
func (mr *MockStoreMockRecorder) SetBlockCursor(ctx, chain, blockNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockCursor", reflect.TypeOf((*MockStore)(nil).SetBlockCursor), ctx, chain, blockNumber)
}

// SetKeyValue mocks base method.
func (m *MockStore) SetKeyValue(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKeyValue", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKeyValue indicates an expected call of SetKeyValue.
func (mr *MockStoreMockRecorder) SetKeyValue(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeyValue", reflect.TypeOf((*MockStore)(nil).SetKeyValue), ctx, key, value)
}

// UpdateIndexingBlockRangeForAddress mocks base method.
func (m *MockStore) UpdateIndexingBlockRangeForAddress(ctx context.Context, address string, chainID domain.Chain, minBlock, maxBlock uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIndexingBlockRangeForAddress", ctx, address, chainID, minBlock, maxBlock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIndexingBlockRangeForAddress indicates an expected call of UpdateIndexingBlockRangeForAddress.
func (mr *MockStoreMockRecorder) UpdateIndexingBlockRangeForAddress(ctx, address, chainID, minBlock, maxBlock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndexingBlockRangeForAddress", reflect.TypeOf((*MockStore)(nil).UpdateIndexingBlockRangeForAddress), ctx, address, chainID, minBlock, maxBlock)
}

// UpdateTokenBurn mocks base method.
func (m *MockStore) UpdateTokenBurn(ctx context.Context, input store.CreateTokenBurnInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenBurn", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenBurn indicates an expected call of UpdateTokenBurn.
func (mr *MockStoreMockRecorder) UpdateTokenBurn(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenBurn", reflect.TypeOf((*MockStore)(nil).UpdateTokenBurn), ctx, input)
}

// UpdateTokenTransfer mocks base method.
func (m *MockStore) UpdateTokenTransfer(ctx context.Context, input store.UpdateTokenTransferInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenTransfer", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenTransfer indicates an expected call of UpdateTokenTransfer.
func (mr *MockStoreMockRecorder) UpdateTokenTransfer(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenTransfer", reflect.TypeOf((*MockStore)(nil).UpdateTokenTransfer), ctx, input)
}

// UpsertEnrichmentSource mocks base method.
func (m *MockStore) UpsertEnrichmentSource(ctx context.Context, input store.CreateEnrichmentSourceInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEnrichmentSource", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEnrichmentSource indicates an expected call of UpsertEnrichmentSource.
func (mr *MockStoreMockRecorder) UpsertEnrichmentSource(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEnrichmentSource", reflect.TypeOf((*MockStore)(nil).UpsertEnrichmentSource), ctx, input)
}

// UpsertTokenMetadata mocks base method.
func (m *MockStore) UpsertTokenMetadata(ctx context.Context, input store.CreateTokenMetadataInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTokenMetadata", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTokenMetadata indicates an expected call of UpsertTokenMetadata.
func (mr *MockStoreMockRecorder) UpsertTokenMetadata(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTokenMetadata", reflect.TypeOf((*MockStore)(nil).UpsertTokenMetadata), ctx, input)
}
