// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=../mocks/store.go -package=mocks -mock_names=Store=MockStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
	store "github.com/feral-file/ff-indexer-v2/internal/store"
	schema "github.com/feral-file/ff-indexer-v2/internal/store/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AcquireJobQueueLock mocks base method.
func (m *MockStore) AcquireJobQueueLock(ctx context.Context, queue string) (bool, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireJobQueueLock", ctx, queue)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcquireJobQueueLock indicates an expected call of AcquireJobQueueLock.
func (mr *MockStoreMockRecorder) AcquireJobQueueLock(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireJobQueueLock", reflect.TypeOf((*MockStore)(nil).AcquireJobQueueLock), ctx, queue)
}

// BatchUpdateTokensViewability mocks base method.
func (m *MockStore) BatchUpdateTokensViewability(ctx context.Context, tokenIDs []uint64) ([]store.TokenViewabilityChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateTokensViewability", ctx, tokenIDs)
	ret0, _ := ret[0].([]store.TokenViewabilityChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdateTokensViewability indicates an expected call of BatchUpdateTokensViewability.
func (mr *MockStoreMockRecorder) BatchUpdateTokensViewability(ctx, tokenIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateTokensViewability", reflect.TypeOf((*MockStore)(nil).BatchUpdateTokensViewability), ctx, tokenIDs)
}

// ClaimJobs mocks base method.
func (m *MockStore) ClaimJobs(ctx context.Context, queue string, limit int) ([]*schema.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimJobs", ctx, queue, limit)
	ret0, _ := ret[0].([]*schema.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimJobs indicates an expected call of ClaimJobs.
func (mr *MockStoreMockRecorder) ClaimJobs(ctx, queue, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimJobs", reflect.TypeOf((*MockStore)(nil).ClaimJobs), ctx, queue, limit)
}

// CreateAddressIndexingJob mocks base method.
func (m *MockStore) CreateAddressIndexingJob(ctx context.Context, input store.CreateAddressIndexingJobInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddressIndexingJob", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddressIndexingJob indicates an expected call of CreateAddressIndexingJob.
func (mr *MockStoreMockRecorder) CreateAddressIndexingJob(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddressIndexingJob", reflect.TypeOf((*MockStore)(nil).CreateAddressIndexingJob), ctx, input)
}

// CreateMediaAsset mocks base method.
func (m *MockStore) CreateMediaAsset(ctx context.Context, input store.CreateMediaAssetInput) (*schema.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMediaAsset", ctx, input)
	ret0, _ := ret[0].(*schema.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMediaAsset indicates an expected call of CreateMediaAsset.
func (mr *MockStoreMockRecorder) CreateMediaAsset(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMediaAsset", reflect.TypeOf((*MockStore)(nil).CreateMediaAsset), ctx, input)
}

// CreateMetadataUpdate mocks base method.
func (m *MockStore) CreateMetadataUpdate(ctx context.Context, input store.CreateMetadataUpdateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetadataUpdate", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMetadataUpdate indicates an expected call of CreateMetadataUpdate.
func (mr *MockStoreMockRecorder) CreateMetadataUpdate(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetadataUpdate", reflect.TypeOf((*MockStore)(nil).CreateMetadataUpdate), ctx, input)
}

// CreateTokenMint mocks base method.
func (m *MockStore) CreateTokenMint(ctx context.Context, input store.CreateTokenMintInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTokenMint", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTokenMint indicates an expected call of CreateTokenMint.
func (mr *MockStoreMockRecorder) CreateTokenMint(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTokenMint", reflect.TypeOf((*MockStore)(nil).CreateTokenMint), ctx, input)
}

// CreateTokenWithProvenances mocks base method.
func (m *MockStore) CreateTokenWithProvenances(ctx context.Context, input store.CreateTokenWithProvenancesInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTokenWithProvenances", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTokenWithProvenances indicates an expected call of CreateTokenWithProvenances.
func (mr *MockStoreMockRecorder) CreateTokenWithProvenances(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTokenWithProvenances", reflect.TypeOf((*MockStore)(nil).CreateTokenWithProvenances), ctx, input)
}

// CreateWebhookClient mocks base method.
func (m *MockStore) CreateWebhookClient(ctx context.Context, input store.CreateWebhookClientInput) (*schema.WebhookClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhookClient", ctx, input)
	ret0, _ := ret[0].(*schema.WebhookClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhookClient indicates an expected call of CreateWebhookClient.
func (mr *MockStoreMockRecorder) CreateWebhookClient(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhookClient", reflect.TypeOf((*MockStore)(nil).CreateWebhookClient), ctx, input)
}

// CreateWebhookDelivery mocks base method.
func (m *MockStore) CreateWebhookDelivery(ctx context.Context, delivery *schema.WebhookDelivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhookDelivery", ctx, delivery)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWebhookDelivery indicates an expected call of CreateWebhookDelivery.
func (mr *MockStoreMockRecorder) CreateWebhookDelivery(ctx, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhookDelivery", reflect.TypeOf((*MockStore)(nil).CreateWebhookDelivery), ctx, delivery)
}

// EnqueueJob mocks base method.
func (m *MockStore) EnqueueJob(ctx context.Context, input store.EnqueueJobInput) (*schema.Job, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueJob", ctx, input)
	ret0, _ := ret[0].(*schema.Job)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EnqueueJob indicates an expected call of EnqueueJob.
func (mr *MockStoreMockRecorder) EnqueueJob(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueJob", reflect.TypeOf((*MockStore)(nil).EnqueueJob), ctx, input)
}

// EnsureWatchedAddressExists mocks base method.
func (m *MockStore) EnsureWatchedAddressExists(ctx context.Context, address string, chain domain.Chain, dailyQuota int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureWatchedAddressExists", ctx, address, chain, dailyQuota)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureWatchedAddressExists indicates an expected call of EnsureWatchedAddressExists.
func (mr *MockStoreMockRecorder) EnsureWatchedAddressExists(ctx, address, chain, dailyQuota any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureWatchedAddressExists", reflect.TypeOf((*MockStore)(nil).EnsureWatchedAddressExists), ctx, address, chain, dailyQuota)
}

// GetActiveIndexingJobForAddress mocks base method.
func (m *MockStore) GetActiveIndexingJobForAddress(ctx context.Context, address string, chainID domain.Chain) (*schema.AddressIndexingJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveIndexingJobForAddress", ctx, address, chainID)
	ret0, _ := ret[0].(*schema.AddressIndexingJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveIndexingJobForAddress indicates an expected call of GetActiveIndexingJobForAddress.
func (mr *MockStoreMockRecorder) GetActiveIndexingJobForAddress(ctx, address, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveIndexingJobForAddress", reflect.TypeOf((*MockStore)(nil).GetActiveIndexingJobForAddress), ctx, address, chainID)
}

// GetActiveWebhookClientsByEventType mocks base method.
func (m *MockStore) GetActiveWebhookClientsByEventType(ctx context.Context, eventType string) ([]*schema.WebhookClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveWebhookClientsByEventType", ctx, eventType)
	ret0, _ := ret[0].([]*schema.WebhookClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveWebhookClientsByEventType indicates an expected call of GetActiveWebhookClientsByEventType.
func (mr *MockStoreMockRecorder) GetActiveWebhookClientsByEventType(ctx, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveWebhookClientsByEventType", reflect.TypeOf((*MockStore)(nil).GetActiveWebhookClientsByEventType), ctx, eventType)
}

// GetAddressIndexingJobByJobID mocks base method.
func (m *MockStore) GetAddressIndexingJobByJobID(ctx context.Context, jobID int64) (*schema.AddressIndexingJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressIndexingJobByJobID", ctx, jobID)
	ret0, _ := ret[0].(*schema.AddressIndexingJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressIndexingJobByJobID indicates an expected call of GetAddressIndexingJobByJobID.
func (mr *MockStoreMockRecorder) GetAddressIndexingJobByJobID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressIndexingJobByJobID", reflect.TypeOf((*MockStore)(nil).GetAddressIndexingJobByJobID), ctx, jobID)
}

// GetAddressIndexingJobByWorkflowID mocks base method.
func (m *MockStore) GetAddressIndexingJobByWorkflowID(ctx context.Context, workflowID string) (*schema.AddressIndexingJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressIndexingJobByWorkflowID", ctx, workflowID)
	ret0, _ := ret[0].(*schema.AddressIndexingJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressIndexingJobByWorkflowID indicates an expected call of GetAddressIndexingJobByWorkflowID.
func (mr *MockStoreMockRecorder) GetAddressIndexingJobByWorkflowID(ctx, workflowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressIndexingJobByWorkflowID", reflect.TypeOf((*MockStore)(nil).GetAddressIndexingJobByWorkflowID), ctx, workflowID)
}

// GetAllKeyValuesByPrefix mocks base method.
func (m *MockStore) GetAllKeyValuesByPrefix(ctx context.Context, prefix string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllKeyValuesByPrefix", ctx, prefix)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllKeyValuesByPrefix indicates an expected call of GetAllKeyValuesByPrefix.
func (mr *MockStoreMockRecorder) GetAllKeyValuesByPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllKeyValuesByPrefix", reflect.TypeOf((*MockStore)(nil).GetAllKeyValuesByPrefix), ctx, prefix)
}

// GetBlockCursor mocks base method.
func (m *MockStore) GetBlockCursor(ctx context.Context, chain string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockCursor", ctx, chain)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockCursor indicates an expected call of GetBlockCursor.
func (mr *MockStoreMockRecorder) GetBlockCursor(ctx, chain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockCursor", reflect.TypeOf((*MockStore)(nil).GetBlockCursor), ctx, chain)
}

// GetEnrichmentSourceByTokenCID mocks base method.
func (m *MockStore) GetEnrichmentSourceByTokenCID(ctx context.Context, tokenCID string) (*schema.EnrichmentSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrichmentSourceByTokenCID", ctx, tokenCID)
	ret0, _ := ret[0].(*schema.EnrichmentSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrichmentSourceByTokenCID indicates an expected call of GetEnrichmentSourceByTokenCID.
func (mr *MockStoreMockRecorder) GetEnrichmentSourceByTokenCID(ctx, tokenCID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrichmentSourceByTokenCID", reflect.TypeOf((*MockStore)(nil).GetEnrichmentSourceByTokenCID), ctx, tokenCID)
}

// GetEnrichmentSourceByTokenID mocks base method.
func (m *MockStore) GetEnrichmentSourceByTokenID(ctx context.Context, tokenID uint64) (*schema.EnrichmentSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrichmentSourceByTokenID", ctx, tokenID)
	ret0, _ := ret[0].(*schema.EnrichmentSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrichmentSourceByTokenID indicates an expected call of GetEnrichmentSourceByTokenID.
func (mr *MockStoreMockRecorder) GetEnrichmentSourceByTokenID(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrichmentSourceByTokenID", reflect.TypeOf((*MockStore)(nil).GetEnrichmentSourceByTokenID), ctx, tokenID)
}

// GetEnrichmentSourcesByTokenIDs mocks base method.
func (m *MockStore) GetEnrichmentSourcesByTokenIDs(ctx context.Context, tokenIDs []uint64) (map[uint64]*schema.EnrichmentSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnrichmentSourcesByTokenIDs", ctx, tokenIDs)
	ret0, _ := ret[0].(map[uint64]*schema.EnrichmentSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnrichmentSourcesByTokenIDs indicates an expected call of GetEnrichmentSourcesByTokenIDs.
func (mr *MockStoreMockRecorder) GetEnrichmentSourcesByTokenIDs(ctx, tokenIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnrichmentSourcesByTokenIDs", reflect.TypeOf((*MockStore)(nil).GetEnrichmentSourcesByTokenIDs), ctx, tokenIDs)
}

// GetIndexingBlockRangeForAddress mocks base method.
func (m *MockStore) GetIndexingBlockRangeForAddress(ctx context.Context, address string, chainID domain.Chain) (uint64, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexingBlockRangeForAddress", ctx, address, chainID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIndexingBlockRangeForAddress indicates an expected call of GetIndexingBlockRangeForAddress.
func (mr *MockStoreMockRecorder) GetIndexingBlockRangeForAddress(ctx, address, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexingBlockRangeForAddress", reflect.TypeOf((*MockStore)(nil).GetIndexingBlockRangeForAddress), ctx, address, chainID)
}

// GetJob mocks base method.
func (m *MockStore) GetJob(ctx context.Context, id int64) (*schema.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, id)
	ret0, _ := ret[0].(*schema.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockStoreMockRecorder) GetJob(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockStore)(nil).GetJob), ctx, id)
}

// GetKeyValue mocks base method.
func (m *MockStore) GetKeyValue(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyValue", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyValue indicates an expected call of GetKeyValue.
func (mr *MockStoreMockRecorder) GetKeyValue(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyValue", reflect.TypeOf((*MockStore)(nil).GetKeyValue), ctx, key)
}

// GetMediaAssetByID mocks base method.
func (m *MockStore) GetMediaAssetByID(ctx context.Context, id int64) (*schema.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaAssetByID", ctx, id)
	ret0, _ := ret[0].(*schema.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaAssetByID indicates an expected call of GetMediaAssetByID.
func (mr *MockStoreMockRecorder) GetMediaAssetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaAssetByID", reflect.TypeOf((*MockStore)(nil).GetMediaAssetByID), ctx, id)
}

// GetMediaAssetBySourceURL mocks base method.
func (m *MockStore) GetMediaAssetBySourceURL(ctx context.Context, sourceURL string, provider schema.StorageProvider) (*schema.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaAssetBySourceURL", ctx, sourceURL, provider)
	ret0, _ := ret[0].(*schema.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaAssetBySourceURL indicates an expected call of GetMediaAssetBySourceURL.
func (mr *MockStoreMockRecorder) GetMediaAssetBySourceURL(ctx, sourceURL, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaAssetBySourceURL", reflect.TypeOf((*MockStore)(nil).GetMediaAssetBySourceURL), ctx, sourceURL, provider)
}

// GetMediaAssetsBySourceURLs mocks base method.
func (m *MockStore) GetMediaAssetsBySourceURLs(ctx context.Context, sourceURLs []string) ([]schema.MediaAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaAssetsBySourceURLs", ctx, sourceURLs)
	ret0, _ := ret[0].([]schema.MediaAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaAssetsBySourceURLs indicates an expected call of GetMediaAssetsBySourceURLs.
func (mr *MockStoreMockRecorder) GetMediaAssetsBySourceURLs(ctx, sourceURLs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaAssetsBySourceURLs", reflect.TypeOf((*MockStore)(nil).GetMediaAssetsBySourceURLs), ctx, sourceURLs)
}

// GetProvenanceEventByID mocks base method.
func (m *MockStore) GetProvenanceEventByID(ctx context.Context, id uint64) (*schema.ProvenanceEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvenanceEventByID", ctx, id)
	ret0, _ := ret[0].(*schema.ProvenanceEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvenanceEventByID indicates an expected call of GetProvenanceEventByID.
func (mr *MockStoreMockRecorder) GetProvenanceEventByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvenanceEventByID", reflect.TypeOf((*MockStore)(nil).GetProvenanceEventByID), ctx, id)
}

// GetQuotaInfo mocks base method.
func (m *MockStore) GetQuotaInfo(ctx context.Context, address string, chain domain.Chain) (*store.QuotaInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaInfo", ctx, address, chain)
	ret0, _ := ret[0].(*store.QuotaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaInfo indicates an expected call of GetQuotaInfo.
func (mr *MockStoreMockRecorder) GetQuotaInfo(ctx, address, chain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaInfo", reflect.TypeOf((*MockStore)(nil).GetQuotaInfo), ctx, address, chain)
}

// GetReleaseByID mocks base method.
func (m *MockStore) GetReleaseByID(ctx context.Context, id uint64) (*schema.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReleaseByID", ctx, id)
	ret0, _ := ret[0].(*schema.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReleaseByID indicates an expected call of GetReleaseByID.
func (mr *MockStoreMockRecorder) GetReleaseByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleaseByID", reflect.TypeOf((*MockStore)(nil).GetReleaseByID), ctx, id)
}

// GetReleaseMembersByTokenIDs mocks base method.
func (m *MockStore) GetReleaseMembersByTokenIDs(ctx context.Context, tokenIDs []uint64) (map[uint64]*schema.ReleaseMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReleaseMembersByTokenIDs", ctx, tokenIDs)
	ret0, _ := ret[0].(map[uint64]*schema.ReleaseMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReleaseMembersByTokenIDs indicates an expected call of GetReleaseMembersByTokenIDs.
func (mr *MockStoreMockRecorder) GetReleaseMembersByTokenIDs(ctx, tokenIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleaseMembersByTokenIDs", reflect.TypeOf((*MockStore)(nil).GetReleaseMembersByTokenIDs), ctx, tokenIDs)
}

// GetTokenByTokenCID mocks base method.
func (m *MockStore) GetTokenByTokenCID(ctx context.Context, tokenCID string) (*schema.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByTokenCID", ctx, tokenCID)
	ret0, _ := ret[0].(*schema.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByTokenCID indicates an expected call of GetTokenByTokenCID.
func (mr *MockStoreMockRecorder) GetTokenByTokenCID(ctx, tokenCID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByTokenCID", reflect.TypeOf((*MockStore)(nil).GetTokenByTokenCID), ctx, tokenCID)
}

// GetTokenCIDsByOwner mocks base method.
func (m *MockStore) GetTokenCIDsByOwner(ctx context.Context, ownerAddress string) ([]domain.TokenCID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenCIDsByOwner", ctx, ownerAddress)
	ret0, _ := ret[0].([]domain.TokenCID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenCIDsByOwner indicates an expected call of GetTokenCIDsByOwner.
func (mr *MockStoreMockRecorder) GetTokenCIDsByOwner(ctx, ownerAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenCIDsByOwner", reflect.TypeOf((*MockStore)(nil).GetTokenCIDsByOwner), ctx, ownerAddress)
}

// GetTokenChangesByOwnerSinceCheckpoint mocks base method.
func (m *MockStore) GetTokenChangesByOwnerSinceCheckpoint(ctx context.Context, ownerAddress string, sinceTimestamp time.Time, sinceEventID uint64, limit int) ([]schema.TokenEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenChangesByOwnerSinceCheckpoint", ctx, ownerAddress, sinceTimestamp, sinceEventID, limit)
	ret0, _ := ret[0].([]schema.TokenEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenChangesByOwnerSinceCheckpoint indicates an expected call of GetTokenChangesByOwnerSinceCheckpoint.
func (mr *MockStoreMockRecorder) GetTokenChangesByOwnerSinceCheckpoint(ctx, ownerAddress, sinceTimestamp, sinceEventID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenChangesByOwnerSinceCheckpoint", reflect.TypeOf((*MockStore)(nil).GetTokenChangesByOwnerSinceCheckpoint), ctx, ownerAddress, sinceTimestamp, sinceEventID, limit)
}

// GetTokenCountsByAddress mocks base method.
func (m *MockStore) GetTokenCountsByAddress(ctx context.Context, address string, chain domain.Chain) (*store.TokenCountsByAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenCountsByAddress", ctx, address, chain)
	ret0, _ := ret[0].(*store.TokenCountsByAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenCountsByAddress indicates an expected call of GetTokenCountsByAddress.
func (mr *MockStoreMockRecorder) GetTokenCountsByAddress(ctx, address, chain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenCountsByAddress", reflect.TypeOf((*MockStore)(nil).GetTokenCountsByAddress), ctx, address, chain)
}

// GetTokenIDsByMediaURL mocks base method.
func (m *MockStore) GetTokenIDsByMediaURL(ctx context.Context, url string) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenIDsByMediaURL", ctx, url)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenIDsByMediaURL indicates an expected call of GetTokenIDsByMediaURL.
func (mr *MockStoreMockRecorder) GetTokenIDsByMediaURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenIDsByMediaURL", reflect.TypeOf((*MockStore)(nil).GetTokenIDsByMediaURL), ctx, url)
}

// GetTokenMediaHealthByTokenIDs mocks base method.
func (m *MockStore) GetTokenMediaHealthByTokenIDs(ctx context.Context, tokenIDs []uint64) (map[uint64][]schema.TokenMediaHealth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMediaHealthByTokenIDs", ctx, tokenIDs)
	ret0, _ := ret[0].(map[uint64][]schema.TokenMediaHealth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMediaHealthByTokenIDs indicates an expected call of GetTokenMediaHealthByTokenIDs.
func (mr *MockStoreMockRecorder) GetTokenMediaHealthByTokenIDs(ctx, tokenIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMediaHealthByTokenIDs", reflect.TypeOf((*MockStore)(nil).GetTokenMediaHealthByTokenIDs), ctx, tokenIDs)
}

// GetTokenMetadataByTokenCID mocks base method.
func (m *MockStore) GetTokenMetadataByTokenCID(ctx context.Context, tokenCID string) (*schema.TokenMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMetadataByTokenCID", ctx, tokenCID)
	ret0, _ := ret[0].(*schema.TokenMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMetadataByTokenCID indicates an expected call of GetTokenMetadataByTokenCID.
func (mr *MockStoreMockRecorder) GetTokenMetadataByTokenCID(ctx, tokenCID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMetadataByTokenCID", reflect.TypeOf((*MockStore)(nil).GetTokenMetadataByTokenCID), ctx, tokenCID)
}

// GetTokenMetadataByTokenID mocks base method.
func (m *MockStore) GetTokenMetadataByTokenID(ctx context.Context, tokenID uint64) (*schema.TokenMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMetadataByTokenID", ctx, tokenID)
	ret0, _ := ret[0].(*schema.TokenMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMetadataByTokenID indicates an expected call of GetTokenMetadataByTokenID.
func (mr *MockStoreMockRecorder) GetTokenMetadataByTokenID(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMetadataByTokenID", reflect.TypeOf((*MockStore)(nil).GetTokenMetadataByTokenID), ctx, tokenID)
}

// GetTokenMetadataByTokenIDs mocks base method.
func (m *MockStore) GetTokenMetadataByTokenIDs(ctx context.Context, tokenIDs []uint64) (map[uint64]*schema.TokenMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMetadataByTokenIDs", ctx, tokenIDs)
	ret0, _ := ret[0].(map[uint64]*schema.TokenMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMetadataByTokenIDs indicates an expected call of GetTokenMetadataByTokenIDs.
func (mr *MockStoreMockRecorder) GetTokenMetadataByTokenIDs(ctx, tokenIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMetadataByTokenIDs", reflect.TypeOf((*MockStore)(nil).GetTokenMetadataByTokenIDs), ctx, tokenIDs)
}

// GetTokenOwnerProvenancesBulk mocks base method.
func (m *MockStore) GetTokenOwnerProvenancesBulk(ctx context.Context, tokenIDs []uint64, ownerAddresses []string, maxPerToken int) (map[uint64][]schema.TokenOwnershipProvenance, map[uint64]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenOwnerProvenancesBulk", ctx, tokenIDs, ownerAddresses, maxPerToken)
	ret0, _ := ret[0].(map[uint64][]schema.TokenOwnershipProvenance)
	ret1, _ := ret[1].(map[uint64]uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTokenOwnerProvenancesBulk indicates an expected call of GetTokenOwnerProvenancesBulk.
func (mr *MockStoreMockRecorder) GetTokenOwnerProvenancesBulk(ctx, tokenIDs, ownerAddresses, maxPerToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenOwnerProvenancesBulk", reflect.TypeOf((*MockStore)(nil).GetTokenOwnerProvenancesBulk), ctx, tokenIDs, ownerAddresses, maxPerToken)
}

// GetTokenOwners mocks base method.
func (m *MockStore) GetTokenOwners(ctx context.Context, tokenID uint64, limit int, offset uint64) ([]schema.Balance, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenOwners", ctx, tokenID, limit, offset)
	ret0, _ := ret[0].([]schema.Balance)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTokenOwners indicates an expected call of GetTokenOwners.
func (mr *MockStoreMockRecorder) GetTokenOwners(ctx, tokenID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenOwners", reflect.TypeOf((*MockStore)(nil).GetTokenOwners), ctx, tokenID, limit, offset)
}

// GetTokenOwnersBulk mocks base method.
func (m *MockStore) GetTokenOwnersBulk(ctx context.Context, tokenIDs []uint64, limit int) (map[uint64][]schema.Balance, map[uint64]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenOwnersBulk", ctx, tokenIDs, limit)
	ret0, _ := ret[0].(map[uint64][]schema.Balance)
	ret1, _ := ret[1].(map[uint64]uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTokenOwnersBulk indicates an expected call of GetTokenOwnersBulk.
func (mr *MockStoreMockRecorder) GetTokenOwnersBulk(ctx, tokenIDs, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenOwnersBulk", reflect.TypeOf((*MockStore)(nil).GetTokenOwnersBulk), ctx, tokenIDs, limit)
}

// GetTokenProvenanceEvents mocks base method.
func (m *MockStore) GetTokenProvenanceEvents(ctx context.Context, tokenID uint64, limit int, offset uint64, orderDesc bool) ([]schema.ProvenanceEvent, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenProvenanceEvents", ctx, tokenID, limit, offset, orderDesc)
	ret0, _ := ret[0].([]schema.ProvenanceEvent)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTokenProvenanceEvents indicates an expected call of GetTokenProvenanceEvents.
func (mr *MockStoreMockRecorder) GetTokenProvenanceEvents(ctx, tokenID, limit, offset, orderDesc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenProvenanceEvents", reflect.TypeOf((*MockStore)(nil).GetTokenProvenanceEvents), ctx, tokenID, limit, offset, orderDesc)
}

// GetTokenProvenanceEventsBulk mocks base method.
func (m *MockStore) GetTokenProvenanceEventsBulk(ctx context.Context, tokenIDs []uint64, limit int) (map[uint64][]schema.ProvenanceEvent, map[uint64]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenProvenanceEventsBulk", ctx, tokenIDs, limit)
	ret0, _ := ret[0].(map[uint64][]schema.ProvenanceEvent)
	ret1, _ := ret[1].(map[uint64]uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTokenProvenanceEventsBulk indicates an expected call of GetTokenProvenanceEventsBulk.
func (mr *MockStoreMockRecorder) GetTokenProvenanceEventsBulk(ctx, tokenIDs, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenProvenanceEventsBulk", reflect.TypeOf((*MockStore)(nil).GetTokenProvenanceEventsBulk), ctx, tokenIDs, limit)
}

// GetTokenWithMetadataByTokenCID mocks base method.
func (m *MockStore) GetTokenWithMetadataByTokenCID(ctx context.Context, tokenCID string) (*store.TokensWithMetadataResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenWithMetadataByTokenCID", ctx, tokenCID)
	ret0, _ := ret[0].(*store.TokensWithMetadataResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenWithMetadataByTokenCID indicates an expected call of GetTokenWithMetadataByTokenCID.
func (mr *MockStoreMockRecorder) GetTokenWithMetadataByTokenCID(ctx, tokenCID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenWithMetadataByTokenCID", reflect.TypeOf((*MockStore)(nil).GetTokenWithMetadataByTokenCID), ctx, tokenCID)
}

// GetTokensByCIDs mocks base method.
func (m *MockStore) GetTokensByCIDs(ctx context.Context, tokenCIDs []string) ([]*schema.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokensByCIDs", ctx, tokenCIDs)
	ret0, _ := ret[0].([]*schema.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokensByCIDs indicates an expected call of GetTokensByCIDs.
func (mr *MockStoreMockRecorder) GetTokensByCIDs(ctx, tokenCIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokensByCIDs", reflect.TypeOf((*MockStore)(nil).GetTokensByCIDs), ctx, tokenCIDs)
}

// GetTokensByFilter mocks base method.
func (m *MockStore) GetTokensByFilter(ctx context.Context, filter store.TokenQueryFilter) ([]schema.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokensByFilter", ctx, filter)
	ret0, _ := ret[0].([]schema.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokensByFilter indicates an expected call of GetTokensByFilter.
func (mr *MockStoreMockRecorder) GetTokensByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokensByFilter", reflect.TypeOf((*MockStore)(nil).GetTokensByFilter), ctx, filter)
}

// GetTokensByIDs mocks base method.
func (m *MockStore) GetTokensByIDs(ctx context.Context, tokenIDs []uint64) ([]*schema.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokensByIDs", ctx, tokenIDs)
	ret0, _ := ret[0].([]*schema.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokensByIDs indicates an expected call of GetTokensByIDs.
func (mr *MockStoreMockRecorder) GetTokensByIDs(ctx, tokenIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokensByIDs", reflect.TypeOf((*MockStore)(nil).GetTokensByIDs), ctx, tokenIDs)
}

// GetTokensViewabilityByIDs mocks base method.
func (m *MockStore) GetTokensViewabilityByIDs(ctx context.Context, tokenIDs []uint64) ([]store.TokenViewabilityInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokensViewabilityByIDs", ctx, tokenIDs)
	ret0, _ := ret[0].([]store.TokenViewabilityInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokensViewabilityByIDs indicates an expected call of GetTokensViewabilityByIDs.
func (mr *MockStoreMockRecorder) GetTokensViewabilityByIDs(ctx, tokenIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokensViewabilityByIDs", reflect.TypeOf((*MockStore)(nil).GetTokensViewabilityByIDs), ctx, tokenIDs)
}

// GetURLsForChecking mocks base method.
func (m *MockStore) GetURLsForChecking(ctx context.Context, recheckAfter time.Duration, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLsForChecking", ctx, recheckAfter, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLsForChecking indicates an expected call of GetURLsForChecking.
func (mr *MockStoreMockRecorder) GetURLsForChecking(ctx, recheckAfter, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLsForChecking", reflect.TypeOf((*MockStore)(nil).GetURLsForChecking), ctx, recheckAfter, limit)
}

// GetWebhookClientByID mocks base method.
func (m *MockStore) GetWebhookClientByID(ctx context.Context, clientID string) (*schema.WebhookClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookClientByID", ctx, clientID)
	ret0, _ := ret[0].(*schema.WebhookClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookClientByID indicates an expected call of GetWebhookClientByID.
func (mr *MockStoreMockRecorder) GetWebhookClientByID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookClientByID", reflect.TypeOf((*MockStore)(nil).GetWebhookClientByID), ctx, clientID)
}

// IncrementTokensIndexed mocks base method.
func (m *MockStore) IncrementTokensIndexed(ctx context.Context, address string, chain domain.Chain, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementTokensIndexed", ctx, address, chain, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementTokensIndexed indicates an expected call of IncrementTokensIndexed.
func (mr *MockStoreMockRecorder) IncrementTokensIndexed(ctx, address, chain, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTokensIndexed", reflect.TypeOf((*MockStore)(nil).IncrementTokensIndexed), ctx, address, chain, count)
}

// IsAnyAddressWatched mocks base method.
func (m *MockStore) IsAnyAddressWatched(ctx context.Context, chain domain.Chain, addresses []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAnyAddressWatched", ctx, chain, addresses)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAnyAddressWatched indicates an expected call of IsAnyAddressWatched.
func (mr *MockStoreMockRecorder) IsAnyAddressWatched(ctx, chain, addresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAnyAddressWatched", reflect.TypeOf((*MockStore)(nil).IsAnyAddressWatched), ctx, chain, addresses)
}

// ListInFlightJobsWithCancelRequest mocks base method.
func (m *MockStore) ListInFlightJobsWithCancelRequest(ctx context.Context, queue string, ids []int64) ([]*schema.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInFlightJobsWithCancelRequest", ctx, queue, ids)
	ret0, _ := ret[0].([]*schema.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInFlightJobsWithCancelRequest indicates an expected call of ListInFlightJobsWithCancelRequest.
func (mr *MockStoreMockRecorder) ListInFlightJobsWithCancelRequest(ctx, queue, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInFlightJobsWithCancelRequest", reflect.TypeOf((*MockStore)(nil).ListInFlightJobsWithCancelRequest), ctx, queue, ids)
}

// ListReleases mocks base method.
func (m *MockStore) ListReleases(ctx context.Context, filter store.ReleaseQueryFilter) ([]schema.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReleases", ctx, filter)
	ret0, _ := ret[0].([]schema.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReleases indicates an expected call of ListReleases.
func (mr *MockStoreMockRecorder) ListReleases(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReleases", reflect.TypeOf((*MockStore)(nil).ListReleases), ctx, filter)
}

// MarkJobCanceled mocks base method.
func (m *MockStore) MarkJobCanceled(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkJobCanceled", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkJobCanceled indicates an expected call of MarkJobCanceled.
func (mr *MockStoreMockRecorder) MarkJobCanceled(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkJobCanceled", reflect.TypeOf((*MockStore)(nil).MarkJobCanceled), ctx, id)
}

// MarkJobFailed mocks base method.
func (m *MockStore) MarkJobFailed(ctx context.Context, id int64, lastErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkJobFailed", ctx, id, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkJobFailed indicates an expected call of MarkJobFailed.
func (mr *MockStoreMockRecorder) MarkJobFailed(ctx, id, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkJobFailed", reflect.TypeOf((*MockStore)(nil).MarkJobFailed), ctx, id, lastErr)
}

// MarkJobSucceeded mocks base method.
func (m *MockStore) MarkJobSucceeded(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkJobSucceeded", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkJobSucceeded indicates an expected call of MarkJobSucceeded.
func (mr *MockStoreMockRecorder) MarkJobSucceeded(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkJobSucceeded", reflect.TypeOf((*MockStore)(nil).MarkJobSucceeded), ctx, id)
}

// RequestJobCancel mocks base method.
func (m *MockStore) RequestJobCancel(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestJobCancel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestJobCancel indicates an expected call of RequestJobCancel.
func (mr *MockStoreMockRecorder) RequestJobCancel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestJobCancel", reflect.TypeOf((*MockStore)(nil).RequestJobCancel), ctx, id)
}

// RescheduleJob mocks base method.
func (m *MockStore) RescheduleJob(ctx context.Context, id int64, runAfter time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RescheduleJob", ctx, id, runAfter)
	ret0, _ := ret[0].(error)
	return ret0
}

// RescheduleJob indicates an expected call of RescheduleJob.
func (mr *MockStoreMockRecorder) RescheduleJob(ctx, id, runAfter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RescheduleJob", reflect.TypeOf((*MockStore)(nil).RescheduleJob), ctx, id, runAfter)
}

// SetBlockCursor mocks base method.
func (m *MockStore) SetBlockCursor(ctx context.Context, chain string, blockNumber uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlockCursor", ctx, chain, blockNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlockCursor indicates an expected call of SetBlockCursor.
func (mr *MockStoreMockRecorder) SetBlockCursor(ctx, chain, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockCursor", reflect.TypeOf((*MockStore)(nil).SetBlockCursor), ctx, chain, blockNumber)
}

// SetKeyValue mocks base method.
func (m *MockStore) SetKeyValue(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKeyValue", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKeyValue indicates an expected call of SetKeyValue.
func (mr *MockStoreMockRecorder) SetKeyValue(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeyValue", reflect.TypeOf((*MockStore)(nil).SetKeyValue), ctx, key, value)
}

// SweepCanceledPendingJobs mocks base method.
func (m *MockStore) SweepCanceledPendingJobs(ctx context.Context, queue string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepCanceledPendingJobs", ctx, queue)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepCanceledPendingJobs indicates an expected call of SweepCanceledPendingJobs.
func (mr *MockStoreMockRecorder) SweepCanceledPendingJobs(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepCanceledPendingJobs", reflect.TypeOf((*MockStore)(nil).SweepCanceledPendingJobs), ctx, queue)
}

// SweepOrphanedJobs mocks base method.
func (m *MockStore) SweepOrphanedJobs(ctx context.Context, queue string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepOrphanedJobs", ctx, queue)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepOrphanedJobs indicates an expected call of SweepOrphanedJobs.
func (mr *MockStoreMockRecorder) SweepOrphanedJobs(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepOrphanedJobs", reflect.TypeOf((*MockStore)(nil).SweepOrphanedJobs), ctx, queue)
}

// UpdateAddressIndexingJobProgress mocks base method.
func (m *MockStore) UpdateAddressIndexingJobProgress(ctx context.Context, jobID int64, tokensProcessed int, minBlock, maxBlock uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddressIndexingJobProgress", ctx, jobID, tokensProcessed, minBlock, maxBlock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddressIndexingJobProgress indicates an expected call of UpdateAddressIndexingJobProgress.
func (mr *MockStoreMockRecorder) UpdateAddressIndexingJobProgress(ctx, jobID, tokensProcessed, minBlock, maxBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddressIndexingJobProgress", reflect.TypeOf((*MockStore)(nil).UpdateAddressIndexingJobProgress), ctx, jobID, tokensProcessed, minBlock, maxBlock)
}

// UpdateAddressIndexingJobStatus mocks base method.
func (m *MockStore) UpdateAddressIndexingJobStatus(ctx context.Context, jobID int64, status schema.IndexingJobStatus, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddressIndexingJobStatus", ctx, jobID, status, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddressIndexingJobStatus indicates an expected call of UpdateAddressIndexingJobStatus.
func (mr *MockStoreMockRecorder) UpdateAddressIndexingJobStatus(ctx, jobID, status, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddressIndexingJobStatus", reflect.TypeOf((*MockStore)(nil).UpdateAddressIndexingJobStatus), ctx, jobID, status, timestamp)
}

// UpdateIndexingBlockRangeForAddress mocks base method.
func (m *MockStore) UpdateIndexingBlockRangeForAddress(ctx context.Context, address string, chainID domain.Chain, minBlock, maxBlock uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIndexingBlockRangeForAddress", ctx, address, chainID, minBlock, maxBlock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIndexingBlockRangeForAddress indicates an expected call of UpdateIndexingBlockRangeForAddress.
func (mr *MockStoreMockRecorder) UpdateIndexingBlockRangeForAddress(ctx, address, chainID, minBlock, maxBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndexingBlockRangeForAddress", reflect.TypeOf((*MockStore)(nil).UpdateIndexingBlockRangeForAddress), ctx, address, chainID, minBlock, maxBlock)
}

// UpdateMediaURLAndPropagate mocks base method.
func (m *MockStore) UpdateMediaURLAndPropagate(ctx context.Context, oldURL, newURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMediaURLAndPropagate", ctx, oldURL, newURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMediaURLAndPropagate indicates an expected call of UpdateMediaURLAndPropagate.
func (mr *MockStoreMockRecorder) UpdateMediaURLAndPropagate(ctx, oldURL, newURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMediaURLAndPropagate", reflect.TypeOf((*MockStore)(nil).UpdateMediaURLAndPropagate), ctx, oldURL, newURL)
}

// UpdateTokenBurn mocks base method.
func (m *MockStore) UpdateTokenBurn(ctx context.Context, input store.CreateTokenBurnInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenBurn", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenBurn indicates an expected call of UpdateTokenBurn.
func (mr *MockStoreMockRecorder) UpdateTokenBurn(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenBurn", reflect.TypeOf((*MockStore)(nil).UpdateTokenBurn), ctx, input)
}

// UpdateTokenMediaHealthByURL mocks base method.
func (m *MockStore) UpdateTokenMediaHealthByURL(ctx context.Context, url string, status schema.MediaHealthStatus, lastError *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenMediaHealthByURL", ctx, url, status, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenMediaHealthByURL indicates an expected call of UpdateTokenMediaHealthByURL.
func (mr *MockStoreMockRecorder) UpdateTokenMediaHealthByURL(ctx, url, status, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenMediaHealthByURL", reflect.TypeOf((*MockStore)(nil).UpdateTokenMediaHealthByURL), ctx, url, status, lastError)
}

// UpdateTokenTransfer mocks base method.
func (m *MockStore) UpdateTokenTransfer(ctx context.Context, input store.UpdateTokenTransferInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenTransfer", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenTransfer indicates an expected call of UpdateTokenTransfer.
func (mr *MockStoreMockRecorder) UpdateTokenTransfer(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenTransfer", reflect.TypeOf((*MockStore)(nil).UpdateTokenTransfer), ctx, input)
}

// UpdateWebhookDeliveryStatus mocks base method.
func (m *MockStore) UpdateWebhookDeliveryStatus(ctx context.Context, deliveryID uint64, status schema.WebhookDeliveryStatus, attempts int, responseStatus *int, responseBody, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhookDeliveryStatus", ctx, deliveryID, status, attempts, responseStatus, responseBody, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWebhookDeliveryStatus indicates an expected call of UpdateWebhookDeliveryStatus.
func (mr *MockStoreMockRecorder) UpdateWebhookDeliveryStatus(ctx, deliveryID, status, attempts, responseStatus, responseBody, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhookDeliveryStatus", reflect.TypeOf((*MockStore)(nil).UpdateWebhookDeliveryStatus), ctx, deliveryID, status, attempts, responseStatus, responseBody, errorMessage)
}

// UpsertEnrichmentSource mocks base method.
func (m *MockStore) UpsertEnrichmentSource(ctx context.Context, input store.CreateEnrichmentSourceInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEnrichmentSource", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEnrichmentSource indicates an expected call of UpsertEnrichmentSource.
func (mr *MockStoreMockRecorder) UpsertEnrichmentSource(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEnrichmentSource", reflect.TypeOf((*MockStore)(nil).UpsertEnrichmentSource), ctx, input)
}

// UpsertRelease mocks base method.
func (m *MockStore) UpsertRelease(ctx context.Context, vendor schema.Vendor, vendorReleaseID string, name *string, totalMints *int64) (*schema.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRelease", ctx, vendor, vendorReleaseID, name, totalMints)
	ret0, _ := ret[0].(*schema.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRelease indicates an expected call of UpsertRelease.
func (mr *MockStoreMockRecorder) UpsertRelease(ctx, vendor, vendorReleaseID, name, totalMints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRelease", reflect.TypeOf((*MockStore)(nil).UpsertRelease), ctx, vendor, vendorReleaseID, name, totalMints)
}

// UpsertReleaseMember mocks base method.
func (m *MockStore) UpsertReleaseMember(ctx context.Context, releaseID, tokenID uint64, mintNumber int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertReleaseMember", ctx, releaseID, tokenID, mintNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertReleaseMember indicates an expected call of UpsertReleaseMember.
func (mr *MockStoreMockRecorder) UpsertReleaseMember(ctx, releaseID, tokenID, mintNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertReleaseMember", reflect.TypeOf((*MockStore)(nil).UpsertReleaseMember), ctx, releaseID, tokenID, mintNumber)
}

// UpsertTokenBalanceForOwner mocks base method.
func (m *MockStore) UpsertTokenBalanceForOwner(ctx context.Context, input store.UpsertTokenBalanceForOwnerInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTokenBalanceForOwner", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTokenBalanceForOwner indicates an expected call of UpsertTokenBalanceForOwner.
func (mr *MockStoreMockRecorder) UpsertTokenBalanceForOwner(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTokenBalanceForOwner", reflect.TypeOf((*MockStore)(nil).UpsertTokenBalanceForOwner), ctx, input)
}

// UpsertTokenMetadata mocks base method.
func (m *MockStore) UpsertTokenMetadata(ctx context.Context, input store.CreateTokenMetadataInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTokenMetadata", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTokenMetadata indicates an expected call of UpsertTokenMetadata.
func (mr *MockStoreMockRecorder) UpsertTokenMetadata(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTokenMetadata", reflect.TypeOf((*MockStore)(nil).UpsertTokenMetadata), ctx, input)
}
