// Code generated by MockGen. DO NOT EDIT.
// Source: sweeper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSweeper is a mock of Sweeper interface.
type MockSweeper struct {
	ctrl     *gomock.Controller
	recorder *MockSweeperMockRecorder
}

// MockSweeperMockRecorder is the mock recorder for MockSweeper.
type MockSweeperMockRecorder struct {
	mock *MockSweeper
}

// NewMockSweeper creates a new mock instance.
func NewMockSweeper(ctrl *gomock.Controller) *MockSweeper {
	mock := &MockSweeper{ctrl: ctrl}
	mock.recorder = &MockSweeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSweeper) EXPECT() *MockSweeperMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockSweeper) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSweeperMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSweeper)(nil).Name))
}

// Start mocks base method.
func (m *MockSweeper) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockSweeperMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSweeper)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockSweeper) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSweeperMockRecorder) Stop(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSweeper)(nil).Stop), ctx)
}
