// Code generated by MockGen. DO NOT EDIT.
// Source: temporal.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	activity "go.temporal.io/sdk/activity"
)

// MockActivity is a mock of Activity interface.
type MockActivity struct {
	ctrl     *gomock.Controller
	recorder *MockActivityMockRecorder
}

// MockActivityMockRecorder is the mock recorder for MockActivity.
type MockActivityMockRecorder struct {
	mock *MockActivity
}

// NewMockActivity creates a new mock instance.
func NewMockActivity(ctrl *gomock.Controller) *MockActivity {
	mock := &MockActivity{ctrl: ctrl}
	mock.recorder = &MockActivityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivity) EXPECT() *MockActivityMockRecorder {
	return m.recorder
}

// GetInfo mocks base method.
func (m *MockActivity) GetInfo(ctx context.Context) activity.Info {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", ctx)
	ret0, _ := ret[0].(activity.Info)
	return ret0
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockActivityMockRecorder) GetInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockActivity)(nil).GetInfo), ctx)
}
