// Code generated by MockGen. DO NOT EDIT.
// Source: orchestrator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	client "go.temporal.io/sdk/client"
)

// MockTemporalOrchestrator is a mock of TemporalOrchestrator interface.
type MockTemporalOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockTemporalOrchestratorMockRecorder
}

// MockTemporalOrchestratorMockRecorder is the mock recorder for MockTemporalOrchestrator.
type MockTemporalOrchestratorMockRecorder struct {
	mock *MockTemporalOrchestrator
}

// NewMockTemporalOrchestrator creates a new mock instance.
func NewMockTemporalOrchestrator(ctrl *gomock.Controller) *MockTemporalOrchestrator {
	mock := &MockTemporalOrchestrator{ctrl: ctrl}
	mock.recorder = &MockTemporalOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemporalOrchestrator) EXPECT() *MockTemporalOrchestratorMockRecorder {
	return m.recorder
}

// DescribeWorkflowExecution mocks base method.
func (m *MockTemporalOrchestrator) DescribeWorkflowExecution(ctx context.Context, workflowID, runID string) (*workflowservice.DescribeWorkflowExecutionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeWorkflowExecution", ctx, workflowID, runID)
	ret0, _ := ret[0].(*workflowservice.DescribeWorkflowExecutionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeWorkflowExecution indicates an expected call of DescribeWorkflowExecution.
func (mr *MockTemporalOrchestratorMockRecorder) DescribeWorkflowExecution(ctx, workflowID, runID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeWorkflowExecution", reflect.TypeOf((*MockTemporalOrchestrator)(nil).DescribeWorkflowExecution), ctx, workflowID, runID)
}

// ExecuteWorkflow mocks base method.
func (m *MockTemporalOrchestrator) ExecuteWorkflow(ctx context.Context, options client.StartWorkflowOptions, workflow interface{}, args ...interface{}) (client.WorkflowRun, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, options, workflow}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteWorkflow", varargs...)
	ret0, _ := ret[0].(client.WorkflowRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWorkflow indicates an expected call of ExecuteWorkflow.
func (mr *MockTemporalOrchestratorMockRecorder) ExecuteWorkflow(ctx, options, workflow interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, options, workflow}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWorkflow", reflect.TypeOf((*MockTemporalOrchestrator)(nil).ExecuteWorkflow), varargs...)
}
