// Code generated by MockGen. DO NOT EDIT.
// Source: tzkt_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tezos "github.com/feral-file/ff-indexer-v2/internal/providers/tezos"
	gomock "github.com/golang/mock/gomock"
)

// MockTzKTClient is a mock of TzKTClient interface.
type MockTzKTClient struct {
	ctrl     *gomock.Controller
	recorder *MockTzKTClientMockRecorder
}

// MockTzKTClientMockRecorder is the mock recorder for MockTzKTClient.
type MockTzKTClientMockRecorder struct {
	mock *MockTzKTClient
}

// NewMockTzKTClient creates a new mock instance.
func NewMockTzKTClient(ctrl *gomock.Controller) *MockTzKTClient {
	mock := &MockTzKTClient{ctrl: ctrl}
	mock.recorder = &MockTzKTClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTzKTClient) EXPECT() *MockTzKTClientMockRecorder {
	return m.recorder
}

// GetTransactionByID mocks base method.
func (m *MockTzKTClient) GetTransactionByID(ctx context.Context, txID uint64) (*tezos.TzKTTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", ctx, txID)
	ret0, _ := ret[0].(*tezos.TzKTTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockTzKTClientMockRecorder) GetTransactionByID(ctx, txID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockTzKTClient)(nil).GetTransactionByID), ctx, txID)
}
