// Code generated by MockGen. DO NOT EDIT.
// Source: tzkt_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
	tezos "github.com/feral-file/ff-indexer-v2/internal/providers/tezos"
)

// MockTzKTClient is a mock of TzKTClient interface.
type MockTzKTClient struct {
	ctrl     *gomock.Controller
	recorder *MockTzKTClientMockRecorder
}

// MockTzKTClientMockRecorder is the mock recorder for MockTzKTClient.
type MockTzKTClientMockRecorder struct {
	mock *MockTzKTClient
}

// NewMockTzKTClient creates a new mock instance.
func NewMockTzKTClient(ctrl *gomock.Controller) *MockTzKTClient {
	mock := &MockTzKTClient{ctrl: ctrl}
	mock.recorder = &MockTzKTClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTzKTClient) EXPECT() *MockTzKTClientMockRecorder {
	return m.recorder
}

// ChainID mocks base method.
func (m *MockTzKTClient) ChainID() domain.Chain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID")
	ret0, _ := ret[0].(domain.Chain)
	return ret0
}

// ChainID indicates an expected call of ChainID.
func (mr *MockTzKTClientMockRecorder) ChainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockTzKTClient)(nil).ChainID))
}

// GetContractDeployer mocks base method.
func (m *MockTzKTClient) GetContractDeployer(ctx context.Context, contractAddress string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractDeployer", ctx, contractAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractDeployer indicates an expected call of GetContractDeployer.
func (mr *MockTzKTClientMockRecorder) GetContractDeployer(ctx, contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractDeployer", reflect.TypeOf((*MockTzKTClient)(nil).GetContractDeployer), ctx, contractAddress)
}

// GetLatestBlock mocks base method.
func (m *MockTzKTClient) GetLatestBlock(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlock", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlock indicates an expected call of GetLatestBlock.
func (mr *MockTzKTClientMockRecorder) GetLatestBlock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlock", reflect.TypeOf((*MockTzKTClient)(nil).GetLatestBlock), ctx)
}

// GetTokenBalances mocks base method.
func (m *MockTzKTClient) GetTokenBalances(ctx context.Context, contractAddress, tokenID string) ([]tezos.TzKTTokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenBalances", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].([]tezos.TzKTTokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenBalances indicates an expected call of GetTokenBalances.
func (mr *MockTzKTClientMockRecorder) GetTokenBalances(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenBalances", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenBalances), ctx, contractAddress, tokenID)
}

// GetTokenBalancesByAccountWithinBlockRange mocks base method.
func (m *MockTzKTClient) GetTokenBalancesByAccountWithinBlockRange(ctx context.Context, accountAddress string, fromBlock, toBlock uint64, limit, offset int) ([]tezos.TzKTTokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenBalancesByAccountWithinBlockRange", ctx, accountAddress, fromBlock, toBlock, limit, offset)
	ret0, _ := ret[0].([]tezos.TzKTTokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenBalancesByAccountWithinBlockRange indicates an expected call of GetTokenBalancesByAccountWithinBlockRange.
func (mr *MockTzKTClientMockRecorder) GetTokenBalancesByAccountWithinBlockRange(ctx, accountAddress, fromBlock, toBlock, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenBalancesByAccountWithinBlockRange", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenBalancesByAccountWithinBlockRange), ctx, accountAddress, fromBlock, toBlock, limit, offset)
}

// GetTokenEvents mocks base method.
func (m *MockTzKTClient) GetTokenEvents(ctx context.Context, contractAddress, tokenID string) ([]domain.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenEvents", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].([]domain.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenEvents indicates an expected call of GetTokenEvents.
func (mr *MockTzKTClientMockRecorder) GetTokenEvents(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenEvents", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenEvents), ctx, contractAddress, tokenID)
}

// GetTokenMetadata mocks base method.
func (m *MockTzKTClient) GetTokenMetadata(ctx context.Context, contractAddress, tokenID string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMetadata", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMetadata indicates an expected call of GetTokenMetadata.
func (mr *MockTzKTClientMockRecorder) GetTokenMetadata(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMetadata", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenMetadata), ctx, contractAddress, tokenID)
}

// GetTokenMetadataUpdates mocks base method.
func (m *MockTzKTClient) GetTokenMetadataUpdates(ctx context.Context, contractAddress, tokenID string) ([]tezos.TzKTBigMapUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMetadataUpdates", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].([]tezos.TzKTBigMapUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMetadataUpdates indicates an expected call of GetTokenMetadataUpdates.
func (mr *MockTzKTClientMockRecorder) GetTokenMetadataUpdates(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMetadataUpdates", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenMetadataUpdates), ctx, contractAddress, tokenID)
}

// GetTokenOwnerBalance mocks base method.
func (m *MockTzKTClient) GetTokenOwnerBalance(ctx context.Context, contractAddress, tokenID, ownerAddress string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenOwnerBalance", ctx, contractAddress, tokenID, ownerAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenOwnerBalance indicates an expected call of GetTokenOwnerBalance.
func (mr *MockTzKTClientMockRecorder) GetTokenOwnerBalance(ctx, contractAddress, tokenID, ownerAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenOwnerBalance", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenOwnerBalance), ctx, contractAddress, tokenID, ownerAddress)
}

// GetTokenTransfers mocks base method.
func (m *MockTzKTClient) GetTokenTransfers(ctx context.Context, contractAddress, tokenID string) ([]tezos.TzKTTokenTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenTransfers", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].([]tezos.TzKTTokenTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenTransfers indicates an expected call of GetTokenTransfers.
func (mr *MockTzKTClientMockRecorder) GetTokenTransfers(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenTransfers", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenTransfers), ctx, contractAddress, tokenID)
}

// GetTransactionsByID mocks base method.
func (m *MockTzKTClient) GetTransactionsByID(ctx context.Context, txID uint64) ([]tezos.TzKTTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByID", ctx, txID)
	ret0, _ := ret[0].([]tezos.TzKTTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByID indicates an expected call of GetTransactionsByID.
func (mr *MockTzKTClientMockRecorder) GetTransactionsByID(ctx, txID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByID", reflect.TypeOf((*MockTzKTClient)(nil).GetTransactionsByID), ctx, txID)
}

// ParseBigMapUpdate mocks base method.
func (m *MockTzKTClient) ParseBigMapUpdate(ctx context.Context, update *tezos.TzKTBigMapUpdate) (*domain.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBigMapUpdate", ctx, update)
	ret0, _ := ret[0].(*domain.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseBigMapUpdate indicates an expected call of ParseBigMapUpdate.
func (mr *MockTzKTClientMockRecorder) ParseBigMapUpdate(ctx, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBigMapUpdate", reflect.TypeOf((*MockTzKTClient)(nil).ParseBigMapUpdate), ctx, update)
}

// ParseTransfer mocks base method.
func (m *MockTzKTClient) ParseTransfer(ctx context.Context, transfer *tezos.TzKTTokenTransfer) (*domain.BlockchainEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTransfer", ctx, transfer)
	ret0, _ := ret[0].(*domain.BlockchainEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTransfer indicates an expected call of ParseTransfer.
func (mr *MockTzKTClientMockRecorder) ParseTransfer(ctx, transfer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTransfer", reflect.TypeOf((*MockTzKTClient)(nil).ParseTransfer), ctx, transfer)
}
