// Code generated by MockGen. DO NOT EDIT.
// Source: tzkt_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	tezos "github.com/feral-file/ff-indexer-v2/internal/providers/tezos"
)

// MockTzKTClient is a mock of TzKTClient interface.
type MockTzKTClient struct {
	ctrl     *gomock.Controller
	recorder *MockTzKTClientMockRecorder
}

// MockTzKTClientMockRecorder is the mock recorder for MockTzKTClient.
type MockTzKTClientMockRecorder struct {
	mock *MockTzKTClient
}

// NewMockTzKTClient creates a new mock instance.
func NewMockTzKTClient(ctrl *gomock.Controller) *MockTzKTClient {
	mock := &MockTzKTClient{ctrl: ctrl}
	mock.recorder = &MockTzKTClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTzKTClient) EXPECT() *MockTzKTClientMockRecorder {
	return m.recorder
}

// GetTokenBalances mocks base method.
func (m *MockTzKTClient) GetTokenBalances(ctx context.Context, contractAddress, tokenID string) ([]tezos.TzKTTokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenBalances", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].([]tezos.TzKTTokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenBalances indicates an expected call of GetTokenBalances.
func (mr *MockTzKTClientMockRecorder) GetTokenBalances(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenBalances", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenBalances), ctx, contractAddress, tokenID)
}

// GetTokenMetadata mocks base method.
func (m *MockTzKTClient) GetTokenMetadata(ctx context.Context, contractAddress, tokenID string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenMetadata", ctx, contractAddress, tokenID)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenMetadata indicates an expected call of GetTokenMetadata.
func (mr *MockTzKTClientMockRecorder) GetTokenMetadata(ctx, contractAddress, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenMetadata", reflect.TypeOf((*MockTzKTClient)(nil).GetTokenMetadata), ctx, contractAddress, tokenID)
}

// GetTransactionsByID mocks base method.
func (m *MockTzKTClient) GetTransactionsByID(ctx context.Context, txID uint64) ([]tezos.TzKTTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByID", ctx, txID)
	ret0, _ := ret[0].([]tezos.TzKTTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByID indicates an expected call of GetTransactionsByID.
func (mr *MockTzKTClientMockRecorder) GetTransactionsByID(ctx, txID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByID", reflect.TypeOf((*MockTzKTClient)(nil).GetTransactionsByID), ctx, txID)
}
