// Code generated by MockGen. DO NOT EDIT.
// Source: url_checker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	uri "github.com/feral-file/ff-indexer-v2/internal/uri"
)

// MockURLChecker is a mock of URLChecker interface.
type MockURLChecker struct {
	ctrl     *gomock.Controller
	recorder *MockURLCheckerMockRecorder
}

// MockURLCheckerMockRecorder is the mock recorder for MockURLChecker.
type MockURLCheckerMockRecorder struct {
	mock *MockURLChecker
}

// NewMockURLChecker creates a new mock instance.
func NewMockURLChecker(ctrl *gomock.Controller) *MockURLChecker {
	mock := &MockURLChecker{ctrl: ctrl}
	mock.recorder = &MockURLCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLChecker) EXPECT() *MockURLCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockURLChecker) Check(ctx context.Context, url string) uri.HealthCheckResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, url)
	ret0, _ := ret[0].(uri.HealthCheckResult)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockURLCheckerMockRecorder) Check(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockURLChecker)(nil).Check), ctx, url)
}
