//go:build cgo

// Code generated by MockGen. DO NOT EDIT.
// Source: vips.go

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	vips "github.com/cshum/vipsgen/vips"
	gomock "github.com/golang/mock/gomock"

	adapter "github.com/feral-file/ff-indexer-v2/internal/adapter"
)

// MockVipsImage is a mock of VipsImage interface.
type MockVipsImage struct {
	ctrl     *gomock.Controller
	recorder *MockVipsImageMockRecorder
}

// MockVipsImageMockRecorder is the mock recorder for MockVipsImage.
type MockVipsImageMockRecorder struct {
	mock *MockVipsImage
}

// NewMockVipsImage creates a new mock instance.
func NewMockVipsImage(ctrl *gomock.Controller) *MockVipsImage {
	mock := &MockVipsImage{ctrl: ctrl}
	mock.recorder = &MockVipsImageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVipsImage) EXPECT() *MockVipsImageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockVipsImage) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockVipsImageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockVipsImage)(nil).Close))
}

// HasAlpha mocks base method.
func (m *MockVipsImage) HasAlpha() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAlpha")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasAlpha indicates an expected call of HasAlpha.
func (mr *MockVipsImageMockRecorder) HasAlpha() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAlpha", reflect.TypeOf((*MockVipsImage)(nil).HasAlpha))
}

// Height mocks base method.
func (m *MockVipsImage) Height() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Height")
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height.
func (mr *MockVipsImageMockRecorder) Height() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Height", reflect.TypeOf((*MockVipsImage)(nil).Height))
}

// JpegsaveBuffer mocks base method.
func (m *MockVipsImage) JpegsaveBuffer(options *vips.JpegsaveBufferOptions) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JpegsaveBuffer", options)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JpegsaveBuffer indicates an expected call of JpegsaveBuffer.
func (mr *MockVipsImageMockRecorder) JpegsaveBuffer(options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JpegsaveBuffer", reflect.TypeOf((*MockVipsImage)(nil).JpegsaveBuffer), options)
}

// PageHeight mocks base method.
func (m *MockVipsImage) PageHeight() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PageHeight")
	ret0, _ := ret[0].(int)
	return ret0
}

// PageHeight indicates an expected call of PageHeight.
func (mr *MockVipsImageMockRecorder) PageHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PageHeight", reflect.TypeOf((*MockVipsImage)(nil).PageHeight))
}

// Pages mocks base method.
func (m *MockVipsImage) Pages() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pages")
	ret0, _ := ret[0].(int)
	return ret0
}

// Pages indicates an expected call of Pages.
func (mr *MockVipsImageMockRecorder) Pages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pages", reflect.TypeOf((*MockVipsImage)(nil).Pages))
}

// Resize mocks base method.
func (m *MockVipsImage) Resize(scale float64, options *vips.ResizeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", scale, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resize indicates an expected call of Resize.
func (mr *MockVipsImageMockRecorder) Resize(scale, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockVipsImage)(nil).Resize), scale, options)
}

// SetPageHeight mocks base method.
func (m *MockVipsImage) SetPageHeight(height int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPageHeight", height)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPageHeight indicates an expected call of SetPageHeight.
func (mr *MockVipsImageMockRecorder) SetPageHeight(height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPageHeight", reflect.TypeOf((*MockVipsImage)(nil).SetPageHeight), height)
}

// WebpsaveBuffer mocks base method.
func (m *MockVipsImage) WebpsaveBuffer(options *vips.WebpsaveBufferOptions) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebpsaveBuffer", options)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WebpsaveBuffer indicates an expected call of WebpsaveBuffer.
func (mr *MockVipsImageMockRecorder) WebpsaveBuffer(options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebpsaveBuffer", reflect.TypeOf((*MockVipsImage)(nil).WebpsaveBuffer), options)
}

// Width mocks base method.
func (m *MockVipsImage) Width() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Width")
	ret0, _ := ret[0].(int)
	return ret0
}

// Width indicates an expected call of Width.
func (mr *MockVipsImageMockRecorder) Width() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Width", reflect.TypeOf((*MockVipsImage)(nil).Width))
}

// MockVipsSource is a mock of VipsSource interface.
type MockVipsSource struct {
	ctrl     *gomock.Controller
	recorder *MockVipsSourceMockRecorder
}

// MockVipsSourceMockRecorder is the mock recorder for MockVipsSource.
type MockVipsSourceMockRecorder struct {
	mock *MockVipsSource
}

// NewMockVipsSource creates a new mock instance.
func NewMockVipsSource(ctrl *gomock.Controller) *MockVipsSource {
	mock := &MockVipsSource{ctrl: ctrl}
	mock.recorder = &MockVipsSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVipsSource) EXPECT() *MockVipsSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockVipsSource) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockVipsSourceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockVipsSource)(nil).Close))
}

// MockVipsClient is a mock of VipsClient interface.
type MockVipsClient struct {
	ctrl     *gomock.Controller
	recorder *MockVipsClientMockRecorder
}

// MockVipsClientMockRecorder is the mock recorder for MockVipsClient.
type MockVipsClientMockRecorder struct {
	mock *MockVipsClient
}

// NewMockVipsClient creates a new mock instance.
func NewMockVipsClient(ctrl *gomock.Controller) *MockVipsClient {
	mock := &MockVipsClient{ctrl: ctrl}
	mock.recorder = &MockVipsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVipsClient) EXPECT() *MockVipsClientMockRecorder {
	return m.recorder
}

// NewImageFromSource mocks base method.
func (m *MockVipsClient) NewImageFromSource(source adapter.VipsSource, options *vips.LoadOptions) (adapter.VipsImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewImageFromSource", source, options)
	ret0, _ := ret[0].(adapter.VipsImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewImageFromSource indicates an expected call of NewImageFromSource.
func (mr *MockVipsClientMockRecorder) NewImageFromSource(source, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewImageFromSource", reflect.TypeOf((*MockVipsClient)(nil).NewImageFromSource), source, options)
}

// NewSource mocks base method.
func (m *MockVipsClient) NewSource(reader io.ReadCloser) adapter.VipsSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSource", reader)
	ret0, _ := ret[0].(adapter.VipsSource)
	return ret0
}

// NewSource indicates an expected call of NewSource.
func (mr *MockVipsClientMockRecorder) NewSource(reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSource", reflect.TypeOf((*MockVipsClient)(nil).NewSource), reader)
}

// Shutdown mocks base method.
func (m *MockVipsClient) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockVipsClientMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockVipsClient)(nil).Shutdown))
}

// Startup mocks base method.
func (m *MockVipsClient) Startup(config *vips.Config) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Startup", config)
}

// Startup indicates an expected call of Startup.
func (mr *MockVipsClientMockRecorder) Startup(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Startup", reflect.TypeOf((*MockVipsClient)(nil).Startup), config)
}
