// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	workflow "go.temporal.io/sdk/workflow"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
)

// MockWorkerCore is a mock of WorkerCore interface.
type MockWorkerCore struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerCoreMockRecorder
}

// MockWorkerCoreMockRecorder is the mock recorder for MockWorkerCore.
type MockWorkerCoreMockRecorder struct {
	mock *MockWorkerCore
}

// NewMockWorkerCore creates a new mock instance.
func NewMockWorkerCore(ctrl *gomock.Controller) *MockWorkerCore {
	mock := &MockWorkerCore{ctrl: ctrl}
	mock.recorder = &MockWorkerCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerCore) EXPECT() *MockWorkerCoreMockRecorder {
	return m.recorder
}

// IndexEthereumTokenOwner mocks base method.
func (m *MockWorkerCore) IndexEthereumTokenOwner(ctx workflow.Context, address string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexEthereumTokenOwner", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexEthereumTokenOwner indicates an expected call of IndexEthereumTokenOwner.
func (mr *MockWorkerCoreMockRecorder) IndexEthereumTokenOwner(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexEthereumTokenOwner", reflect.TypeOf((*MockWorkerCore)(nil).IndexEthereumTokenOwner), ctx, address)
}

// IndexMetadataUpdate mocks base method.
func (m *MockWorkerCore) IndexMetadataUpdate(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMetadataUpdate", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMetadataUpdate indicates an expected call of IndexMetadataUpdate.
func (mr *MockWorkerCoreMockRecorder) IndexMetadataUpdate(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMetadataUpdate", reflect.TypeOf((*MockWorkerCore)(nil).IndexMetadataUpdate), ctx, event)
}

// IndexTezosTokenOwner mocks base method.
func (m *MockWorkerCore) IndexTezosTokenOwner(ctx workflow.Context, address string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTezosTokenOwner", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTezosTokenOwner indicates an expected call of IndexTezosTokenOwner.
func (mr *MockWorkerCoreMockRecorder) IndexTezosTokenOwner(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTezosTokenOwner", reflect.TypeOf((*MockWorkerCore)(nil).IndexTezosTokenOwner), ctx, address)
}

// IndexToken mocks base method.
func (m *MockWorkerCore) IndexToken(ctx workflow.Context, tokenCID domain.TokenCID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexToken", ctx, tokenCID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexToken indicates an expected call of IndexToken.
func (mr *MockWorkerCoreMockRecorder) IndexToken(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexToken", reflect.TypeOf((*MockWorkerCore)(nil).IndexToken), ctx, tokenCID)
}

// IndexTokenBurn mocks base method.
func (m *MockWorkerCore) IndexTokenBurn(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenBurn", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenBurn indicates an expected call of IndexTokenBurn.
func (mr *MockWorkerCoreMockRecorder) IndexTokenBurn(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenBurn", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenBurn), ctx, event)
}

// IndexTokenFromEvent mocks base method.
func (m *MockWorkerCore) IndexTokenFromEvent(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenFromEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenFromEvent indicates an expected call of IndexTokenFromEvent.
func (mr *MockWorkerCoreMockRecorder) IndexTokenFromEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenFromEvent", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenFromEvent), ctx, event)
}

// IndexTokenMetadata mocks base method.
func (m *MockWorkerCore) IndexTokenMetadata(ctx workflow.Context, tokenCID domain.TokenCID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenMetadata", ctx, tokenCID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenMetadata indicates an expected call of IndexTokenMetadata.
func (mr *MockWorkerCoreMockRecorder) IndexTokenMetadata(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenMetadata", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenMetadata), ctx, tokenCID)
}

// IndexTokenMint mocks base method.
func (m *MockWorkerCore) IndexTokenMint(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenMint", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenMint indicates an expected call of IndexTokenMint.
func (mr *MockWorkerCoreMockRecorder) IndexTokenMint(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenMint", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenMint), ctx, event)
}

// IndexTokenOwner mocks base method.
func (m *MockWorkerCore) IndexTokenOwner(ctx workflow.Context, address string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenOwner", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenOwner indicates an expected call of IndexTokenOwner.
func (mr *MockWorkerCoreMockRecorder) IndexTokenOwner(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenOwner", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenOwner), ctx, address)
}

// IndexTokenOwners mocks base method.
func (m *MockWorkerCore) IndexTokenOwners(ctx workflow.Context, addresses []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenOwners", ctx, addresses)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenOwners indicates an expected call of IndexTokenOwners.
func (mr *MockWorkerCoreMockRecorder) IndexTokenOwners(ctx, addresses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenOwners", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenOwners), ctx, addresses)
}

// IndexTokenProvenances mocks base method.
func (m *MockWorkerCore) IndexTokenProvenances(ctx workflow.Context, tokenCID domain.TokenCID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenProvenances", ctx, tokenCID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenProvenances indicates an expected call of IndexTokenProvenances.
func (mr *MockWorkerCoreMockRecorder) IndexTokenProvenances(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenProvenances", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenProvenances), ctx, tokenCID)
}

// IndexTokenTransfer mocks base method.
func (m *MockWorkerCore) IndexTokenTransfer(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenTransfer", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenTransfer indicates an expected call of IndexTokenTransfer.
func (mr *MockWorkerCoreMockRecorder) IndexTokenTransfer(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenTransfer", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenTransfer), ctx, event)
}

// IndexTokens mocks base method.
func (m *MockWorkerCore) IndexTokens(ctx workflow.Context, tokenCIDs []domain.TokenCID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokens", ctx, tokenCIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokens indicates an expected call of IndexTokens.
func (mr *MockWorkerCoreMockRecorder) IndexTokens(ctx, tokenCIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokens", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokens), ctx, tokenCIDs)
}

// MockWorkerMedia is a mock of WorkerMedia interface.
type MockWorkerMedia struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMediaMockRecorder
}

// MockWorkerMediaMockRecorder is the mock recorder for MockWorkerMedia.
type MockWorkerMediaMockRecorder struct {
	mock *MockWorkerMedia
}

// NewMockWorkerMedia creates a new mock instance.
func NewMockWorkerMedia(ctrl *gomock.Controller) *MockWorkerMedia {
	mock := &MockWorkerMedia{ctrl: ctrl}
	mock.recorder = &MockWorkerMediaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerMedia) EXPECT() *MockWorkerMediaMockRecorder {
	return m.recorder
}
