// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	workflow "go.temporal.io/sdk/workflow"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
)

// MockCoreWorker is a mock of WorkerCore interface.
type MockCoreWorker struct {
	ctrl     *gomock.Controller
	recorder *MockCoreWorkerMockRecorder
}

// MockCoreWorkerMockRecorder is the mock recorder for MockCoreWorker.
type MockCoreWorkerMockRecorder struct {
	mock *MockCoreWorker
}

// NewMockCoreWorker creates a new mock instance.
func NewMockCoreWorker(ctrl *gomock.Controller) *MockCoreWorker {
	mock := &MockCoreWorker{ctrl: ctrl}
	mock.recorder = &MockCoreWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreWorker) EXPECT() *MockCoreWorkerMockRecorder {
	return m.recorder
}

// IndexEthereumTokenOwner mocks base method.
func (m *MockCoreWorker) IndexEthereumTokenOwner(ctx workflow.Context, address string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexEthereumTokenOwner", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexEthereumTokenOwner indicates an expected call of IndexEthereumTokenOwner.
func (mr *MockCoreWorkerMockRecorder) IndexEthereumTokenOwner(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexEthereumTokenOwner", reflect.TypeOf((*MockCoreWorker)(nil).IndexEthereumTokenOwner), ctx, address)
}

// IndexMetadataUpdate mocks base method.
func (m *MockCoreWorker) IndexMetadataUpdate(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMetadataUpdate", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMetadataUpdate indicates an expected call of IndexMetadataUpdate.
func (mr *MockCoreWorkerMockRecorder) IndexMetadataUpdate(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMetadataUpdate", reflect.TypeOf((*MockCoreWorker)(nil).IndexMetadataUpdate), ctx, event)
}

// IndexMultipleTokensMetadata mocks base method.
func (m *MockCoreWorker) IndexMultipleTokensMetadata(ctx workflow.Context, tokenCIDs []domain.TokenCID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMultipleTokensMetadata", ctx, tokenCIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMultipleTokensMetadata indicates an expected call of IndexMultipleTokensMetadata.
func (mr *MockCoreWorkerMockRecorder) IndexMultipleTokensMetadata(ctx, tokenCIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMultipleTokensMetadata", reflect.TypeOf((*MockCoreWorker)(nil).IndexMultipleTokensMetadata), ctx, tokenCIDs)
}

// IndexTezosTokenOwner mocks base method.
func (m *MockCoreWorker) IndexTezosTokenOwner(ctx workflow.Context, address string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTezosTokenOwner", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTezosTokenOwner indicates an expected call of IndexTezosTokenOwner.
func (mr *MockCoreWorkerMockRecorder) IndexTezosTokenOwner(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTezosTokenOwner", reflect.TypeOf((*MockCoreWorker)(nil).IndexTezosTokenOwner), ctx, address)
}

// IndexToken mocks base method.
func (m *MockCoreWorker) IndexToken(ctx workflow.Context, tokenCID domain.TokenCID, skipExistenceCheck bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexToken", ctx, tokenCID, skipExistenceCheck)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexToken indicates an expected call of IndexToken.
func (mr *MockCoreWorkerMockRecorder) IndexToken(ctx, tokenCID, skipExistenceCheck interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexToken", reflect.TypeOf((*MockCoreWorker)(nil).IndexToken), ctx, tokenCID, skipExistenceCheck)
}

// IndexTokenBurn mocks base method.
func (m *MockCoreWorker) IndexTokenBurn(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenBurn", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenBurn indicates an expected call of IndexTokenBurn.
func (mr *MockCoreWorkerMockRecorder) IndexTokenBurn(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenBurn", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokenBurn), ctx, event)
}

// IndexTokenFromEvent mocks base method.
func (m *MockCoreWorker) IndexTokenFromEvent(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenFromEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenFromEvent indicates an expected call of IndexTokenFromEvent.
func (mr *MockCoreWorkerMockRecorder) IndexTokenFromEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenFromEvent", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokenFromEvent), ctx, event)
}

// IndexTokenMetadata mocks base method.
func (m *MockCoreWorker) IndexTokenMetadata(ctx workflow.Context, tokenCID domain.TokenCID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenMetadata", ctx, tokenCID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenMetadata indicates an expected call of IndexTokenMetadata.
func (mr *MockCoreWorkerMockRecorder) IndexTokenMetadata(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenMetadata", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokenMetadata), ctx, tokenCID)
}

// IndexTokenMint mocks base method.
func (m *MockCoreWorker) IndexTokenMint(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenMint", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenMint indicates an expected call of IndexTokenMint.
func (mr *MockCoreWorkerMockRecorder) IndexTokenMint(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenMint", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokenMint), ctx, event)
}

// IndexTokenOwner mocks base method.
func (m *MockCoreWorker) IndexTokenOwner(ctx workflow.Context, address string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenOwner", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenOwner indicates an expected call of IndexTokenOwner.
func (mr *MockCoreWorkerMockRecorder) IndexTokenOwner(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenOwner", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokenOwner), ctx, address)
}

// IndexTokenOwners mocks base method.
func (m *MockCoreWorker) IndexTokenOwners(ctx workflow.Context, addresses []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenOwners", ctx, addresses)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenOwners indicates an expected call of IndexTokenOwners.
func (mr *MockCoreWorkerMockRecorder) IndexTokenOwners(ctx, addresses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenOwners", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokenOwners), ctx, addresses)
}

// IndexTokenProvenances mocks base method.
func (m *MockCoreWorker) IndexTokenProvenances(ctx workflow.Context, tokenCID domain.TokenCID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenProvenances", ctx, tokenCID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenProvenances indicates an expected call of IndexTokenProvenances.
func (mr *MockCoreWorkerMockRecorder) IndexTokenProvenances(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenProvenances", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokenProvenances), ctx, tokenCID)
}

// IndexTokenTransfer mocks base method.
func (m *MockCoreWorker) IndexTokenTransfer(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenTransfer", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenTransfer indicates an expected call of IndexTokenTransfer.
func (mr *MockCoreWorkerMockRecorder) IndexTokenTransfer(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenTransfer", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokenTransfer), ctx, event)
}

// IndexTokens mocks base method.
func (m *MockCoreWorker) IndexTokens(ctx workflow.Context, tokenCIDs []domain.TokenCID, skipExistenceCheck bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokens", ctx, tokenCIDs, skipExistenceCheck)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokens indicates an expected call of IndexTokens.
func (mr *MockCoreWorkerMockRecorder) IndexTokens(ctx, tokenCIDs, skipExistenceCheck interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokens", reflect.TypeOf((*MockCoreWorker)(nil).IndexTokens), ctx, tokenCIDs, skipExistenceCheck)
}
