// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	workflow "go.temporal.io/sdk/workflow"
)

// MockMediaWorker is a mock of Worker interface.
type MockMediaWorker struct {
	ctrl     *gomock.Controller
	recorder *MockMediaWorkerMockRecorder
}

// MockMediaWorkerMockRecorder is the mock recorder for MockMediaWorker.
type MockMediaWorkerMockRecorder struct {
	mock *MockMediaWorker
}

// NewMockMediaWorker creates a new mock instance.
func NewMockMediaWorker(ctrl *gomock.Controller) *MockMediaWorker {
	mock := &MockMediaWorker{ctrl: ctrl}
	mock.recorder = &MockMediaWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaWorker) EXPECT() *MockMediaWorkerMockRecorder {
	return m.recorder
}

// IndexMediaWorkflow mocks base method.
func (m *MockMediaWorker) IndexMediaWorkflow(ctx workflow.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMediaWorkflow", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMediaWorkflow indicates an expected call of IndexMediaWorkflow.
func (mr *MockMediaWorkerMockRecorder) IndexMediaWorkflow(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMediaWorkflow", reflect.TypeOf((*MockMediaWorker)(nil).IndexMediaWorkflow), ctx, url)
}

// IndexMultipleMediaWorkflow mocks base method.
func (m *MockMediaWorker) IndexMultipleMediaWorkflow(ctx workflow.Context, urls []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMultipleMediaWorkflow", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMultipleMediaWorkflow indicates an expected call of IndexMultipleMediaWorkflow.
func (mr *MockMediaWorkerMockRecorder) IndexMultipleMediaWorkflow(ctx, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMultipleMediaWorkflow", reflect.TypeOf((*MockMediaWorker)(nil).IndexMultipleMediaWorkflow), ctx, urls)
}
