// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	workflow "go.temporal.io/sdk/workflow"

	domain "github.com/feral-file/ff-indexer-v2/internal/domain"
)

// MockWorkerCore is a mock of WorkerCore interface.
type MockWorkerCore struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerCoreMockRecorder
}

// MockWorkerCoreMockRecorder is the mock recorder for MockWorkerCore.
type MockWorkerCoreMockRecorder struct {
	mock *MockWorkerCore
}

// NewMockWorkerCore creates a new mock instance.
func NewMockWorkerCore(ctrl *gomock.Controller) *MockWorkerCore {
	mock := &MockWorkerCore{ctrl: ctrl}
	mock.recorder = &MockWorkerCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerCore) EXPECT() *MockWorkerCoreMockRecorder {
	return m.recorder
}

// IndexMetadataUpdate mocks base method.
func (m *MockWorkerCore) IndexMetadataUpdate(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMetadataUpdate", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMetadataUpdate indicates an expected call of IndexMetadataUpdate.
func (mr *MockWorkerCoreMockRecorder) IndexMetadataUpdate(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMetadataUpdate", reflect.TypeOf((*MockWorkerCore)(nil).IndexMetadataUpdate), ctx, event)
}

// IndexTokenBurn mocks base method.
func (m *MockWorkerCore) IndexTokenBurn(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenBurn", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenBurn indicates an expected call of IndexTokenBurn.
func (mr *MockWorkerCoreMockRecorder) IndexTokenBurn(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenBurn", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenBurn), ctx, event)
}

// IndexTokenMetadata mocks base method.
func (m *MockWorkerCore) IndexTokenMetadata(ctx workflow.Context, tokenCID domain.TokenCID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenMetadata", ctx, tokenCID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenMetadata indicates an expected call of IndexTokenMetadata.
func (mr *MockWorkerCoreMockRecorder) IndexTokenMetadata(ctx, tokenCID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenMetadata", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenMetadata), ctx, tokenCID)
}

// IndexTokenMint mocks base method.
func (m *MockWorkerCore) IndexTokenMint(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenMint", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenMint indicates an expected call of IndexTokenMint.
func (mr *MockWorkerCoreMockRecorder) IndexTokenMint(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenMint", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenMint), ctx, event)
}

// IndexTokenTransfer mocks base method.
func (m *MockWorkerCore) IndexTokenTransfer(ctx workflow.Context, event *domain.BlockchainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexTokenTransfer", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexTokenTransfer indicates an expected call of IndexTokenTransfer.
func (mr *MockWorkerCoreMockRecorder) IndexTokenTransfer(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexTokenTransfer", reflect.TypeOf((*MockWorkerCore)(nil).IndexTokenTransfer), ctx, event)
}

// MockWorkerMedia is a mock of WorkerMedia interface.
type MockWorkerMedia struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMediaMockRecorder
}

// MockWorkerMediaMockRecorder is the mock recorder for MockWorkerMedia.
type MockWorkerMediaMockRecorder struct {
	mock *MockWorkerMedia
}

// NewMockWorkerMedia creates a new mock instance.
func NewMockWorkerMedia(ctrl *gomock.Controller) *MockWorkerMedia {
	mock := &MockWorkerMedia{ctrl: ctrl}
	mock.recorder = &MockWorkerMediaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerMedia) EXPECT() *MockWorkerMediaMockRecorder {
	return m.recorder
}
