// Code generated by MockGen. DO NOT EDIT.
// Source: xml.go
//
// Generated by this command:
//
//	mockgen -source=xml.go -destination=../mocks/xml.go -package=mocks -mock_names=XML=MockXML
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockXML is a mock of XML interface.
type MockXML struct {
	ctrl     *gomock.Controller
	recorder *MockXMLMockRecorder
	isgomock struct{}
}

// MockXMLMockRecorder is the mock recorder for MockXML.
type MockXMLMockRecorder struct {
	mock *MockXML
}

// NewMockXML creates a new mock instance.
func NewMockXML(ctrl *gomock.Controller) *MockXML {
	mock := &MockXML{ctrl: ctrl}
	mock.recorder = &MockXMLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXML) EXPECT() *MockXMLMockRecorder {
	return m.recorder
}

// Unmarshal mocks base method.
func (m *MockXML) Unmarshal(data []byte, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", data, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockXMLMockRecorder) Unmarshal(data, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockXML)(nil).Unmarshal), data, v)
}
