name: 'Setup libvips'
description: 'Install libvips 8.18.0 with caching support'

runs:
  using: 'composite'
  steps:
    - name: Cache libvips build
      id: cache-libvips
      uses: actions/cache@v4
      with:
        path: ~/libvips
        key: libvips-install-8.18.0-${{ runner.os }}

    - name: Install libvips build dependencies
      if: steps.cache-libvips.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          meson \
          ninja-build \
          build-essential \
          pkg-config \
          libglib2.0-dev \
          libexpat1-dev

    - name: Build libvips 8.18.0
      if: steps.cache-libvips.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd /tmp
        wget https://github.com/libvips/libvips/releases/download/v8.18.0/vips-8.18.0.tar.xz
        tar xf vips-8.18.0.tar.xz
        cd vips-8.18.0
        meson setup build --prefix=$HOME/libvips
        cd build
        meson compile
        meson install

    - name: Install libvips to system
      shell: bash
      run: |
        sudo cp -r ~/libvips/* /usr/local/
        sudo ldconfig

    - name: Verify libvips version
      shell: bash
      run: |
        pkg-config --modversion vips
        vips --version
