version: "2"

# ================
# Core run options
# ================
run:
  go: "1.21"          # minimum Go version your project supports
  timeout: 10m        # timeout for the linting process
  concurrency: 4      # parallelism (optional – default is auto‑detected)

# =================
# Code formatters
# =================
formatters:
  enable:
    - goimports        # keeps import blocks ordered & grouped
  settings:
    goimports:
      # change to your project’s import path(s)
      local-prefixes:
        - github.com/feral-file/ff-indexer-v2

# =========
# Linters
# =========
linters:
  # v2 replaces the old "disable-all: true" with this:
  default: none        # start from an empty set and opt‑in
  enable:
    # Bugs / correctness
    - govet
    - staticcheck      # includes old gosimple & stylecheck bundles
    - errcheck
    - ineffassign
    - unused

    # Error‑handling hints
    - errorlint
    - errname

    # Security
    - gosec

    # Style / spelling
    - misspell
  settings:
    misspell:
      locale: US       # US or UK spelling dictionary
      ignore-rules:
        - MONITORD

# ==========
# Issues UI
# ==========
issues:
  max-issues-per-linter: 0   # keep unlimited, as before
  max-same-issues: 0         # …
  new: true                  # show only issues on changed lines (handy for CI)
  new-from-merge-base: develop  # compare against the develop branch


# ==========
# CLI output
# ==========
output:
  formats:
    text:
      print-issued-lines: true  # show offending code lines
