package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/feral-file/ff-indexer-v2/internal/api/shared/dto"
	apierrors "github.com/feral-file/ff-indexer-v2/internal/api/shared/errors"
	"github.com/feral-file/ff-indexer-v2/internal/api/shared/types"
)

// ID is the resolver for the id field.
func (r *changeResolver) ID(ctx context.Context, obj *dto.ChangeResponse) (Uint64, error) {
	return Uint64(obj.ID), nil
}

// SubjectType is the resolver for the subject_type field.
func (r *changeResolver) SubjectType(ctx context.Context, obj *dto.ChangeResponse) (string, error) {
	return string(obj.SubjectType), nil
}

// Meta is the resolver for the meta field.
func (r *changeResolver) Meta(ctx context.Context, obj *dto.ChangeResponse) (JSON, error) {
	if obj.Meta == nil {
		return JSON("{}"), nil
	}
	return JSON(obj.Meta), nil
}

// Subject is the resolver for the subject field.
func (r *changeResolver) Subject(ctx context.Context, obj *dto.ChangeResponse) (JSON, error) {
	if obj.Subject == nil {
		return JSON("null"), nil
	}
	// Subject is already an interface{}, we need to marshal it to JSON
	bytes, err := json.Marshal(obj.Subject)
	if err != nil {
		return JSON("null"), nil
	}
	return JSON(bytes), nil
}

// Offset is the resolver for the offset field.
func (r *changeListResolver) Offset(ctx context.Context, obj *dto.ChangeListResponse) (*Uint64, error) {
	return FromNativeUint64(obj.Offset), nil
}

// Total is the resolver for the total field.
func (r *changeListResolver) Total(ctx context.Context, obj *dto.ChangeListResponse) (Uint64, error) {
	return Uint64(obj.Total), nil
}

// TokenID is the resolver for the token_id field.
func (r *enrichmentSourceResolver) TokenID(ctx context.Context, obj *dto.EnrichmentSourceResponse) (Uint64, error) {
	return Uint64(obj.TokenID), nil
}

// VendorJSON is the resolver for the vendor_json field.
func (r *enrichmentSourceResolver) VendorJSON(ctx context.Context, obj *dto.EnrichmentSourceResponse) (JSON, error) {
	if obj.VendorJSON == nil {
		return JSON("{}"), nil
	}
	return JSON(obj.VendorJSON), nil
}

// TriggerIndexing is the resolver for the triggerIndexing field.
func (r *mutationResolver) TriggerIndexing(ctx context.Context, tokenCids []string, addresses []string) (*dto.TriggerIndexingResponse, error) {
	return r.executor.TriggerTokenIndexing(ctx, tokenCids, addresses)
}

// Offset is the resolver for the offset field.
func (r *paginatedOwnersResolver) Offset(ctx context.Context, obj *dto.PaginatedOwners) (*Uint64, error) {
	return FromNativeUint64(obj.Offset), nil
}

// Total is the resolver for the total field.
func (r *paginatedOwnersResolver) Total(ctx context.Context, obj *dto.PaginatedOwners) (Uint64, error) {
	return Uint64(obj.Total), nil
}

// Offset is the resolver for the offset field.
func (r *paginatedProvenanceEventsResolver) Offset(ctx context.Context, obj *dto.PaginatedProvenanceEvents) (*Uint64, error) {
	return FromNativeUint64(obj.Offset), nil
}

// Total is the resolver for the total field.
func (r *paginatedProvenanceEventsResolver) Total(ctx context.Context, obj *dto.PaginatedProvenanceEvents) (Uint64, error) {
	return Uint64(obj.Total), nil
}

// ID is the resolver for the id field.
func (r *provenanceEventResolver) ID(ctx context.Context, obj *dto.ProvenanceEventResponse) (Uint64, error) {
	return Uint64(obj.ID), nil
}

// TokenID is the resolver for the token_id field.
func (r *provenanceEventResolver) TokenID(ctx context.Context, obj *dto.ProvenanceEventResponse) (Uint64, error) {
	return Uint64(obj.TokenID), nil
}

// Chain is the resolver for the chain field.
func (r *provenanceEventResolver) Chain(ctx context.Context, obj *dto.ProvenanceEventResponse) (string, error) {
	return string(obj.Chain), nil
}

// EventType is the resolver for the event_type field.
func (r *provenanceEventResolver) EventType(ctx context.Context, obj *dto.ProvenanceEventResponse) (string, error) {
	return string(obj.EventType), nil
}

// BlockNumber is the resolver for the block_number field.
func (r *provenanceEventResolver) BlockNumber(ctx context.Context, obj *dto.ProvenanceEventResponse) (*Uint64, error) {
	if obj.BlockNumber == nil {
		return nil, nil
	}
	num := Uint64(*obj.BlockNumber)
	return &num, nil
}

// Raw is the resolver for the raw field.
func (r *provenanceEventResolver) Raw(ctx context.Context, obj *dto.ProvenanceEventResponse) (JSON, error) {
	if obj.Raw == nil {
		return JSON("{}"), nil
	}
	return JSON(obj.Raw), nil
}

// Token is the resolver for the token field.
func (r *queryResolver) Token(ctx context.Context, cid string, expand []string, ownersLimit *int, ownersOffset *Uint64, provenanceEventsLimit *int, provenanceEventsOffset *Uint64, provenanceEventsOrder *types.Order) (*dto.TokenResponse, error) {
	expansions := convertExpansionStrings(expand)
	token, err := r.executor.GetToken(ctx, cid, expansions, ownersLimit, ToNativeUint64(ownersOffset), provenanceEventsLimit, ToNativeUint64(provenanceEventsOffset), provenanceEventsOrder)
	if err != nil {
		return nil, err
	}

	if token == nil {
		return nil, apierrors.NewNotFoundError("Token not found")
	}

	return token, nil
}

// Tokens is the resolver for the tokens field.
func (r *queryResolver) Tokens(ctx context.Context, owner []string, chain []string, contractAddress []string, tokenID []string, limit *int, offset *Uint64, expand []string, ownersLimit *int, ownersOffset *Uint64, provenanceEventsLimit *int, provenanceEventsOffset *Uint64, provenanceEventsOrder *types.Order) (*dto.TokenListResponse, error) {
	expansions := convertExpansionStrings(expand)
	chains := convertChainStrings(chain)
	return r.executor.GetTokens(ctx, owner, chains, contractAddress, tokenID, limit, ToNativeUint64(offset), expansions, ownersLimit, ToNativeUint64(ownersOffset), provenanceEventsLimit, ToNativeUint64(provenanceEventsOffset), provenanceEventsOrder)
}

// Changes is the resolver for the changes field.
func (r *queryResolver) Changes(ctx context.Context, tokenCid []string, address []string, since *string, limit *int, offset *Uint64, order *types.Order, expand []string) (*dto.ChangeListResponse, error) {
	expansions := convertExpansionStrings(expand)
	sinceTime, err := parseSinceTimestamp(since)
	if err != nil {
		return nil, fmt.Errorf("invalid since timestamp: %w", err)
	}
	return r.executor.GetChanges(ctx, tokenCid, address, sinceTime, limit, ToNativeUint64(offset), order, expansions)
}

// ID is the resolver for the id field.
func (r *tokenResolver) ID(ctx context.Context, obj *dto.TokenResponse) (Uint64, error) {
	return Uint64(obj.ID), nil
}

// Chain is the resolver for the chain field.
func (r *tokenResolver) Chain(ctx context.Context, obj *dto.TokenResponse) (string, error) {
	return string(obj.Chain), nil
}

// Standard is the resolver for the standard field.
func (r *tokenResolver) Standard(ctx context.Context, obj *dto.TokenResponse) (string, error) {
	return string(obj.Standard), nil
}

// Offset is the resolver for the offset field.
func (r *tokenListResolver) Offset(ctx context.Context, obj *dto.TokenListResponse) (*Uint64, error) {
	return FromNativeUint64(obj.Offset), nil
}

// Total is the resolver for the total field.
func (r *tokenListResolver) Total(ctx context.Context, obj *dto.TokenListResponse) (Uint64, error) {
	return Uint64(obj.Total), nil
}

// TokenID is the resolver for the token_id field.
func (r *tokenMetadataResolver) TokenID(ctx context.Context, obj *dto.TokenMetadataResponse) (Uint64, error) {
	return Uint64(obj.TokenID), nil
}

// OriginJSON is the resolver for the origin_json field.
func (r *tokenMetadataResolver) OriginJSON(ctx context.Context, obj *dto.TokenMetadataResponse) (JSON, error) {
	if obj.OriginJSON == nil {
		return JSON("{}"), nil
	}
	return JSON(obj.OriginJSON), nil
}

// LatestJSON is the resolver for the latest_json field.
func (r *tokenMetadataResolver) LatestJSON(ctx context.Context, obj *dto.TokenMetadataResponse) (JSON, error) {
	if obj.LatestJSON == nil {
		return JSON("{}"), nil
	}
	return JSON(obj.LatestJSON), nil
}

// Change returns ChangeResolver implementation.
func (r *Resolver) Change() ChangeResolver { return &changeResolver{r} }

// ChangeList returns ChangeListResolver implementation.
func (r *Resolver) ChangeList() ChangeListResolver { return &changeListResolver{r} }

// EnrichmentSource returns EnrichmentSourceResolver implementation.
func (r *Resolver) EnrichmentSource() EnrichmentSourceResolver { return &enrichmentSourceResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// PaginatedOwners returns PaginatedOwnersResolver implementation.
func (r *Resolver) PaginatedOwners() PaginatedOwnersResolver { return &paginatedOwnersResolver{r} }

// PaginatedProvenanceEvents returns PaginatedProvenanceEventsResolver implementation.
func (r *Resolver) PaginatedProvenanceEvents() PaginatedProvenanceEventsResolver {
	return &paginatedProvenanceEventsResolver{r}
}

// ProvenanceEvent returns ProvenanceEventResolver implementation.
func (r *Resolver) ProvenanceEvent() ProvenanceEventResolver { return &provenanceEventResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Token returns TokenResolver implementation.
func (r *Resolver) Token() TokenResolver { return &tokenResolver{r} }

// TokenList returns TokenListResolver implementation.
func (r *Resolver) TokenList() TokenListResolver { return &tokenListResolver{r} }

// TokenMetadata returns TokenMetadataResolver implementation.
func (r *Resolver) TokenMetadata() TokenMetadataResolver { return &tokenMetadataResolver{r} }

type changeResolver struct{ *Resolver }
type changeListResolver struct{ *Resolver }
type enrichmentSourceResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type paginatedOwnersResolver struct{ *Resolver }
type paginatedProvenanceEventsResolver struct{ *Resolver }
type provenanceEventResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type tokenResolver struct{ *Resolver }
type tokenListResolver struct{ *Resolver }
type tokenMetadataResolver struct{ *Resolver }
