// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockFxhashClient is a mock of Client interface.
type MockFxhashClient struct {
	ctrl     *gomock.Controller
	recorder *MockFxhashClientMockRecorder
}

// MockFxhashClientMockRecorder is the mock recorder for MockFxhashClient.
type MockFxhashClientMockRecorder struct {
	mock *MockFxhashClient
}

// NewMockFxhashClient creates a new mock instance.
func NewMockFxhashClient(ctrl *gomock.Controller) *MockFxhashClient {
	mock := &MockFxhashClient{ctrl: ctrl}
	mock.recorder = &MockFxhashClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFxhashClient) EXPECT() *MockFxhashClientMockRecorder {
	return m.recorder
}
